module.exports = { tema: "Arbeidsliv", emner: [{ emne: "A2", kilde: "", items: [
["Hva er et mål i norsk arbeidsliv?","At flest mulig voksne har jobb","At alle jobber like mange timer","At flest mulig jobber i industrien"],
["Hvor mange av dem som jobber, jobber i offentlig sektor?","Omtrent en tredel","Omtrent halvparten","Omtrent en tidel"],
["Hvordan kan staten hjelpe bedrifter slik at de beholder jobbene?","Gi penger til bedrifter i vanskelige tider","Si opp mange av de ansatte i staten","Gjøre skatten høyere for bedriftene"],
["Hva kan skje med jobbene når samfunnet blir mer digitalt?","Nye jobber kommer, noen forsvinner","Alle gamle jobber blir tryggere","Det blir like mange jobber som før"],
["Hvor mange arbeidstakere er med i en fagforening?","Omtrent halvparten","Omtrent en tidel","Omtrent ni av ti"],
["Hva er fagforeningens viktigste oppgave?","Å forhandle om lønn og rettigheter","Å finne nye jobber til medlemmene","Å betale lønn når medlemmer er syke"],
["Hva kan arbeidstakerne gjøre hvis de ikke blir enige med arbeidsgiveren?","Gå ut i streik innenfor reglene","Anmelde arbeidsgiveren til politiet","Gi arbeidsgiveren en bot og advarsel"],
["Hva er et verneombud?","En som passer på sikkerheten for de ansatte","En som forhandler om lønn for lederen","En som kontrollerer alle arbeidsplasser"],
["Hva betyr medbestemmelse på jobben?","De ansatte får si sin mening og være med","Sjefen bestemmer alt helt alene","De som har jobbet lengst bestemmer"],
["Hva skjer når forhandlingene er ferdige?","De skriver en avtale som begge må følge","De skriver råd som begge kan velge å følge","De skriver en avtale som lederen kan endre"],
["Hvorfor jobber vi kortere dager i dag enn før?","Fagforeningene kjempet blant annet for dette","Fordi bedriftene ville gi arbeiderne mer fri","Fordi det ble færre arbeidsplasser i landet"],
["Hva forhandler fagforeninger om, i tillegg til lønn?","Arbeidstid, ferie og kurs i jobben","Skattesatser og priser i butikkene","Boligpriser og renter i banken"],
["Hvem må følge arbeidsmiljøloven?","Alle arbeidsgivere og arbeidstakere","Store bedrifter med mange ansatte","Ansatte som jobber for kommunen"],
["Hva står i arbeidsmiljøloven?","Regler om ansettelse, arbeidstid og fravær","Regler om feriepenger og lengde på ferie","Regler om skattetrekk og trygdeavgift"],
["Hvem har hovedansvaret for arbeidsmiljøet?","Arbeidsgiveren","Verneombudet","Fagforeningen"],
["Hvor mye ferie har du rett til etter ferieloven?","Fire uker og én dag","Tre uker og to dager","Fem uker og tre dager"],
["Hvilke penger får du når du har ferie?","Feriepenger","Sykepenger","Dagpenger"],
["Hva bestemmer hvor mye feriepenger du får?","Hvor mye du tjente året før","Hvor mye du har tjent hittil i år","Hvor mange ansatte bedriften har"],
["Hvem bestemmer lovene om arbeidsliv i Norge?","Politikerne på Stortinget","Fagforeninger og arbeidsgivere sammen","Arbeidstilsynet og Nav"],
["Hva er forskjellen på lov og avtale i arbeidslivet?","Lover gjelder for alle, avtaler for noen bransjer","Lover gjelder for noen bransjer, avtaler for alle","Lover gjelder i staten, avtaler i private bedrifter"],
["Hva må arbeidstakeren gjøre etter arbeidsmiljøloven?","Hjelpe til med et godt arbeidsmiljø","Betale for å gjøre arbeidsmiljøet bedre","Velge verneombud blant arbeidsgiverne"],
["Hva kjennetegner en velferdsstat?","Staten og kommunene gir tjenester til innbyggerne","Innbyggerne må selv betale for helse og skole","Private firmaer driver alle offentlige tjenester"],
["Hvilken tanke bygger det norske velferdssamfunnet på?","Likeverd – alle mennesker er like viktige","Konkurranse – de sterke klarer seg best","Tradisjon – alt skal være som før"],
["Hva er en velferdsordning i Norge?","Gratis sykehusopphold","Gratis treningssenter","Gratis bolig og mat"],
["Hvem bestemmer hvilke velferdsordninger Norge har?","Politikerne, gjennom lover og budsjett","Saksbehandlerne på Nav-kontorene","Fagforeninger og arbeidsgivere"],
["Hva er en av Navs oppgaver?","Gi trygd og hjelp til å få jobb","Forhandle om lønn for de ansatte","Kontrollere arbeidsmiljøet på jobben"],
["Hvor finnes Nav-kontor?","I alle kommuner i landet","I Oslo, Bergen og Trondheim","Ingen kontorer, hjelp på nett"],
["Hva må til for at velferdsstaten skal virke?","At mange jobber og betaler skatt","At alle får penger uten å jobbe","At bedriftene betaler all skatt alene"],
["Hva bygger velferdsstaten i stor grad på?","Tillit mellom staten og innbyggerne","Daglig kontroll av alle innbyggerne","Betaling fra hver enkelt bruker"],
["Hvilken jobb finner vi ofte i offentlig sektor?","Sykepleier på offentlig sykehus","Bonde som driver egen gård","Kassemedarbeider i en butikk"],
["Hva er bruttolønn?","Lønn før skatten er tatt ut","Lønn etter at skatten er tatt ut","Lønn med feriepenger og overtid"],
["Hva er en lønnsslipp?","Et dokument til deg om lønn og skattetrekk","Et dokument til Skatteetaten om bolig og inntekt","Et dokument til sjefen om konto og timer"],
["Hvor ofte får man vanligvis lønn?","Én gang i måneden, på en fast dato","Hver uke, vanligvis på fredag","Hver tredje måned, på en fast dato"],
["Hva er riktig om skatt i Norge?","De som tjener mest, betaler mest","Alle betaler det samme beløpet","De som tjener minst, betaler mest"],
["Hvem må trekke skatt fra bruttolønnen?","Arbeidsgiveren","Arbeidstakeren","Banken"],
["Hva bør du gjøre hvis du får ny jobb med høyere lønn?","Si fra til Skatteetaten på nett","Si fra til Nav-kontoret i kommunen","Si fra til kommunen din"],
["Når får alle en skattemelding?","Hvert år i mars eller april","Hver høst, i september eller oktober","Hver måned sammen med lønnsslippen"],
["Hva skjer hvis du har betalt for lite skatt?","Du får en regning som du må betale","Du får lavere lønn neste måned","Du må komme til Skatteetaten"],
["Hva har alle ansatte rett til?","En skriftlig arbeidsavtale","Fast jobb etter tre måneder","Mer lønn etter ett år i jobben"],
["Hva står i en arbeidsavtale?","Hva jobben er, lønn og arbeidstid","Navn og adresse til alle ansatte","Karakterer fra tidligere skoler"],
["Hva er svart arbeid?","Jobb uten kontrakt og uten å betale skatt","Jobb med ulovlige varer, som narkotika","Jobb med ekstra lønn for farlig arbeid"],
["Hva kan skje når du jobber svart?","Du får ikke feriepenger og dagpenger","Du får sykepenger og forsikring på jobb","Du får høyere pensjon når du er gammel"],
["Hvilke næringer var viktigst for 150 år siden?","Jordbruk, skogbruk og fiske","Industri, handel og transport","Helse, skole og barnehage"],
["Hva skjedde på slutten av 1800-tallet?","Det ble bygd fabrikker, og mange flyttet til byene","Fabrikker ble stengt, og folk flyttet til gårdene","Mange nordmenn begynte å jobbe i sykehus"],
["Hvor og når fant man olje i Norge?","I Nordsjøen på slutten av 1960-tallet","I Barentshavet på slutten av 1970-tallet","I Norskehavet på slutten av 1980-tallet"],
["Hvorfor lager vi mer mat enn før, selv om færre er bønder?","Fordi maskiner gjør arbeidet lettere og raskere","Fordi bøndene jobber flere timer enn før","Fordi mange dyrker mat på fritiden"],
["Hvor finner vi flest jobber i Norge i dag?","I serviceyrker, som butikk","I industrien, på fabrikker","I olje- og gassnæringen"],
["Hvilken jobb er et serviceyrke?","Bussjåfør i en by","Bonde på en gård","Fisker på en fiskebåt"],
["Hvor mange av innbyggerne jobbet i jordbruk i 1950?","Mer enn 20 prosent","Omtrent 5 prosent","Mer enn 50 prosent"],
["Hva er en jobbsøknad?","Et brev til arbeidsgiveren om deg selv","Et brev til kommunen om ny jobb","Et brev til Nav om at du søker jobb"],
["Hva er en CV?","Et dokument om jobbene og skolene dine","Et dokument om hvorfor du vil ha jobben","Et dokument om karakterene fra grunnskolen"],
["Hva er viktig på et jobbintervju?","Å gi et fast håndtrykk og se på dem","Å se bort og snakke så lite som mulig","Å komme sent, men være rolig og glad"],
["Hva er viktig i søknad og CV?","At norsken er riktig og alt stemmer","At de er lange og har mange detaljer","At de er skrevet i en uvanlig stil"],
["Hva ser en arbeidsgiver etter når hun eller han skal ansette?","Utdanning, erfaring, referanser og væremåte","Alder, kjønn og hvilken kommune du bor i","Karakterer og utdanning fra kjente skoler"],
["Hva gjelder for ledige jobber i Norge, selv om få er arbeidsledige?","Det er ofte mange som søker på jobbene","Alle som søker jobb får komme på intervju","Man trenger ikke CV når få er arbeidsledige"],
["Hva er en referanse?","En tidligere sjef som sier hvordan du jobbet","En venn som sier hva du liker å gjøre","En i familien som sier hva du er god til"],
["Hva er et nettverk?","Alle du kjenner, møter og har kontakt med","Alle som bor i samme nabolag som deg","Alle som jobber i samme yrke som deg"],
["Hvilke nettsider bruker man for å lete etter jobb?","arbeidsplassen.nav.no og finn.no","regjeringen.no og stortinget.no","skatteetaten.no og udir.no"],
["Hva kan du gjøre for å få referanser og nettverk?","Være i praksis og ta småjobber","Være hjemme og søke på nett","Vente til arbeidsgivere ringer"],
["Hvordan kan man lete etter jobb i Norge?","Via nettverk, nett og vikarbyrå","Via fylkeskommunen og skolene","Via Skatteetaten og Lånekassen"],
["Hva skjer hvis du har betalt for mye skatt?","Du får pengene tilbake","Pengene brukes på neste års skatt","Du får en bot fra Skatteetaten"],
["Hva er en grunn til at kvinner ofte tjener mindre enn menn?","Kvinner jobber oftere deltid og i yrker med lav lønn","Kvinner har ikke lov til å jobbe i alle yrker","Kvinner får ikke være med i en fagforening"],
["Hvem kan forhandle om lønn for deg?","Fagforeningen du er medlem i","Skatteetaten og kommunen","Arbeidstilsynet og Nav"],
["Hva betyr HMS?","Helse, miljø og sikkerhet","Hjelp, medbestemmelse og støtte","Husleie, mat og strøm"],
["Hva er en arbeidsgiver?","Den som ansetter deg og betaler lønn","Den som søker jobb i en bedrift","Den som representerer alle de ansatte"],
["Hvem foreslår nye lover i Norge?","Regjeringen","Fagforeningene","Domstolene"],
["Hva er sosialhjelp?","Hjelp fra Nav når du ikke har penger","Penger som alle voksne får hver måned","Støtte til å kjøpe bolig fra en bank"],
["Hva er barnetrygd?","Penger fra staten til familier med barn","Penger til barn som jobber etter skolen","Penger fra skolen til elevene"],
["Hva er dagpenger?","Penger fra Nav hvis du mister jobben","Penger du får for hver dag du jobber","Penger du får når du har ferie"],
["Hva er pensjon?","Penger du får som gammel etter å ha jobbet","Penger du får første dag i ny jobb","Penger du får når du begynner på skole"],
["Hvem er arbeidsgiver i offentlig sektor?","Staten, fylket eller kommunen","En privat eier eller et aksjeselskap","En fagforening eller en forening"],
["Hva gjør et vikarbyrå?","Finner midlertidige jobber til folk","Gir lån til folk som vil starte bedrift","Kontrollerer at arbeidsgivere betaler skatt"],
["Hvor mange jobber i Norge blir ikke lyst ut?","Mellom 60 og 80 prosent","Mellom 10 og 20 prosent","Mellom 30 og 40 prosent"],
["Hvem kan stille spørsmål på et jobbintervju?","Både arbeidsgiveren og du","Arbeidsgiveren, men ikke du","Du, men ikke arbeidsgiveren"],
["Hva bør du skrive i en jobbsøknad?","Hvorfor du passer til jobben","Hva du vil gjøre i ferien","Hvem du stemte på ved valget"],
["Hva er en streik?","De ansatte stopper arbeidet for å få endring","Sjefen stenger bedriften for å spare penger","De ansatte tar ferie på samme tid"],
["Hva er grønne jobber?","Jobber som er bra for klima og miljø","Jobber i skog og park om sommeren","Jobber der man dyrker mat på gård"],
["Hva er en arbeidstaker?","En som jobber for en bedrift","En som eier en egen bedrift","En som leder en fagforening"],
["Hvem får introduksjonsstønad?","Deltakere i introduksjonsprogrammet","Personer som nettopp har mistet jobben","Studenter ved et norsk universitet"],
["Hvilken næring får flere jobber i dag?","Informasjonsteknologi (IT)","Fabrikker og tung industri","Jordbruk og skogbruk"],
]}]};
