module.exports = { "tema": "Bærekraft", "emner": [
{ "emne": "Bærekraftig utvikling", "kilde": "https://samfunnskunnskap.no/nb/baerekraft/baerekraftig-utvikling.html", "tillegg": ["https://samfunnskunnskap.no/nb/baerekraft.html", "https://www.fn.no/om-fn/fns-baerekraftsmaal"], "items": [
[ "Hva betyr bærekraftig utvikling?", "Vi dekker behovene våre uten å ødelegge for dem som kommer etter oss", "Vi bruker naturen så mye vi vil, så lenge vi har råd til det", "Vi lager flest mulig nye varer, slik at økonomien vokser veldig raskt" ],
[ "Når ble begrepet bærekraftig utvikling kjent over hele verden?", "På slutten av 1980-årene", "På begynnelsen av 1950-årene", "På slutten av 2010-årene" ],
[ "Hvem ledet FNs kommisjon for miljø og utvikling i 1980-årene?", "Gro Harlem Brundtland", "Thorvald Stoltenberg", "Dag Hammarskjöld" ],
[ "Hvilket år la Brundtlandkommisjonen fram rapporten sin?", "1987", "1945", "2015" ],
[ "Hva er FNs bærekraftsmål?", "En felles plan for hele verden", "En norsk lov om natur og miljø", "En avtale om handel i Europa" ],
[ "Hvor mange bærekraftsmål har FN?", "17", "8", "30" ],
[ "Hvilket år ble FNs bærekraftsmål vedtatt?", "2015", "1987", "2001" ],
[ "Innen hvilket år skal FNs bærekraftsmål være nådd?", "2030", "2050", "2100" ],
[ "Hvilke tre deler handler bærekraft om, ifølge FN?", "Miljø, økonomi og sosiale forhold", "Skole, helse og familieliv i landet", "Språk, kultur og religion" ],
[ "Hva handler det første av FNs bærekraftsmål om?", "Å utrydde fattigdom", "Å bygge flere byer", "Å øke handelen" ],
[ "Hvilket av disse er ett av FNs bærekraftsmål?", "Likestilling mellom kjønnene", "Flere bilveier i hvert eneste land", "Mer kjøtt i hvert måltid" ],
[ "Hvem skal jobbe for å nå FNs bærekraftsmål?", "Stater, bedrifter og vanlige folk", "FN og de rikeste landene i verden", "Store firmaer som tjener mye" ],
[ "Hva er klima?", "Gjennomsnittet av været over lang tid", "Været du ser ut av vinduet i dag", "Hvor mye det regner i løpet av en uke" ],
[ "Hva mener de fleste forskere er årsaken til de raske klimaendringene?", "Menneskenes utslipp av klimagasser", "Naturlige endringer i sola og havet", "Vulkaner som får utbrudd" ],
[ "Hva skjer med havet på grunn av klimaendringene?", "Det stiger og blir surere", "Det synker og blir saltere", "Det blir kaldere og renere" ],
[ "Hva betyr ekstremvær?", "Svært kraftig vær, som storm, flom eller tørke", "Vanlig vær som kommer tilbake hver høst", "Vær som er helt likt over hele landet" ],
[ "Hva er en klimagass?", "En gass som holder på varmen rundt jorda", "En gass som gjør lufta kaldere", "En gass som beskytter jorda mot sterk sol" ],
[ "Hvilken klimagass slipper mennesker ut mest av?", "Karbondioksid (CO₂)", "Oksygen (O₂)", "Nitrogen (N₂)" ],
[ "Hva er en fornybar ressurs?", "En naturressurs som fornyer seg selv", "En naturressurs som tar slutt", "En ressurs som er laget på en fabrikk" ],
[ "Hvilken energikilde er fornybar?", "Vind", "Olje", "Kull" ],
[ "Hvilken av disse ressursene kan bli brukt opp for alltid?", "Naturgass", "Solstråler", "Regnvann" ],
[ "Hva kan skje hvis vi bruker en fornybar ressurs for raskt?", "Naturen rekker ikke å fornye den", "Ressursen blir større og sterkere", "Ressursen blir billigere å kjøpe" ],
[ "Hva er kortreist mat?", "Mat som er produsert nær der du bor", "Mat som det går raskt å lage", "Mat som er laget i et land langt borte" ],
[ "Hvorfor er kortreist mat bra for klimaet?", "Det trengs mindre transport", "Maten varer lenger i kjøleskapet", "Maten blir laget uten strøm" ],
[ "Hva er lettere å kontrollere når maten produseres lokalt?", "Sprøytemidler og hvordan dyrene har det", "Prisen på den samme maten i andre land", "Hvor mye mat hver familie spiser" ],
[ "Hva betyr det at et land er selvforsynt med mat?", "Landet produserer nok mat selv", "Landet kjøper mat fra andre land", "Landet gir mat til andre gratis" ],
[ "Samir vil leve mer bærekraftig. Hva kan han gjøre?", "Sykle eller ta bussen til jobben", "Kjøre bil også på de korte turene", "Kjøpe en ny mobil hvert år" ],
[ "Hva er målet med Parisavtalen fra 2015?", "Å begrense oppvarmingen av jorda", "Å stoppe krigene i Europa", "Å gjøre handel mellom land enklere" ]
] },
{ "emne": "Natur og naturressurser", "kilde": "https://samfunnskunnskap.no/nb/baerekraft/natur-og-naturressurser.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/1957-06-28-16", "https://lovdata.no/dokument/NL/lov/2003-07-04-74", "https://www.dsb.no/aktuelt/husk-balforbudet-fra-15.-april", "https://www.regjeringen.no/no/tema/okonomi-og-budsjett/norsk_okonomi/bruk-av-oljepenger-/handlingsregelen/id444338/", "https://norskfriluftsliv.no/hva-er-allemannsretten/slik-er-fiskereglene-i-norge", "https://www.miljodirektoratet.no/ansvarsomrader/friluftsliv/friluftsliv-og-allemannsretten/fiske/"], "items": [
[ "Hva er det viktigste grunnlaget for at Norge har blitt rikt?", "Naturressursene og måten vi bruker dem på", "Store gruver med gull og diamanter i fjellene", "Mange store bilfabrikker rundt om i landet" ],
[ "Hvilke naturressurser er de viktigste i Norge?", "Fisk, skog og olje", "Gull, kull og diamanter", "Ris, kaffe og bomull" ],
[ "Hvor kommer det meste av strømmen i Norge fra?", "Vannkraft", "Solkraft", "Gasskraft" ],
[ "Hvilken energikilde har Norge begynt å bruke mer de senere årene?", "Vindkraft", "Kullkraft", "Atomkraft" ],
[ "Hvorfor kan Norge produsere mye aluminium?", "Vi har mye strøm fra vannkraft", "Vi har mye aluminium i fjellene", "Vi har mange billige arbeidere" ],
[ "Hva brukes tømmer fra norske skoger blant annet til?", "Papir og materialer til hus", "Plastposer og glass til flasker", "Medisiner og vitaminer" ],
[ "Hva er havbruk eller oppdrett?", "Å ale opp fisk, som laks, i merder i sjøen", "Å fiske med store båter langt ute i havet", "Å bygge hus og hytter langs kysten" ],
[ "Hvorfor bestemmer myndighetene hvor mye fisk som kan fiskes?", "Så det blir nok fisk også i fremtiden", "Så fisken blir dyrere i butikkene", "Så turister kan fiske mer om sommeren" ],
[ "Hva er Statens pensjonsfond utland, ofte kalt «oljefondet»?", "Et fond der staten sparer inntektene fra olje og gass", "Et fond som betaler lønn til folk som jobber med olje", "Et fond som eies av de store oljeselskapene" ],
[ "Hva sier handlingsregelen om bruken av oljefondet?", "Staten skal over tid bruke omtrent 3 prosent av fondet", "Staten skal bruke halvparten av fondet hvert år", "Staten skal bruke omtrent 30 prosent av fondet hvert år" ],
[ "Hvorfor sparer Norge oljepengene i et fond?", "Så også fremtidige generasjoner får glede av dem", "Så oljeselskapene kan betale mindre skatt", "Så Norge kan kjøpe mer olje fra andre land" ],
[ "Hva kommer mange turister til Norge for å se?", "Fjordene og midnattssola", "Ørkenen og palmestrendene", "Vulkanene og regnskogen" ],
[ "Hva betyr allemannsretten?", "Alle kan ferdes fritt i naturen", "Alle kan bygge hytte der de vil", "Alle kan hogge trær i skogen" ],
[ "Hva er utmark?", "Strand, myr, skog og fjell", "Hage, åker og gårdsplass", "Parker og plasser inne i byen" ],
[ "Kan du gå over en åker med korn om sommeren?", "Nei, åkeren er innmark", "Ja, hvis du går forsiktig", "Ja, hvis det er en kort tur" ],
[ "Hvor langt fra et hus eller en hytte må teltet ditt stå?", "Minst 150 meter", "Minst 15 meter", "Minst 1500 meter" ],
[ "Hvor lenge kan du vanligvis telte på samme sted uten å spørre grunneieren?", "To døgn", "To uker", "To måneder" ],
[ "Leila vil lage bål i skogen i juli. Hva må hun vite?", "Det er forbudt å tenne bål i skogen da", "Hun må få lov av politiet først", "Bål er lov hvis det er lite" ],
[ "Når er det forbudt å tenne bål i skog og utmark?", "Fra 15. april til 15. september", "Fra 1. juni til 1. august", "Fra 15. oktober til 15. desember" ],
[ "Hvilke plikter har du når du bruker allemannsretten?", "Rydde etter deg og ikke skade natur og dyr", "Betale en avgift til kommunen før turen", "Melde fra til grunneieren hver gang" ],
[ "Hva kan du plukke i skogen etter allemannsretten?", "Bær, sopp og blomster", "Ved fra levende trær", "Egg fra fuglereir" ],
[ "Hva trenger voksne vanligvis for å fiske i elver og innsjøer?", "Fiskekort", "Båtførerbevis", "Jegerprøve" ],
[ "Hvor kan du fiske med stang uten å ha fiskekort?", "I sjøen, langs kysten", "I elver med laks", "I vann på fjellet" ],
[ "Hva må du ha for å gå på jakt i Norge?", "Jegerprøve og lov fra grunneieren", "Fiskekort og lov fra kommunen", "Førerkort og lov fra politiet" ],
[ "Når må hunder være i bånd i hele Norge?", "Fra 1. april til 20. august", "Fra 1. oktober til 1. mars", "Fra 15. juni til 15. juli" ],
[ "Kan du kjøre snøscooter eller ATV hvor du vil i utmark?", "Nei, du trenger som regel tillatelse", "Ja, allemannsretten gjelder også her", "Ja, hvis du kjører sakte og stille" ]
] },
{ "emne": "Natur- og miljøvern", "kilde": "https://samfunnskunnskap.no/nb/baerekraft/natur-og-miljovern.html", "tillegg": ["https://infinitum.no/no/pantesystemet/hva-kan-pantes/", "https://www.mattilsynet.no/mat-og-drikke/merking-av-mat/holdbarhetsmerking-pa-matvarer", "https://www.norgesnasjonalparker.no/", "https://www.miljodirektoratet.no/ansvarsomrader/vernet-natur/norges-verneomrader/"], "items": [
[ "Hva handler natur- og miljøvern om?", "Å ta vare på naturen og miljøet", "Å bygge flere veier i naturen", "Å selge mer tømmer fra de norske skogene" ],
[ "Hva betyr gjenbruk?", "Andre bruker ting du ikke trenger lenger", "Gamle ting blir smeltet om til nye varer", "Søppel blir brent for å lage varme" ],
[ "Hva betyr gjenvinning?", "Gamle ting blir til råvarer for nye produkter", "Du gir de gamle klærne dine til en venn", "Du kjøper en brukt sofa på nettet" ],
[ "Amir kjøper en brukt jakke. Hvorfor er det bra for miljøet?", "Det trengs ikke å lages en ny jakke", "Brukte jakker er laget av plast", "Butikken sorterer søppelet for ham" ],
[ "Hva er kildesortering?", "Å sortere søppelet i ulike typer", "Å kaste alt søppelet i én stor pose", "Å brenne søppelet i hagen" ],
[ "Omtrent hvor mye søppel kaster hver innbygger i Norge i året?", "Flere hundre kilo", "Noen få kilo", "Flere tusen kilo" ],
[ "Hvor kan du levere en gammel sofa eller vaskemaskin?", "På en gjenvinningsstasjon", "I søppeldunken hjemme", "På postkontoret" ],
[ "Hva gjør du med tomme flasker og bokser med pantemerke?", "Leverer dem i en panteautomat", "Kaster dem i restavfallet hjemme", "Legger dem i papirdunken" ],
[ "Hvorfor har vi pant på flasker og bokser?", "Så de blir levert tilbake og gjenvunnet", "Så butikkene kan tjene mer penger", "Så folk kjøper mindre drikke" ],
[ "Hvor leverer du gamle batterier og rester av maling?", "Som farlig avfall, for eksempel på gjenvinningsstasjonen", "I restavfallet hjemme, godt pakket inn i en pose", "I containeren for glass og metall på returpunktet" ],
[ "Fatima har en ødelagt mobil. Hvor kan hun levere den gratis?", "I en butikk som selger elektronikk", "I dunken for matavfall hjemme", "I containeren for glass" ],
[ "Hva er matsvinn?", "Mat som kunne vært spist, blir kastet", "Folk spiser for lite mat hver dag", "Maten blir dyrere i butikken" ],
[ "Omtrent hvor mye av all maten i verden blir kastet?", "En tredjedel", "En tidel", "Tre fjerdedeler" ],
[ "Hva betyr «best før» på en matvare?", "Maten er ofte god også etter datoen", "Maten må kastes dagen etter datoen", "Maten er farlig å spise etter datoen" ],
[ "Hvordan kan du kaste mindre mat?", "Planlegge innkjøp og spise opp rester", "Kjøpe de største pakkene hver gang", "Kaste maten på best før-datoen" ],
[ "Hvor kommer de største utslippene av klimagasser i Norge fra?", "Olje- og gassutvinning", "Fly, båter og ferger", "Jordbruk, skogbruk og fiske" ],
[ "Hvordan har utslippene av klimagasser i Norge endret seg?", "De har gått ned de siste årene", "De har økt raskt de siste årene", "De har vært helt like i mange år" ],
[ "Hva er en nullutslippsbil?", "En bil som ikke slipper ut klimagasser", "En bil som går på både diesel og strøm", "En bil som det er gratis å kjøre" ],
[ "Hva skjedde med bilene i Norge i 2024?", "For første gang var det flere elbiler enn bensinbiler", "Det ble forbudt for folk å kjøpe nye bensinbiler", "Det ble flere dieselbiler enn elbiler på veiene" ],
[ "Hvordan vil myndighetene at flere skal reise i de store byene?", "Med kollektivtransport, sykkel og gange", "Med flere privatbiler og nye veier", "Med drosjer og flere parkeringshus" ],
[ "Hva er en nasjonalpark?", "Et stort naturområde som er vernet", "En stor park midt i hovedstaden", "Et område der staten selger tomter" ],
[ "Hva kan du gjøre i en nasjonalpark?", "Gå på tur og overnatte i telt", "Bygge en hytte uten å spørre", "Kjøre motorsykkel i terrenget" ],
[ "Isbjørnen er fredet. Hva betyr det?", "Det er forbudt å jakte på den", "Den må leve i en dyrehage", "Det er lov å jakte på den om vinteren" ],
[ "Hva er en viktig oppgave for Miljødirektoratet?", "Passe på at miljølovene blir fulgt", "Selge strøm til folk og til bedrifter", "Tømme søppeldunkene i kommunene" ],
[ "Hva sier loven om å kaste søppel i naturen?", "Det er forbudt å forsøple naturen", "Det er lov hvis søppelet er lite", "Det er lov i skogen, men ikke i byen" ],
[ "Hvorfor er plast i havet et problem?", "Dyr kan spise plasten og bli syke", "Plasten gjør vannet i havet varmere", "Plasten gjør at fisken vokser" ]
] }
] };
