module.exports = { "tema": "Menneskerettigheter og demokrati", "emner": [
{ "emne": "Demokratiet i Norge", "kilde": "https://samfunnskunnskap.no/nb/menneskerettigheter-og-demokrati/demokratiet-i-norge.html", "tillegg": ["https://samfunnskunnskap.no/nb/menneskerettigheter-og-demokrati.html", "https://lovdata.no/dokument/NL/lov/1814-05-17", "https://www.stortinget.no/no/Stortinget-og-demokratiet/"], "items": [
[ "Ordet «demokrati» kommer fra gresk. Hva betyr det?", "Folkestyre", "Kongestyre", "Fellesskap" ],
[ "Hvordan styrer folket politikken i Norge?", "De velger representanter ved valg", "De stemmer selv over hver eneste lov", "De sender forslag til kongen" ],
[ "Hva skal flertallet gjøre når det bestemmer politikken?", "Ta hensyn til det mindretallet mener", "Bestemme uten å høre på mindretallet", "La mindretallet avgjøre de store sakene" ],
[ "Hvem setter rammene for hva kommunene kan bestemme?", "Staten", "Fylkeskommunen", "Nabokommunene" ],
[ "Hvilket ansvarsområde har staten?", "Sykehusene", "Barnehagene", "Fylkesveiene" ],
[ "Fylkesveien utenfor huset til Sara har store hull. Hvem har ansvaret?", "Fylkeskommunen", "Kommunen", "Staten" ],
[ "Hva gjør byråkratene i staten og kommunene?", "Setter politikken ut i livet", "Vedtar nye lover og budsjetter", "Dømmer i saker etter loven" ],
[ "Hvor sitter de folkevalgte som vedtar lovene for hele Norge?", "På Stortinget", "I regjeringen", "I kommunestyret" ],
[ "Hvor mange representanter sitter på Stortinget?", "169", "150", "199" ],
[ "Kan det bli nyvalg til Stortinget før fire år har gått?", "Nei, Stortinget sitter i fire år", "Ja, kongen kan kalle inn til nyvalg", "Ja, regjeringen kan kreve nyvalg" ],
[ "Hva er en viktig oppgave for Stortinget?", "Å vedta statsbudsjettet", "Å dømme i rettssaker", "Å lede departementene" ],
[ "Hva betyr det at Stortinget kontrollerer regjeringen?", "Stortinget følger med på det regjeringen gjør", "Stortinget bestemmer hvem som skal bli dommere", "Stortinget svarer på brevene til regjeringen" ],
[ "Amira vil høre en debatt i Stortinget. Kan hun det?", "Ja, alle kan sitte og høre på", "Nei, bare politikere kan være der", "Ja, og hun kan også si sin mening" ],
[ "Hva betyr det at en sak blir sendt på høring?", "Folk og fagmiljøer kan si sin mening", "Saken blir sendt til en domstol", "Stortinget stemmer over saken med en gang" ],
[ "Hvem lager forslag til statsbudsjett hvert år?", "Regjeringen", "Stortinget", "Kongen" ],
[ "Hvem sitter i regjeringen?", "Statsministeren og statsrådene", "Stortingsrepresentantene", "Kongen og dommerne i Høyesterett" ],
[ "Hva kalles møtet mellom kongen og regjeringen hver fredag?", "Statsråd", "Landsmøte", "Rettsmøte" ],
[ "Norge er et konstitusjonelt monarki. Hva betyr det?", "Vi har konge, men folket styrer gjennom valg", "Kongen styrer, og folket gir råd ved valg", "Vi har en president som folket velger" ],
[ "Hva betyr maktfordeling?", "Makten er delt på tre uavhengige myndigheter", "Makten er delt likt mellom de største partiene", "Makten er delt mellom kongen og kirken" ],
[ "Hvem er den dømmende makten i Norge?", "Domstolene", "Stortinget", "Regjeringen" ],
[ "Hvilken statsmakt er regjeringen?", "Den utøvende makten", "Den dømmende makten", "Den lovgivende makten" ],
[ "Hva betyr parlamentarisme?", "Regjeringen må ha støtte fra Stortinget", "Folket velger regjeringen direkte", "Kongen velger regjeringen helt fritt selv" ],
[ "Flertallet på Stortinget har ikke lenger tillit til regjeringen. Hva skjer?", "Regjeringen må gå av", "Stortinget blir oppløst", "Kongen tar over styringen" ],
[ "Hvem danner ny regjering etter et stortingsvalg?", "Ett eller flere politiske partier", "Domstolene sammen med kongen", "Kandidaten med flest stemmer" ]
] },
{ "emne": "Demokratiske rettigheter og plikter", "kilde": "https://samfunnskunnskap.no/nb/menneskerettigheter-og-demokrati/demokratiske-rettigheter-og-plikter.html", "tillegg": ["https://lovdata.no/lov/2005-05-20-28/§287", "https://lovdata.no/lov/1981-05-22-25/§108", "https://lovdata.no/lov/1969-06-13-26", "https://snl.no/%C3%A6rekrenkelse", "https://www.forsvaret.no/forstegangstjeneste/verneplikt", "https://lovdata.no/dokument/NL/lov/2006-05-19-16", "https://www.skatteetaten.no/person/folkeregister/flytte/i-norge/"], "items": [
[ "Hva har vi i et demokrati, i tillegg til frihet og rettigheter?", "Ansvar og plikter", "Makt og privilegier", "Lønn og goder" ],
[ "Gjelder ytringsfriheten også for aviser, radio og tv?", "Ja, den gjelder også for mediene", "Nei, mediene må få lov av staten", "Nei, mediene har ikke ytringsfrihet" ],
[ "Mona blir valgt inn i kommunestyret. Må hun ta imot vervet?", "Ja, som hovedregel har hun plikt til det", "Nei, hun kan si nei uten noen grunn", "Nei, det er helt frivillig å ta vervet" ],
[ "Lise sprer løgner om en kollega. Kan hun straffes for ærekrenkelse?", "Nei, men hun kan måtte betale erstatning", "Ja, hun kan få fengsel i opptil ett år", "Nei, løgner er en del av ytringsfriheten" ],
[ "Er det plikt å stemme ved valg i Norge?", "Nei, å stemme er en rettighet", "Ja, du får bot hvis du ikke stemmer", "Ja, ved stortingsvalg er det plikt" ],
[ "Hva betyr rettssikkerhet?", "Ingen kan få fengsel uten en rettssak", "Politiet bestemmer straffen etter en arrestasjon", "Regjeringen bestemmer hva domstolene gjør" ],
[ "Karim er tiltalt for tyveri. Hva har han rett til?", "En forsvarer som hjelper ham i retten", "Å slippe rettssak hvis han betaler", "Å velge dommeren i saken sin helt selv" ],
[ "En person er «uskyldig til det motsatte er bevist». Hva betyr det?", "Skyld må bevises før noen kan straffes", "Den tiltalte må bevise at hun er uskyldig", "Politiet kan straffe uten bevis i små saker" ],
[ "Hva betyr det at domstolene er uavhengige?", "Ingen kan bestemme hvordan dommerne dømmer", "Dommerne må følge det regjeringen sier", "Dommerne blir valgt av de store partiene" ],
[ "Hva betyr organisasjonsfrihet?", "Du kan bli med i partier og foreninger", "Du må være medlem av en fagforening", "Du kan starte en bedrift uten å betale skatt" ],
[ "Samfunnet bygger på gjensidig tillit. Hva betyr det?", "Folk og myndigheter stoler på hverandre", "Innbyggerne må kontrollere hverandre", "Staten sjekker alt det folk sier" ],
[ "Nadia søker om støtte fra Nav. Hvilken plikt har hun?", "Å gi riktige opplysninger om seg selv", "Å møte på Nav-kontoret hver uke", "Å vise fram vitnemålet sitt" ],
[ "Hvem har plikt til å betale skatt i Norge?", "Folk som tjener penger eller har formue", "Norske statsborgere, ikke utlendinger", "Folk som eier hus eller leilighet" ],
[ "Ali får brev om å vitne i retten. Hva må han gjøre?", "Møte i retten og forklare det han vet", "Bestemme selv om han vil møte", "Sende et brev til politiet i stedet" ],
[ "Hvem har verneplikt blant norske statsborgere?", "Både kvinner og menn", "Menn, men ikke kvinner", "De som melder seg frivillig" ],
[ "Norge har opplæringsplikt. Hva betyr det?", "Barn må få grunnskoleopplæring", "Barn må gå på en privat skole", "Voksne må ta videregående skole" ],
[ "Du er uenig i en lov. Hva er riktig å gjøre?", "Følge loven og jobbe for å endre den", "Bryte loven til den blir endret", "Klage til kongen og vente på svar" ],
[ "Hva kan være en trussel mot demokratiet?", "Lav valgdeltakelse", "Mange politiske partier", "Frie og uavhengige aviser" ],
[ "Du ser en person som er hardt skadet etter en ulykke. Hva sier loven?", "Du må hjelpe eller skaffe hjelp", "Du må vente til politiet kommer", "Du kan gå hvis du har det travelt" ],
[ "Omar flytter til en ny leilighet. Hva må han gjøre?", "Melde flytting til Folkeregisteret", "Søke om lov til å flytte hos kommunen", "Gi beskjed til politiet i den nye byen" ],
[ "Hva er en meddommer i en rettssak?", "En vanlig innbygger som er med og dømmer", "En advokat som forsvarer den tiltalte", "En politimann som leder etterforskningen" ],
[ "Hva betyr offentlighetsprinsippet?", "Alle kan be om å se dokumenter fra det offentlige", "Alle må vise fram skattepapirene sine på nett", "Politikerne må holde møtene sine hemmelige" ]
] },
{ "emne": "Menneskerettigheter", "kilde": "https://samfunnskunnskap.no/nb/menneskerettigheter-og-demokrati/menneskerettigheter.html", "tillegg": ["https://www.fn.no/tema/menneskerettigheter", "https://lovdata.no/dokument/NL/lov/1999-05-21-30", "https://lovdata.no/dokument/NL/lov/1814-05-17", "https://www.nhri.no/om-nim/", "https://www.sivilombudet.no/"], "items": [
[ "Hva betyr det at menneskerettighetene er universelle?", "De gjelder for alle mennesker i verden", "De gjelder for land som har skrevet under", "De gjelder for voksne statsborgere" ],
[ "Hvorfor har vi menneskerettigheter?", "Fordi vi er mennesker", "Fordi vi er statsborgere", "Fordi vi betaler skatt" ],
[ "Når vedtok FN verdenserklæringen om menneskerettighetene?", "I 1948", "I 1945", "I 1965" ],
[ "Hvor mange land er medlemmer i FN i dag?", "193", "150", "250" ],
[ "Hvilken dag er menneskerettighetenes dag?", "10. desember", "17. mai", "24. oktober" ],
[ "Hva sier menneskerettighetene om tortur?", "Tortur er forbudt i alle former", "Tortur er lov under en krig", "Tortur er lov hvis en dommer sier ja" ],
[ "Hva sier Grunnloven om dødsstraff?", "Ingen kan dømmes til døden", "Dødsstraff er lov under en krig", "Domstolene avgjør det i hver sak" ],
[ "Når fikk Grunnloven et eget kapittel om menneskerettigheter?", "I 2014", "I 1905", "I 1948" ],
[ "En vanlig lov og en menneskerettskonvensjon sier ulike ting. Hva gjelder?", "Menneskerettighetene går foran", "Den norske loven går foran", "Kongen bestemmer i hver sak" ],
[ "Hva er Den europeiske menneskerettskonvensjonen (EMK)?", "En avtale om menneskerettigheter i Europa", "En avtale mellom EU-landene om handel", "En domstol for saker mellom bedrifter" ],
[ "Kari mener Norge har brutt rettighetene hennes i EMK. Hvor kan hun klage til slutt?", "Til Den europeiske menneskerettsdomstolen", "Til FNs sikkerhetsråd i New York", "Til kongen og regjeringen i statsråd" ],
[ "Hva gjør Norges institusjon for menneskerettigheter (NIM)?", "Følger med på menneskerettighetene i Norge", "Dømmer personer som bryter menneskerettighetene", "Gir oppholdstillatelse til flyktninger" ],
[ "Hvilken rettighet står i FNs verdenserklæring om menneskerettighetene?", "Retten til frie og hemmelige valg", "Retten til å få en bil fra staten", "Retten til å slippe å betale skatt" ],
[ "Hva sier verdenserklæringen om alle mennesker?", "De er født frie og med samme verd", "De har rett til like mye penger", "De får rettigheter når de blir voksne" ],
[ "Hvem passer på at offentlige kontorer behandler folk riktig?", "Sivilombudet", "Forbrukerrådet", "Barneombudet" ],
[ "Grunnloven sier at alle er like for loven. Hva betyr det?", "Loven gjelder likt for alle mennesker", "Rike personer kan få lavere straff", "Politikere slipper å følge loven" ]
] },
{ "emne": "Valg og politiske partier", "kilde": "https://samfunnskunnskap.no/nb/menneskerettigheter-og-demokrati/valg-og-politiske-partier.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/2023-06-16-62", "https://www.stortinget.no/no/Stortinget-og-demokratiet/Valg-og-konstituering/Stortingsvalg", "https://valgmedarbeiderportalen.valg.no/artikler/regelverksendringer-ny-valglov", "https://lovdata.no/dokument/NL/lov/1814-05-17"], "items": [
[ "Hvilket valg holdes to år etter et stortingsvalg?", "Kommunestyre- og fylkestingsvalg", "Sametingsvalg og folkeavstemning", "Et nytt valg til Stortinget" ],
[ "Det var stortingsvalg i 2025. Når er det neste?", "I 2029", "I 2027", "I 2028" ],
[ "Hva skriver et parti i partiprogrammet sitt?", "Hvilke saker partiet vil jobbe for", "Hvor mange medlemmer partiet har", "Hvem medlemmene stemte på sist" ],
[ "Hvor vedtar partiene programmet sitt?", "På landsmøtet", "På Stortinget", "I statsråd" ],
[ "Hvem kan stille til valg til Stortinget?", "Personer som har stemmerett ved stortingsvalg", "Personer som har bodd i Norge i tre år", "Personer som er medlem i et stort parti" ],
[ "Hvordan kan vi grovt plassere de største partiene i Norge?", "Fra sosialistisk til borgerlig", "Fra religiøs til ikke-religiøs", "Fra nord til sør i landet" ],
[ "Ola og Kari er gift. Må de stemme på samme parti?", "Nei, hver person velger selv", "Ja, familien bør stemme likt", "Ja, det står i valgloven" ],
[ "I hvilken måned er det stortingsvalg i Norge?", "September", "Mai", "Desember" ],
[ "Lina blir 18 år i desember. Kan hun stemme ved valget i september?", "Ja, hun blir 18 i valgåret", "Nei, hun må være 18 på valgdagen", "Nei, hun må vente til hun er 20" ],
[ "Kan du endre rekkefølgen på kandidatene ved stortingsvalg?", "Nei, listene kan ikke endres", "Ja, du kan stryke kandidater", "Ja, du kan skrive inn nye navn" ],
[ "Hva er en personstemme ved kommunestyrevalg?", "Et kryss ved navnet til en kandidat", "En stemme du gir fra utlandet", "En stemme du gir uten legitimasjon" ],
[ "Ved kommunestyrevalg kan du gi «slengere». Hva betyr det?", "Skrive inn kandidater fra andre lister", "Levere stemmen etter at valget er over", "Stemme på to partier samtidig" ],
[ "Hva er sperregrensen ved stortingsvalg?", "Fire prosent av stemmene i hele landet", "Ti prosent av stemmene i hvert fylke", "Én prosent av stemmene i Oslo" ],
[ "Hva er et utjevningsmandat på Stortinget?", "Et sete som gjør fordelingen mer rettferdig", "Et sete som kongen gir til et lite parti", "Et sete til den med flest personstemmer" ],
[ "Hva kalles det når flere partier styrer sammen i regjering?", "En koalisjonsregjering", "En ettpartiregjering", "Et opposisjonsparti" ],
[ "Hva er en mindretallsregjering?", "Regjeringen har ikke flertall på Stortinget", "Regjeringen har færre enn ti statsråder", "Regjeringen styrer i mindre enn fire år" ],
[ "Hva kalles partiene på Stortinget som er utenfor regjeringen?", "Opposisjonen", "Koalisjonen", "Departementet" ],
[ "Hvem bestemmer hvilke kandidater som står på partiets liste?", "Partiet selv, på et nominasjonsmøte", "Valgdirektoratet etter en søknad", "Kommunen der kandidaten bor" ]
] }
] };
