module.exports = { "tema": "Dette er Norge", "emner": [
{ "emne": "Fakta om Norge", "kilde": "https://samfunnskunnskap.no/nb/dette-er-norge/fakta-om-norge.html", "tillegg": ["https://kartverket.no/til-lands/fakta-om-norge/norske-fylke-og-kommunar", "https://lovdata.no/dokument/NL/lov/2021-05-21-42"], "items": [
[ "Hvilke land har grense mot Norge?", "Sverige, Finland og Russland", "Sverige, Danmark og Finland", "Danmark, Estland og Russland" ],
[ "Hvor mange fylker har Norge hatt siden 2024?", "15 fylker", "11 fylker", "19 fylker" ],
[ "Hvor mange kommuner er Norge delt inn i?", "357 kommuner", "157 kommuner", "557 kommuner" ],
[ "Hvor bor omtrent tre av fire innbyggere i Norge?", "Langs kysten", "Inne i fjellene", "Ved svenskegrensen" ],
[ "I hvilken landsdel bor omtrent halvparten av befolkningen?", "På Østlandet", "På Vestlandet", "I Nord-Norge" ],
[ "Hva heter det sørligste punktet på fastlandet i Norge?", "Lindesnes", "Nordkapp", "Preikestolen" ],
[ "Hva er Svalbard?", "En øygruppe i nord som hører til Norge", "En stor fjord på Vestlandet i Norge", "Et fylke i Nord-Norge ved grensen" ],
[ "Hva heter den største innsjøen i Norge?", "Mjøsa", "Glomma", "Sognefjorden" ],
[ "Hva er en isbre?", "Et stort område med is og snø hele året", "Et vann som fryser til is om vinteren", "En vei over fjellet som stenges om vinteren" ],
[ "Hvor stor del av Norge er dyrket mark?", "Omtrent tre prosent", "Omtrent tretti prosent", "Omtrent halvparten" ],
[ "Hvorfor er klimaet i Norge mildere enn man skulle tro?", "Golfstrømmen gir varmt vann langs kysten", "Fjellene stopper kald luft fra Nordpolen", "Det blåser varme vinder fra Russland" ],
[ "Hva betyr midnattssol?", "At sola ikke går ned om natten", "At sola ikke kommer opp om dagen", "At det er fullmåne hele natten" ],
[ "Hva er bokmål og nynorsk?", "To skriftspråk for norsk", "To samiske språk i nord", "To dialekter fra Vestlandet" ],
[ "Hvilke to språk er offisielle språk i Norge?", "Norsk og samisk", "Norsk og svensk", "Norsk og engelsk" ],
[ "Hvorfor øker folketallet i Norge?", "Innvandring, og flere blir født enn dør", "Flere dør enn det blir født hvert år", "Mange nordmenn flytter tilbake fra USA" ],
[ "Hvordan blir en person konge eller dronning i Norge?", "Tittelen går i arv i kongefamilien", "Folket velger en ny konge ved valg", "Stortinget stemmer over hvem det blir" ]
] },
{ "emne": "Likestilling og likeverd", "kilde": "https://samfunnskunnskap.no/nb/dette-er-norge/likestilling-og-likeverd.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/2017-06-16-51", "https://lovdata.no/lov/2005-05-20-28/§185", "https://www.ldo.no/"], "items": [
[ "Hva betyr likeverd?", "At alle mennesker har like stor verdi", "At alle mennesker tjener like mye", "At alle mennesker må tro det samme" ],
[ "Hvilket tilbud er et eksempel på at samfunnet gir like muligheter?", "Norskopplæring for innvandrere", "Gratis bolig til nye familier", "Høyere skatt for unge folk" ],
[ "Likestilling gjelder ikke bare kjønn. Hva gjelder det også?", "Funksjonsevne, religion og alder", "Hvilket fotballag du heier på", "Hvilken mat du liker best" ],
[ "Hvor mange kvinner er i jobb i Norge i dag?", "Nesten like mange som menn", "Omtrent halvparten så mange som menn", "Mange flere kvinner enn menn" ],
[ "Hvem er de fleste lederne i arbeidslivet i Norge?", "Menn – nesten to av tre", "Kvinner – nesten to av tre", "Like mange menn og kvinner" ],
[ "Hvilke fag velger kvinner oftere enn menn å utdanne seg i?", "Omsorg og undervisning", "Teknikk og naturfag", "Data og ingeniørfag" ],
[ "Hva viser undersøkelser om husarbeidet i norske familier?", "Kvinner bruker fortsatt mer tid enn menn", "Menn bruker nå mer tid enn kvinner", "Barna gjør det meste av husarbeidet" ],
[ "Lina har jobbet deltid i mange år. Hva kan det føre til?", "Lavere pensjon når hun blir gammel", "Høyere skatt enn de som jobber fullt", "At hun mister retten til fastlege" ],
[ "Hvem bestemmer hvordan et par deler arbeidet hjemme?", "Paret bestemmer det selv", "Kommunen bestemmer det", "Loven sier hvem som gjør hva" ],
[ "Hva forbyr straffeloven § 185, som ofte kalles rasismeparagrafen?", "Hatefulle ord om noens hudfarge eller religion", "Å kritisere politikerne og regjeringen i avisen", "Å si meningen sin i avisen eller på nett" ],
[ "Hva er målet med rasismeparagrafen?", "Å beskytte minoriteter", "Å beskytte politikere", "Å stoppe kritikk av staten" ],
[ "Hva sier likestillings- og diskrimineringsloven om alder?", "Ingen skal diskrimineres på grunn av alder", "Eldre arbeidstakere skal få mer lønn enn de unge", "Unge søkere skal få jobb før de som er eldre" ],
[ "Ahmed mener han ble diskriminert på jobben. Hvem kan behandle klagen hans?", "Diskrimineringsnemnda", "Forbrukerrådet", "Sivilombudet" ],
[ "Hva betyr «lik lønn for likt arbeid»?", "Samme lønn for samme jobb, uansett kjønn", "De eldste skal få mest lønn i jobben", "Lønnen skal følge prisene i butikken" ],
[ "Sara er på jobbintervju. Kan arbeidsgiveren spørre om hun planlegger å få barn?", "Nei, det er ikke lov å spørre om det", "Ja, hvis jobben er en fast stilling", "Ja, hvis hun er gift eller samboer" ],
[ "Hva betyr universell utforming?", "At flest mulig kan bruke bygg og tjenester", "At nye bygg i en by skal se like ut", "At skoler og sykehus i Norge skal være gratis" ]
] },
{ "emne": "Merke- og helligdager", "kilde": "https://samfunnskunnskap.no/nb/dette-er-norge/merke-og-helligdager.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/1995-02-24-12", "https://lovdata.no/dokument/NL/lov/1947-04-26-1", "https://snl.no/kvinnedagen"], "items": [
[ "Hva er spesielt med 1. nyttårsdag?", "Det er en helligdag, og butikkene er stengt", "Det er en vanlig arbeidsdag for de fleste", "Det er fri for barn, men voksne må jobbe" ],
[ "Er samefolkets dag 6. februar en fridag?", "Nei, men den er en offisiell flaggdag", "Ja, det er en offentlig fridag", "Ja, for dem som bor i Finnmark" ],
[ "Hva markerer mange i Norge 8. mars?", "Den internasjonale kvinnedagen", "Den internasjonale arbeiderdagen", "Samenes nasjonaldag" ],
[ "Siden hvilket år har kvinnedagen blitt markert i Norge hvert år?", "Siden 1972", "Siden 1915", "Siden 1945" ],
[ "Hva minnes kristne i påsken?", "Jesu død og oppstandelse", "Jesu fødsel i Betlehem", "At Jesus ble døpt i elven" ],
[ "Hvilke dager i påsken er helligdager?", "Skjærtorsdag, langfredag, 1. og 2. påskedag", "Palmesøndag og hele uka etter påske", "Langfredag, påskeaften og 3. påskedag" ],
[ "Når er Kristi himmelfartsdag?", "En torsdag 40 dager etter påske", "En søndag 10 dager etter jul", "En mandag 40 dager før påske" ],
[ "Hvor lenge etter Kristi himmelfartsdag kommer pinsen?", "Ti dager etter", "Fire uker etter", "Én dag etter" ],
[ "Hva gjør mange på arbeidernes dag 1. mai?", "Går i tog for politiske saker", "Går i kirken og hører på preken", "Går i tog med skolen og korpset" ],
[ "Hvem er 17. mai først og fremst en dag for?", "Barna", "Soldatene", "Kongefamilien" ],
[ "Hva er det vanlig å gjøre på julaften?", "Spise julemiddag og gi gaver", "Gå i tog med flagg og korps", "Skyte opp raketter ved midnatt" ],
[ "Hvilke dager i julen er helligdager?", "1. og 2. juledag", "Lille julaften og julaften", "Romjulen og nyttårsaften" ],
[ "Hva er konfirmasjon?", "En markering for ungdom rundt 15 år", "En fest når et barn får navnet sitt", "En feiring når et par har vært gift lenge" ],
[ "Meryams klasse lærer om jul på skolen. Hva betyr det for Meryam?", "Hun lærer om jul, men trenger ikke å tro", "Hun må gå i kirken hver søndag i desember", "Hun må bli kristen for å gå på skolen" ]
] },
{ "emne": "Minoritet og majoritet i Norge", "kilde": "https://samfunnskunnskap.no/nb/dette-er-norge/minoritet-og-majoritet-i-norge.html", "tillegg": ["https://www.regjeringen.no/no/tema/urfolk-og-minoriteter/nasjonale-minoriteter/midtspalte/nasjonale-minoriteter/id1404/", "https://www.ssb.no/befolkning/innvandrere/statistikk/innvandrere-og-norskfodte-med-innvandrerforeldre", "https://lovdata.no/dokument/NL/lov/2021-05-21-42"], "items": [
[ "Hva betyr ordet «majoritet»?", "Den største gruppen i et samfunn", "Den eldste gruppen i et samfunn", "Den rikeste gruppen i et samfunn" ],
[ "Hva er en nasjonal minoritet i Norge?", "En gruppe som har bodd her i flere hundre år", "En gruppe som har kommet hit de siste årene", "En gruppe som har flyttet ut av Norge" ],
[ "Hvor mange nasjonale minoriteter har Norge?", "Fem", "To", "Ti" ],
[ "Hvilken gruppe er en nasjonal minoritet i Norge?", "Kvener/norskfinner", "Polske arbeidsinnvandrere", "Svenske pensjonister" ],
[ "Hva er kvensk, romani og romanes?", "Språk til nasjonale minoriteter", "Tre dialekter på Vestlandet", "Samiske ord for reinsdyr" ],
[ "Hva lovet Norge i en avtale om nasjonale minoriteter i 1999?", "Å hjelpe dem å ta vare på kulturen sin", "Å gi dem egne fylker og et eget parlament", "Å la dem slippe å betale skatt" ],
[ "Omtrent hvor mange i Norge er innvandrere eller barn av to innvandrere?", "Mer enn én million", "Omtrent 300 000", "Omtrent tre millioner" ],
[ "Fra hvilket land kommer flest innvandrere i Norge?", "Polen", "Sverige", "Syria" ],
[ "Hva betyr «norskfødt med innvandrerforeldre»?", "Født i Norge av to foreldre født i utlandet", "Født i utlandet, men har bodd i Norge i mange år", "Født i Norge av foreldre som er født i Norge" ],
[ "Hvor i Norge bor det innvandrere?", "I alle kommuner, men flest i byene", "Mest i små bygder langt fra byene", "Mest i Nord-Norge og på Svalbard" ],
[ "Hva er hovedmålet med integreringspolitikken i Norge?", "At innvandrere kan bruke ressursene sine og bidra", "At innvandrere skal glemme kulturen fra hjemlandet", "At innvandrere skal bo i egne bydeler" ],
[ "Hva er en av nøklene til god integrering, ifølge myndighetene?", "Gode norskkunnskaper", "Et norsk etternavn", "En stor bolig" ]
] },
{ "emne": "Religion og livssyn", "kilde": "https://samfunnskunnskap.no/nb/dette-er-norge/religion-og-livssyn.html", "tillegg": ["https://www.ssb.no/kultur-og-fritid/religion-og-livssyn/statistikk/den-norske-kirke", "https://www.ssb.no/kultur-og-fritid/religion-og-livssyn/statistikk/trus-og-livssynssamfunn-utanfor-den-norske-kyrkja", "https://lovdata.no/dokument/NL/lov/2020-04-24-31", "https://lovdata.no/dokument/NL/lov/1814-05-17"], "items": [
[ "Norge er et sekulært samfunn. Hva betyr det?", "Religion styrer ikke lovene og samfunnet", "Religion bestemmer hvordan lovene blir", "Kirken bestemmer hva skolen lærer bort" ],
[ "Omtrent hvor mange av de døde i Norge får gravferd i kirken?", "Omtrent åtte av ti", "Omtrent to av ti", "Omtrent fire av ti" ],
[ "Hva kaller Grunnloven Den norske kirke i dag?", "Norges folkekirke", "Norges statsreligion", "Kongens egen kirke" ],
[ "Omtrent hvor mange i Norge er medlem av Den norske kirke?", "Omtrent seks av ti", "Omtrent to av ti", "Omtrent ni av ti" ],
[ "Hvilken retning i kristendommen hører Den norske kirke til?", "Den lutherske", "Den katolske", "Den ortodokse" ],
[ "Jonas er kristen, men vil bli buddhist. Hvem bestemmer det?", "Jonas bestemmer det selv", "Familien hans bestemmer", "Presten må gi tillatelse" ],
[ "Hvordan får tros- og livssynssamfunn støtte fra staten?", "Støtte etter hvor mange medlemmer de har", "Støtte etter hvor gamle byggene deres er", "Støtte hvis de har en kristen tro" ],
[ "Hva er et livssynssamfunn, for eksempel Human-Etisk Forbund?", "Et fellesskap med et livssyn uten gud", "En kristen menighet i Den norske kirke", "Et politisk parti som er imot religion" ],
[ "Hvilken religion har flest medlemmer i Norge etter kristendommen?", "Islam", "Buddhisme", "Hinduisme" ],
[ "Hva ble lov for nordmenn i 1845?", "Å melde seg ut av statskirken", "Å gifte seg uten prest", "Å stemme ved stortingsvalg" ],
[ "Hvorfor gifter mange seg i kirken selv om de ikke er religiøse?", "Det er en tradisjon som betyr mye for dem", "Loven sier at bryllup skal være i kirken", "Kommunen tar ikke imot bryllup" ],
[ "Hvordan ser mange i Norge på religion?", "Som en privatsak for hver enkelt", "Som noe staten skal bestemme", "Som noe man snakker om på jobben" ]
] },
{ "emne": "Samene", "kilde": "https://samfunnskunnskap.no/nb/dette-er-norge/samene.html", "tillegg": ["https://snl.no/Sametinget", "https://sametinget.no/", "https://snl.no/samenes_nasjonaldag"], "items": [
[ "Hva betyr det at samene er Norges urfolk?", "De bodde i området før dagens grenser ble laget", "De kom til Norge som flyktninger etter krigen", "De er en ny folkegruppe fra Russland" ],
[ "I hvilke land bor det samer?", "Norge, Sverige, Finland og Russland", "Norge, Sverige, Danmark og Island", "Norge, Finland, Estland og Polen" ],
[ "Hva skjedde i Trondheim 6. februar 1917?", "Det første samiske landsmøtet", "Sametinget åpnet for første gang", "Samene fikk sitt eget flagg" ],
[ "Hva er en kofte?", "En samisk folkedrakt", "Et samisk musikkinstrument", "Et samisk telt av skinn" ],
[ "Hva er joik?", "En gammel samisk måte å synge på", "En samisk rett med reinkjøtt", "En samisk dans rundt bålet" ],
[ "Kan en som bare snakker norsk, forstå samisk?", "Nei, språkene er helt forskjellige", "Ja, samisk er en norsk dialekt", "Ja, språkene ligner mye på hverandre" ],
[ "Hva betyr fornorsking av samene?", "Staten prøvde å gjøre samene norske", "Samene flyttet frivillig til byer i sør", "Staten ga samene eget land i Finnmark" ],
[ "Når ble det igjen tillatt å bruke samisk i skolen?", "I 1959", "I 1905", "I 1989" ],
[ "Hva jobber Sametinget med?", "Samenes rettigheter, kultur og språk", "Skatt og forsvar for hele Norge", "Olje og fiske i Nordsjøen" ],
[ "Hva må du gjøre for å kunne stemme ved sametingsvalget?", "Stå i Sametingets valgmanntall", "Bo i Finnmark i minst fem år", "Eie reinsdyr eller en gård" ]
] }
] };
