module.exports = { "tema": "Fritid", "emner": [
{ "emne": "Politisk engasjement", "kilde": "https://samfunnskunnskap.no/nb/fritid/politisk-engasjement.html", "tillegg": ["https://lovdata.no/lov/2023-06-16-62", "https://lovdata.no/lov/2018-06-22-83/kap12", "https://www.minsak.no/", "https://www.politiet.no/tjenester/arrangementer", "https://www.regjeringen.no/no/tema/valg-og-demokrati/den-norske-valgordningen/kommunestyre-og-fylkestingsvalg/id2989114/"], "items": [
[ "Hvem har ansvar for at demokratiet skal fungere?", "Alle som bor i landet", "Politikerne på Stortinget", "Kongen og regjeringen" ],
[ "Yusuf er 16 år. Kan han lage et innbyggerforslag i kommunen?", "Ja, det krever ikke stemmerett", "Nei, han må vente til han er 18", "Nei, han må være norsk statsborger" ],
[ "Hva skjedde med valgdeltakelsen til de yngste velgerne fra 2007 til 2011?", "Den økte med mer enn ti prosent", "Den gikk ned med mer enn ti prosent", "Den var nesten helt lik" ],
[ "Hva har skjedd med medlemstallene i politiske ungdomsorganisasjoner?", "Flere har blitt medlemmer", "Færre har blitt medlemmer", "Mange av dem er lagt ned" ],
[ "Hvilke demokratiske ferdigheter kan du trene på i en organisasjon?", "Å diskutere, stemme og velge et styre", "Å skrive lover og dømme i en rettssak", "Å kontrollere regnskapet til staten" ],
[ "Hva er et eksempel på uformell politisk deltakelse?", "Å skrive under på en underskriftskampanje", "Å stille til valg for et politisk parti", "Å jobbe i valgkampen for et parti" ],
[ "Hva er et eksempel på formell politisk deltakelse?", "Å fremme en sak i et politisk parti", "Å diskutere politikk på sosiale medier", "Å gå i et demonstrasjonstog i byen" ],
[ "Hva betyr det å være politisk engasjert?", "Å bry seg om og delta i samfunnssaker", "Å jobbe som politiker og få lønn for det", "Å lese om politikk uten å ha meninger" ],
[ "Hva er en demonstrasjon?", "Folk samles ute for å vise hva de mener", "Et møte der politikerne vedtar en ny lov", "En dag der folk stemmer på et parti" ],
[ "Leila vil arrangere en demonstrasjon i sentrum. Hva må hun gjøre?", "Melde fra til politiet i god tid", "Søke om lov fra Stortinget", "Få en underskrift fra ordføreren" ],
[ "Hva er en underskriftskampanje?", "Mange skriver navnet sitt for å støtte en sak", "En liste over folk som har stemt ved valget", "Et skjema du fyller ut for å bli partimedlem" ],
[ "Kari er imot en ny bomring. Hva kan hun gjøre for å bli hørt?", "Skrive et innlegg i avisen", "Slutte å betale skatt til kommunen", "Kjøre gjennom bommen uten å betale" ],
[ "Hva er et leserinnlegg i en avis?", "En tekst der en leser skriver sin mening", "En nyhetssak skrevet av en journalist", "En annonse som et parti betaler for" ],
[ "Hva er en interesseorganisasjon?", "En gruppe som jobber for en felles sak", "Et firma som tjener penger på en sak", "Et kontor i kommunen som tar imot klager" ],
[ "Hvordan kan du bli medlem i et politisk parti?", "Du melder deg inn og betaler medlemsavgift", "Du må først bli valgt av kommunestyret", "Du må ha vært norsk statsborger i ti år" ],
[ "Hva er en politisk ungdomsorganisasjon?", "En del av et parti der unge medlemmer er aktive", "En klubb der unge trener sammen etter skolen", "Et kontor i kommunen som hjelper unge med jobb" ],
[ "Samir er utenlandsk statsborger med fire år i Norge. Hvilke valg kan han stemme ved?", "Kommunestyrevalget og fylkestingsvalget", "Stortingsvalget og kommunestyrevalget", "Ingen valg før han er statsborger" ],
[ "Hvor lenge må utenlandske statsborgere ha bodd i Norge for å stemme ved kommunestyrevalg?", "Tre år", "Ett år", "Sju år" ],
[ "Hvor mange år går det mellom hvert kommunestyrevalg?", "Fire år", "To år", "Seks år" ],
[ "Hva velger innbyggerne ved kommunestyrevalget?", "Politikerne som skal styre kommunen", "Ordføreren som skal lede Stortinget", "De ansatte som skal jobbe i kommunen" ],
[ "Hvem bestemmer til slutt hvor ofte bussene går?", "Politikere som innbyggerne har valgt", "Sjåførene som kjører bussene hver dag", "Passasjerene som tar bussen til jobb" ],
[ "Hva betyr det at valget er hemmelig?", "Ingen ser hva du stemmer", "Partiet ditt får vite hva du stemmer", "Valget skjer på et hemmelig sted" ],
[ "Hva må du ta med når du skal stemme?", "Legitimasjon, for eksempel pass", "Et brev fra arbeidsgiveren din", "En kvittering for at du har betalt skatt" ],
[ "Ali skal reise bort på valgdagen. Hva kan han gjøre?", "Forhåndsstemme før valgdagen", "Stemme på telefon etter valget", "Be naboen stemme for ham" ],
[ "Hva må du ha for å stille til valg til kommunestyret?", "Stemmerett og bosted i kommunen", "Norsk statsborgerskap og fylt 25 år", "Medlemskap i et parti i ti år" ],
[ "Hva er et innbyggerforslag?", "Et forslag fra innbyggerne som kommunestyret må behandle", "Et forslag fra ordføreren som innbyggerne må stemme over", "En klage fra en innbygger som politiet må behandle" ],
[ "Hvor kan du lage et innbyggerforslag på nettet?", "På minsak.no", "På valg.no", "På nav.no" ],
[ "Hva er et ungdomsråd i kommunen?", "Et råd der unge sier sin mening til kommunen", "En klubb der unge kan trene og spille sammen", "Et kontor som hjelper unge med å finne jobb" ],
[ "Hva gjør partiene i en valgkamp?", "De forteller velgerne om politikken sin", "De teller stemmene etter at valget er over", "De bestemmer hvem som har stemmerett" ],
[ "Hvorfor sier noen at «alt er politikk»?", "Politikk påvirker mye i hverdagen vår", "Politikere bestemmer hva vi skal mene", "Hver innbygger må være med i et parti" ],
[ "Hvordan ser det norske samfunnet på at folk engasjerer seg politisk?", "Det blir sett på som positivt og viktig", "Det blir sett på som farlig og dumt", "Det blir sett på som en jobb for eliten" ],
[ "Må du være med i et parti for å engasjere deg politisk?", "Nei, du kan engasjere deg på mange måter", "Ja, det krever medlemskap i et parti", "Ja, og du må ha bodd i Norge i ti år" ]
] },
{ "emne": "Dugnad", "kilde": "https://samfunnskunnskap.no/nb/fritid/dugnad.html", "tillegg": ["https://snl.no/dugnad"], "items": [
[ "Hva er dugnad?", "Frivillig, ubetalt arbeid i et fellesskap", "Betalt ekstraarbeid for kommunen i helgene", "Arbeid du må gjøre for arbeidsgiveren din" ],
[ "Er dugnad en ny eller gammel tradisjon i Norge?", "Den er en gammel skikk", "Den startet rundt år 2000", "Den kom fra USA nylig" ],
[ "Har bare Norge tradisjonen med dugnad?", "Nei, mange landbrukssamfunn har noe lignende", "Ja, dugnad ble funnet opp i Norge", "Nei, den kommer fra byer i Sør-Europa" ],
[ "Hvilket ord ble kåret til Norges nasjonalord i 2004?", "Dugnad", "Kos", "Friluftsliv" ],
[ "Hva er det vanlig å servere på en dugnad?", "Vafler og kaffe", "Suppe og te", "Fisk og poteter" ],
[ "Hvorfor har mange borettslag dugnad om våren?", "For å gjøre det pent ute etter vinteren", "For å velge et nytt styre i borettslaget", "For å betale husleien for neste år" ],
[ "Hva gjør foreldre ofte på dugnad i barnehagen?", "Vasker leker og fikser uteområdet", "Lager timeplaner for de ansatte", "Betaler regningene til barnehagen" ],
[ "Hvorfor lager foreldre i en forening ofte loppemarked?", "For å få inn penger til foreningen", "For å få penger til sin egen familie", "For å bli kvitt søppel uten å betale" ],
[ "Hva er et loppemarked?", "Et marked der brukte ting blir solgt", "Et marked der nye klær blir solgt billig", "En butikk der kommunen selger møbler" ],
[ "Hvem driver mange av fritidsaktivitetene for barn i Norge?", "Foreldre som jobber på dugnad", "Ansatte som får lønn av staten", "Lærere som jobber på skolen" ],
[ "Må du delta når det er dugnad?", "Nei, men det er forventet at du deltar", "Ja, det står i loven at du må delta", "Nei, og ingen bryr seg om du kommer" ],
[ "Noen familier kommer aldri på dugnad. Hvorfor kan andre reagere på det?", "Alle får nytte av det andre gjør", "Det er ulovlig å ikke komme", "Familiene må da betale en bot" ],
[ "Leo kan ikke komme på dugnaden. Hva bør han gjøre?", "Si fra og tilby å hjelpe en annen gang", "Bli hjemme uten å si noe til noen", "Sende en klage til styret i laget" ],
[ "Hva lar noen lag foreldrene gjøre i stedet for å delta på dugnad?", "Betale et beløp til laget", "Sende barna på dugnaden alene", "Skrive en klage til laget" ],
[ "Hva kan du få ut av å delta på dugnad?", "Bli kjent med naboer og andre", "Få betalt for timene du jobber", "Få lavere skatt fra kommunen" ],
[ "Hva betydde ordet «dugnad» opprinnelig?", "Hjelp og støtte", "Plikt og straff", "Penger og lønn" ],
[ "Hva hjalp folk hverandre med på dugnad i gamle dager?", "Å bygge hus og legge tak", "Å betale skatt til kongen", "Å lære barna å lese" ],
[ "Hvem pleier å arrangere dugnad?", "Idrettslag og borettslag", "Banker og butikker", "Bedrifter og fabrikker" ],
[ "Er dugnad vanlig på arbeidsplasser der folk får lønn?", "Nei, det er vanlig i lag og foreninger", "Ja, det er en del av arbeidstiden", "Ja, det står i arbeidsavtalen" ],
[ "Hvem kaller vanligvis inn til dugnad i et borettslag?", "Styret i borettslaget", "Kommunen der borettslaget er", "Politiet i området" ],
[ "Hvorfor er dugnad viktig for mange lag og foreninger?", "De sparer penger fordi folk jobber gratis", "De får penger fra staten for hver dugnad", "Medlemmene får lønn når de jobber der" ],
[ "Hva gjør beboere ofte på en vårdugnad?", "Raker løv og planter blomster", "Maler leilighetene til hverandre", "Bytter vinduer i husene" ],
[ "Kan barn være med på dugnad?", "Ja, barn er ofte med og hjelper til", "Nei, det er forbudt for barn under 18", "Nei, barn må være i barnehagen da" ],
[ "Hva kan skje hvis du aldri stiller opp på dugnad?", "Andre kan bli irritert på deg", "Du kan få bot fra politiet", "Du kan miste jobben din" ]
] },
{ "emne": "Sosiale arenaer", "kilde": "https://samfunnskunnskap.no/nb/fritid/sosiale-arenaer.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/1985-12-20-108", "https://www.bufdir.no/prosjekter/fritidserklaringen/", "https://frivilligsentral.no/"], "items": [
[ "Hva er en sosial arena?", "Et sted der folk møtes og er sammen", "En app der du kan dele bilder", "Et sted der folk kan være alene" ],
[ "Hvilket sted er en viktig sosial arena for mange voksne?", "Arbeidsplassen", "Bankkontoen", "Postkassen" ],
[ "Hva er et eksempel på en organisert fritidsaktivitet for barn?", "Å spille i korps", "Å se på TV hjemme", "Å leke alene i hagen" ],
[ "Hvordan kan barnas fritidsaktiviteter hjelpe foreldre som er nye på et sted?", "De kan bli kjent med folk i nærmiljøet", "De kan få lønn for å kjøre barna", "De slipper å snakke med andre voksne" ],
[ "Hva gjør foreldre ofte når barna har fritidsaktiviteter?", "De bytter på å kjøre barna", "De betaler lønn til trenerne", "De bestemmer reglene i idretten" ],
[ "Hva er forskjellen på frivillig arbeid og en vanlig jobb?", "Frivillige får ikke lønn", "Frivillige jobber full tid", "Frivillige betaler ikke skatt" ],
[ "Hvor mye jobber en frivillig vanligvis?", "Noen timer i blant", "Full tid hver uke", "Hver natt hele året" ],
[ "Hvilken organisasjon er et eksempel på frivillig arbeid?", "Røde Kors", "Skatteetaten", "Nav" ],
[ "Hvordan kan frivillige organisasjoner påvirke politikken?", "De sier sin mening til politikerne", "De vedtar nye lover for landet", "De bestemmer budsjettet til kommunen" ],
[ "Hva kan du få ved å være frivillig?", "Et større nettverk og nye venner", "Lønn og feriepenger fra laget", "Lavere skatt og gratis bolig" ],
[ "Hva er en uskreven regel?", "En regel som ikke er skrevet ned", "En regel som politiet gir bøter for", "En regel som står i en norsk lov" ],
[ "Hvordan er uskrevne regler i ulike kulturer?", "De er forskjellige", "De er helt like", "De finnes ikke i Norge" ],
[ "Hvordan hilser kvinner og menn ofte når de møtes første gang?", "De tar hverandre i hånden", "De bukker for hverandre", "De kysser hverandre på kinnet" ],
[ "Hvordan hilser venner ofte på hverandre i Norge?", "De sier «hei» eller gir en klem", "De bukker dypt for hverandre", "De kysser hverandre tre ganger" ],
[ "Hva svarer man ofte når noen sier «Hei, hvordan går det»?", "«Takk, bare bra. Og med deg?»", "«Det har jeg ikke tid til nå»", "«Det vil jeg ikke snakke om»" ],
[ "Ole vil gjerne besøke deg en dag. Hva bør du gjøre?", "Avtale en bestemt dag og tid", "Vente på at han kommer en dag", "Lage mat hver dag til han kommer" ],
[ "Hva er vanlig når nordmenn skal besøke venner?", "De avtaler besøket på forhånd", "De kommer uten å si fra først", "De kommer sent på kvelden" ],
[ "Du møter en venn du besøkte forrige uke. Hva sier du ofte?", "«Takk for sist»", "«Takk for maten»", "«God bedring»" ],
[ "Hva er et folkebibliotek?", "En gratis møteplass der du kan låne bøker", "En butikk der du kan kjøpe brukte bøker", "Et kontor der du kan søke om bolig" ],
[ "Hvor skal det finnes et folkebibliotek ifølge loven?", "I alle kommuner i Norge", "Bare i de største byene", "Bare på skoler og universiteter" ],
[ "Hva er målet med fritidserklæringen?", "At alle barn kan være med på en fritidsaktivitet", "At barn skal trene minst fem dager i uken", "At barn skal slutte med aktiviteter i ferien" ],
[ "Hva er en frivilligsentral?", "Et sted som skaffer frivillige oppgaver", "Et kontor som skaffer folk fast jobb", "En butikk som selger utstyr til lag" ],
[ "Nadia vil bli kjent med folk der hun bor. Hva kan hun gjøre?", "Bli med i et lag eller en forening", "Vente til naboene banker på døren", "Flytte til en større by i et annet fylke" ],
[ "Alle vennene til Omar spiller fotball, men Omar får ikke være med. Hva kan skje?", "Omar kan føle seg utenfor", "Omar får bedre karakterer på skolen", "Omar får flere venner på skolen" ]
] }
] };
