module.exports = { "tema": "Familieliv", "emner": [
{ "emne": "Ekteskap og familie", "kilde": "https://samfunnskunnskap.no/nb/familieliv/ekteskap-og-familie.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/1991-07-04-47", "https://lovdata.no/dokument/NL/lov/1981-04-08-7", "https://www.bufdir.no/familie/samlivsbrudd/mekling/", "https://www.bufdir.no/familie/par/", "https://www.nav.no/barnebidrag"], "items": [
[ "Hva er en husholdning?", "Personer som bor sammen og har felles økonomi", "Personer som er i slekt og bor i samme land", "Personer som bor i samme gate og kjenner hverandre" ],
[ "Hva er en kjernefamilie?", "Foreldre og barna deres", "Besteforeldre, tanter og onkler", "Naboer som hjelper hverandre" ],
[ "Hva er en storfamilie?", "Flere generasjoner og slektninger som bor sammen", "Foreldre og barn som bor i et stort hus", "Venner som deler en stor leilighet sammen" ],
[ "Hvilken familie kan også være en kjernefamilie i Norge i dag?", "To mødre og barna deres", "Tre venner som deler leilighet", "Naboer i samme borettslag" ],
[ "Omtrent hvor mange personer bor i en norsk husholdning?", "Litt mer enn to", "Litt mer enn fire", "Litt mer enn seks" ],
[ "Omtrent hvor mange av parene som bor sammen, er gift?", "Omtrent sju av ti", "Omtrent tre av ti", "Omtrent ni av ti" ],
[ "Siden hvilket år har to av samme kjønn kunnet gifte seg i Norge?", "Siden 2009", "Siden 1989", "Siden 2019" ],
[ "Omtrent hvor mange av dem som gifter seg, vil trolig skille seg?", "Omtrent fire av ti", "Omtrent én av ti", "Omtrent åtte av ti" ],
[ "Hvor kan et par gifte seg uten en religiøs seremoni?", "Hos kommunen", "Hos Nav-kontoret", "Hos politiet" ],
[ "Hva har ektefeller plikt til ifølge loven?", "Å forsørge hverandre", "Å ha samme religion", "Å bo nær familien" ],
[ "Et ektepar tar opp et lån sammen. Hvem er ansvarlig for lånet?", "Begge ektefellene", "Den som tjener mest", "Den som er eldst" ],
[ "Ali og Sara er ikke gift og får et barn. Hvem har foreldreansvaret?", "Både Ali og Sara", "Sara, fordi hun er moren", "Ali, fordi han er faren" ],
[ "Hva betyr foreldreansvar?", "Rett og plikt til å ta avgjørelser for barnet", "Plikt til å betale skatt for barnet hvert år", "Rett til å velge hvem barnet skal gifte seg med" ],
[ "Hva betyr det å være separert?", "Man er gift, men bor ikke lenger sammen", "Man er skilt og gift med en ny person", "Man er forlovet, men ikke gift ennå" ],
[ "Hvor lenge må man vanligvis være separert før man kan skilles?", "Minst ett år", "Minst tre år", "Minst fem år" ],
[ "Når kan man få skilsmisse med en gang, uten separasjon?", "Når det har vært vold i ekteskapet", "Når en av dem vil flytte til en annen by", "Når de har krangler om penger" ],
[ "Et ektepar med barn under 16 år vil skilles. Hva må de gjøre først?", "Gå til mekling", "Gå til politiet", "Gå til barnevernet" ],
[ "Hva er målet med mekling når foreldre skal skilles?", "Å bli enige om ordninger for barna", "Å finne ut hvem som har skylden", "Å bestemme hvem som får beholde huset" ],
[ "Anna og Morten krangler mye. Hvor kan de få hjelp som par?", "På et familievernkontor", "På et skattekontor", "På et legevaktkontor" ],
[ "Hvem har rett og plikt til omsorg for barnet etter en skilsmisse?", "Både moren og faren", "Den som får beholde huset", "Den som tjener mest penger" ],
[ "Hva betyr «delt bosted» for et barn med skilte foreldre?", "Barnet bor omtrent like mye hos begge", "Barnet bor fast hos besteforeldrene", "Barnet bor på internat i skoleåret" ],
[ "Hva er barnebidrag?", "Penger fra forelderen som barnet ikke bor fast hos", "Penger fra skolen til barn i familier med lav inntekt", "Penger fra banken når et barn blir født" ],
[ "Hva gjelder for samboere sammenlignet med ektepar?", "De har ikke automatisk de samme rettighetene", "De har nøyaktig de samme rettighetene", "De har flere rettigheter enn ektepar" ],
[ "Hvorfor skriver mange samboere en avtale hos en advokat?", "For å avtale arv og deling av verdier", "For å få lov til å bo sammen", "For å få lov til å få barn sammen" ]
] },
{ "emne": "Å leve i to kulturer", "kilde": "https://samfunnskunnskap.no/nb/familieliv/a-leve-i-to-kulturer.html", "tillegg": ["https://www.helsenorge.no/barn/sprakutvikling-hos-barn/", "https://www.statped.no/tiltak-og-tilrettelegging/dld/hvilket-sprak-bor-flerspraklige-foreldre-snakke-med-sine-barn/", "https://www.imdi.no/"], "items": [
[ "Hva lærer vi i den kulturen vi vokser opp i?", "Hvordan vi skal leve sammen", "Hvilken jobb vi skal ha", "Hvor mye penger vi skal tjene" ],
[ "Hvem og hva lærer barn kultur og verdier av?", "Av foreldrene og samfunnet rundt seg", "Mest av lærebøkene de leser på skolen", "Mest av besteforeldrene og slekta si" ],
[ "Hva kaller vi de to hovedgruppene av kulturer i denne modellen?", "Jeg-kulturer og vi-kulturer", "Kan-kulturer og vil-kulturer", "By-kulturer og bygdekulturer" ],
[ "Hvorfor deler vi kulturer inn i jeg-kulturer og vi-kulturer?", "For å forstå kulturforskjeller lettere", "For å vise hvilken kultur som er best", "For å bestemme hvem som får bo i Norge" ],
[ "Hva er viktigst i en jeg-kultur?", "Enkeltmennesket", "Storfamilien", "Fellesskapet" ],
[ "Hva kjennetegner en vi-kultur?", "Gruppa er viktigere enn den enkelte", "Den enkelte er viktigere enn gruppa", "Pengene er viktigere enn familien" ],
[ "Hvilke verdier er typiske i en jeg-kultur?", "Selvstendighet og likestilling", "Lydighet og gode relasjoner", "Respekt for slekt og tradisjon" ],
[ "Hvilke verdier er typiske i en vi-kultur?", "Lydighet, respekt og gode relasjoner", "Selvstendighet, likeverd og likestilling", "Konkurranse, frihet og privatliv" ],
[ "Hva betyr det å være selvstendig?", "Å klare seg og bestemme selv", "Å gjøre det familien bestemmer", "Å bo sammen med mange andre" ],
[ "Hva kan være vanskelig for barn som vokser opp med to kulturer?", "Ulike regler hjemme og ute", "At de må gå på to skoler", "At de ikke får gå i barnehage" ],
[ "Hva betyr det å være tospråklig?", "Å kunne snakke to språk godt", "Å ha pass fra to forskjellige land", "Å ha bodd i to forskjellige land" ],
[ "Hvilket språk bør foreldre snakke med barna sine hjemme?", "Det språket foreldrene kan best", "Norsk, selv om de kan lite norsk", "Engelsk, fordi det er et verdensspråk" ],
[ "Hva kan være en styrke for barn som har to kulturer?", "De kan forstå flere måter å tenke på", "De trenger ikke å lære norsk på skolen", "De får bedre karakterer enn andre barn" ],
[ "Manar får ikke lov å bli med venner hjem etter skolen. Hva kan skje?", "Hun kan bli mer alene på skolen", "Hun får flere venner i klassen", "Hun blir bedre i norsk på skolen" ],
[ "Manars foreldre er usikre på å la henne besøke venner. Hva kan de gjøre?", "Bli kjent med foreldrene til vennen", "Be læreren velge venner for Manar", "Be skolen flytte Manar til en ny klasse" ],
[ "Familien er ny i Norge, og hverdagen er vanskelig. Hva er viktig?", "Å støtte hverandre og snakke sammen", "At hver person klarer seg alene", "Å ikke snakke om det de savner" ]
] },
{ "emne": "Barneoppdragelse", "kilde": "https://samfunnskunnskap.no/nb/familieliv/barneoppdragelse.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/1981-04-08-7/KAPITTEL_5", "https://www.imdi.no/introduksjonsprogrammet/", "https://www.bufdir.no/familie/"], "items": [
[ "Hva er riktig om barneoppdragelse i ulike kulturer?", "Den kan være forskjellig", "Den er lik over hele verden", "Den har ikke endret seg på 100 år" ],
[ "Hvem påvirker også barna, i tillegg til foreldrene?", "Voksne i barnehage, skole og fritid", "Ansatte på Nav, i banken og i butikken", "Folk som bor i andre land" ],
[ "Hva er et viktig mål med barneoppdragelse?", "At barna kan delta i samfunnet", "At barna tjener egne penger tidlig", "At barna gjør alt foreldrene sier" ],
[ "Hvordan så mange på barn i Norge for lenge siden?", "Som små voksne", "Som små konger", "Som små gjester" ],
[ "Hva måtte mange barn gjøre før, som de ikke må i dag?", "Jobbe for å skaffe familien penger", "Gå på skole fem dager i uka", "Hjelpe til med å rydde rommet sitt" ],
[ "Hva er barndommen i Norge i dag?", "En tid for lek og læring", "En tid for arbeid og plikter", "En tid for å tjene egne penger" ],
[ "Hvorfor samarbeider foreldre tett med barnehagen og skolen?", "For å vite mer om barnas hverdag", "For å slippe å følge opp barna hjemme", "For å bestemme hvor mye lærerne tjener" ],
[ "Hva synes de fleste foreldre er viktig når det gjelder barnas venner?", "Å kjenne vennene og foreldrene deres", "At barna har få venner om gangen", "At vennene går i samme klasse" ],
[ "Fatima synes barneoppdragelse er vanskelig. Hva kan hun gjøre?", "Søke råd hos noen som kan mye", "Vente og håpe at det går over", "La være å snakke med noen om det" ],
[ "Hvilket råd er godt i barneoppdragelse?", "Lytt til barnet og gi mye ros", "Gi ros først når barnet er stille", "Ikke snakk med barnet om følelser" ],
[ "Hva betyr det å være konsekvent som forelder?", "Å gjøre det man har sagt", "Å straffe barnet hver dag", "Å endre reglene hver uke" ],
[ "Hvilket år ble det forbudt å slå barn i Norge?", "I 1987", "I 1957", "I 2017" ],
[ "Ali gir sønnen et lett klaps når han er ulydig. Hva sier loven?", "Det er forbudt i Norge", "Det er lov i eget hjem", "Det er lov hvis det ikke skader" ],
[ "Hvorfor bør foreldre tenke på vanskelige situasjoner før de skjer?", "Da vet de bedre hva de skal gjøre", "Da slipper barna å ha regler hjemme", "Da trenger de ikke hjelp fra skolen" ],
[ "Hvem skal få foreldreveiledning i introduksjonsprogrammet?", "Deltakere som har barn under 18 år", "Deltakere som er over 60 år gamle", "Deltakere som ikke har egne barn" ],
[ "Hva er foreldreveiledning?", "Samtaler og kurs om å være forelder", "Kontroll av hjemmet til familien", "Undervisning for barna om skolen" ]
] },
{ "emne": "Barnevernet", "kilde": "https://samfunnskunnskap.no/nb/familieliv/barnevernet.html", "tillegg": ["https://www.bufdir.no/barnevern/", "https://www.bufdir.no/barnevern/omsorgsovertakelse/", "https://lovdata.no/dokument/NL/lov/2021-06-18-97", "https://lovdata.no/dokument/NL/lov/2021-06-11-79"], "items": [
[ "Hvor finnes det en barnevernstjeneste?", "I alle kommuner i Norge", "I hvert fylke i Norge", "I de største byene i Norge" ],
[ "Når trådte Norges første lov om barnevern i kraft?", "I år 1900", "I år 1950", "I år 1814" ],
[ "Hva er barnevernets viktigste oppgave?", "Å beskytte barn, helst sammen med familien", "Å finne nye familier til så mange barn som mulig", "Å lære barn å lese og skrive før skolen" ],
[ "Hvilke hjelpetiltak kan barnevernet gi?", "Veiledning, avlastning og støttekontakt", "Lån, bolig og fast jobb til foreldrene", "Skattefradrag, trygd og gratis bil" ],
[ "Ahmed og Lina er slitne og trenger hjelp med barna. Hva kan de gjøre?", "Be barnevernet om hjelp selv", "Vente til skolen melder fra", "Vente til barna blir eldre" ],
[ "Hva er et fosterhjem?", "Et hjem der et barn bor når det ikke kan bo hjemme", "Et hjem der eldre bor når de trenger mye hjelp", "Et hjem der nye innvandrere bor det første året" ],
[ "Hva betyr det at de ansatte i barnevernet har taushetsplikt?", "De kan ikke fortelle andre om saken", "De må fortelle naboene om saken", "De kan ikke snakke med barnet selv" ],
[ "Hva betyr avlastning fra barnevernet?", "Barnet er hos andre noen dager, så foreldrene får hvile", "Barnet får gratis plass på SFO gjennom hele skoleåret", "Familien får hjelp til å vaske og rydde hjemme" ],
[ "Hva er en bekymringsmelding?", "En beskjed til barnevernet om et barn", "En klage til skolen om en lærer", "Et brev fra Nav om penger til familien" ],
[ "Hvem bestemmer om et barn må flytte fra foreldrene sine?", "Barneverns- og helsenemnda", "Barnevernstjenesten alene", "Skolen og helsestasjonen" ],
[ "Hvilke barn har rett til å si sin mening til barnevernet?", "Alle barn som kan danne seg en mening", "Bare barn som har fylt 15 år", "Bare barn som er gamle nok til å gå på skole" ],
[ "En nabo er bekymret for et barn. Kan hun melde fra uten navn?", "Ja, en privatperson kan være anonym", "Nei, hun må først kontakte politiet", "Nei, hun må først snakke med familien" ]
] },
{ "emne": "Barn og unges rettigheter", "kilde": "https://samfunnskunnskap.no/nb/familieliv/barn-og-unges-rettigheter.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/1981-04-08-7/KAPITTEL_5", "https://www.regjeringen.no/no/tema/familie-og-barn/innsikt/fns-barnekonvensjon/id2593839/", "https://www.barneombudet.no/"], "items": [
[ "Hvem gjelder barneloven for?", "Barn og unge under 18 år", "Barn og unge under 16 år", "Barn og unge under 15 år" ],
[ "Hva skjer når et barn blir født i Norge?", "Det sendes melding til Folkeregisteret", "Foreldrene må melde fødselen til politiet", "Barnet får et norsk pass med en gang" ],
[ "Hvor lenge må foreldre sørge for mat og klær til barnet?", "Til barnet har fylt 18 år", "Til barnet har fylt 15 år", "Til barnet har fylt 16 år" ],
[ "Hva må foreldre passe på når det gjelder skole?", "At barnet går på grunnskolen", "At barnet får de beste karakterene", "At barnet velger samme yrke som dem" ],
[ "Foreldrene til Omar bor hver for seg. Hva har Omar rett til?", "Samvær med begge foreldrene", "Samvær med den som tjener mest", "Samvær med den eldste forelderen" ],
[ "Når skal et barn senest få si sin mening om viktige avgjørelser?", "Når barnet er sju år", "Når barnet er 15 år", "Når barnet er 18 år" ],
[ "Hva sier barneloven når barnet har fylt 12 år?", "Barnets mening skal veie tungt", "Barnet bestemmer alt selv", "Barnet kan flytte hjemmefra" ],
[ "Sofie er 15 år. Hva kan hun bestemme selv?", "Hvilken utdanning hun vil ta", "Om hun vil gifte seg nå", "Om hun vil kjøpe bil på lån" ],
[ "Ali er 15 år og vil melde seg inn i en forening. Hvem bestemmer?", "Ali bestemmer selv", "Faren bestemmer", "Skolen bestemmer" ],
[ "Hva er FNs barnekonvensjon?", "En avtale om barns rettigheter", "En lov om barnehager i Norge", "En avtale om handel mellom land" ],
[ "Hva gjør Barneombudet?", "Passer på at barns rettigheter blir fulgt", "Bestemmer hvilken skole barna skal gå på", "Betaler ut penger til familier med barn" ],
[ "Hva skal være viktigst når voksne tar avgjørelser om barn?", "Det som er best for barnet", "Det som er billigst for kommunen", "Det som foreldrene ønsker mest" ]
] }
] };
