module.exports = { "tema": "Retten til et fritt og selvstendig liv", "emner": [
{ "emne": "Vold i nære relasjoner", "kilde": "https://samfunnskunnskap.no/nb/retten-til-et-fritt-og-selvstendig-liv/vold-i-naere-relasjoner.html", "tillegg": ["https://lovdata.no/lov/2005-05-20-28/§282", "https://lovdata.no/lov/2005-05-20-28/§196", "https://lovdata.no/dokument/NL/lov/2009-06-19-44", "https://www.politiet.no/rad/vold-i-nare-relasjoner/", "https://dinutvei.no/hjelpetilbud/vo-linjen-116-006/", "https://www.helsenorge.no/psykisk-helse/vold-og-overgrep/", "https://www.116111.no/", "https://www.udi.no/skal-soke/oppholdstillatelse-for-de-som-har-blitt-mishandlet/", "https://atv-stiftelsen.no/"], "items": [
[ "Hva betyr «vold i nære relasjoner»?", "Vold mellom familiemedlemmer eller partnere", "Vold mellom fremmede mennesker ute på gaten", "Vold mellom spillere under en kamp i idrett" ],
[ "Hva er psykisk vold?", "Trusler, ydmykelse og sterk kontroll", "Slag og spark som gir blåmerker", "Å ødelegge ting som en annen eier" ],
[ "Hva er materiell vold?", "Å knuse eller ødelegge ting i hjemmet", "Å true en person med å skade henne", "Å tvinge noen til sex mot sin vilje" ],
[ "Hva er seksuell vold?", "Å tvinge noen til seksuelle handlinger", "Å slå noen i ansiktet med flat hånd", "Å kaste og knuse telefonen til noen" ],
[ "Hva sier norsk lov om vold i familien?", "Vold er forbudt, også i familien", "Litt vold er lov når det skjer hjemme", "Familien bestemmer selv hva som er lov" ],
[ "Hvorfor er vold i nære relasjoner ikke en privatsak?", "Samfunnet har ansvar for å beskytte alle", "Familien må betale en bot til staten", "Naboene bestemmer hva som skjer hjemme" ],
[ "En mann sier at volden skyldes kulturen hans. Hva gjelder i Norge?", "Vold er straffbart uansett årsak", "Vold er lov hvis det er vanlig i kulturen", "Vold er lov hvis kona har gjort noe galt" ],
[ "Hvem gjelder forbudet mot vold i familien for?", "Alle som bor eller oppholder seg i Norge", "Personer som er norske statsborgere", "Familier som har barn under 18 år" ],
[ "Et barn ser at moren blir slått hjemme. Kan dette skade barnet?", "Ja, det kan skade barnet å se vold", "Nei, barnet blir ikke slått selv", "Nei, små barn forstår ikke det de ser" ],
[ "Hvilken gruppe kan være ekstra utsatt for vold i nære relasjoner?", "LHBTIQ+-personer, som lesbiske og homofile", "Personer som har høy utdanning og god lønn", "Personer som bor alene i en stor by i Norge" ],
[ "Hvordan ser det norske samfunnet på tvangsekteskap og kjønnslemlestelse?", "Former for vold som ikke aksepteres", "Private saker som familien bestemmer", "Gamle tradisjoner som er lov i Norge" ],
[ "Hva kan straffen være for mishandling i nære relasjoner?", "Fengsel i inntil 6 år", "Bot på inntil 5 000 kroner", "Fengsel i inntil 3 måneder" ],
[ "Hva kan straffen være for grov mishandling i nære relasjoner?", "Fengsel i inntil 15 år", "Fengsel i inntil 2 år", "Bot og samfunnsstraff" ],
[ "Hvem er beskyttet av loven om mishandling i nære relasjoner?", "Blant annet ektefelle, samboer og barn", "Blant annet kolleger, naboer og gode venner", "Blant annet kunder, turister og fremmede" ],
[ "Hva betyr «avvergeplikt»?", "Plikt til å prøve å stoppe alvorlig vold", "Plikt til å holde vold i familien hemmelig", "Plikt til å flytte når det er vold hjemme" ],
[ "Hvem har plikt til å prøve å avverge mishandling i nære relasjoner?", "Alle, også de som har taushetsplikt", "Politiet og ansatte i barnevernet", "Familiemedlemmer som bor sammen" ],
[ "Du hører at naboen blir slått og skriker om hjelp. Hva bør du gjøre?", "Ringe politiet på 112", "Vente og spørre naboen neste dag", "Skru opp musikken og gå til sengs" ],
[ "Hva betyr det å «anmelde» vold?", "Å melde fra til politiet om et lovbrudd", "Å skrive om volden på sosiale medier", "Å snakke med familien om det som skjedde" ],
[ "En lærer tror at en elev blir slått hjemme. Hva må læreren gjøre?", "Melde fra til barnevernet", "Snakke med foreldrene og la det være", "Vente til eleven blir 18 år" ],
[ "Hva er et krisesenter?", "Et trygt sted for dem som er utsatt for vold", "Et sykehus for dem som er skadet i trafikken", "Et kontor der man søker om kommunal bolig" ],
[ "Hvem kan få hjelp på et krisesenter?", "Kvinner, menn og barn som er utsatt for vold", "Turister som trenger et billig sted å bo", "Personer som har mistet jobben og boligen" ],
[ "Hva koster det å bo på et krisesenter?", "Det er gratis for alle som trenger det", "Det koster omtrent 500 kroner per natt", "Man betaler en egenandel hver uke" ],
[ "Hvordan kan man komme til et krisesenter?", "Man kan ta kontakt selv, uten henvisning", "Man må først få en henvisning fra Nav", "Man må først anmelde volden til politiet" ],
[ "Hvem har ansvar for at det finnes et krisesentertilbud?", "Kommunen", "Arbeidsgiveren", "Kirken" ],
[ "Hva gjør krisesenteret med opplysninger om hvem som bor der?", "De ansatte har taushetsplikt", "De sender navnene til familien", "De legger ut navnene på nettet" ],
[ "Hva er Vold- og overgrepslinjen, 116 006?", "En gratis og anonym hjelpelinje", "Et nummer for å bestille legetime", "Et nummer for å melde fra om innbrudd" ],
[ "Hvor kan barn og unge ringe hvis de blir utsatt for vold?", "Alarmtelefonen for barn og unge, 116 111", "Legevakten, 116 117, for å bestille time", "Skatteetaten, 800 80 000, for å få råd" ],
[ "Hvor kan eldre over 62 år ringe hvis de utsettes for vold?", "Vern for eldre, 800 30 196", "Nav kontaktsenter, 55 55 33 33", "Opplysningen, 1881" ],
[ "Hva er dinutvei.no?", "En nettside om vold og hjelpetilbud", "En nettside for å søke jobb i kommunen", "En nettside for å kjøpe bussbilletter" ],
[ "Hva er et kontaktforbud?", "Forbud mot å oppsøke eller kontakte noen", "Forbud mot å ringe politiet om natten", "Forbud mot å bruke mobil på skolen" ],
[ "Ana har opphold fordi hun er gift. Mannen mishandler henne. Hva kan hun søke om?", "Egen oppholdstillatelse hos UDI", "Norsk statsborgerskap med en gang", "Penger fra mannen som en straff" ],
[ "Er det voldtekt å tvinge ektefellen sin til sex?", "Ja, det er straffbart også i ekteskap", "Nei, ektefeller har rett til sex", "Nei, det er en sak mellom ektefellene" ],
] },
{ "emne": "Tvangsekteskap", "kilde": "https://samfunnskunnskap.no/nb/retten-til-et-fritt-og-selvstendig-liv/tvangsekteskap.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/1991-07-04-47", "https://lovdata.no/lov/2005-05-20-28/§253", "https://lovdata.no/lov/2005-05-20-28/§5", "https://rodekorstelefonen.no/", "https://www.bufdir.no/vold/aresrelatert/kompetanseteamet/"], "items": [
[ "Kan en person under 18 år få særskilt lov til å gifte seg i Norge?", "Nei, det finnes ingen unntak", "Ja, hvis foreldrene sier ja", "Ja, hvis statsforvalteren sier ja" ],
[ "Hva betyr «tvangsekteskap»?", "At noen blir tvunget til å gifte seg", "At to personer gifter seg uten en stor fest", "At to personer gifter seg uten å ha bodd sammen" ],
[ "Hva er et arrangert ekteskap?", "Familien foreslår en ektefelle, og paret sier fritt ja", "Familien truer paret til å gifte seg med hverandre", "Paret gifter seg i hemmelighet uten at familien vet om det" ],
[ "Hva kan straffen være for å tvinge noen til å gifte seg?", "Fengsel i inntil 6 år", "Bot på inntil 10 000 kroner", "Fengsel i inntil 6 måneder" ],
[ "En onkel hjelper til med å tvinge en jente til ekteskap. Kan han straffes?", "Ja, den som hjelper til kan straffes", "Nei, han er ikke foreldre til jenta", "Nei, det er en sak for familien selv" ],
[ "Hvem må si ja for at et ekteskap skal være gyldig?", "De to som skal gifte seg", "Foreldrene til de to", "Den eldste i familien" ],
[ "Hva må man blant annet ha for å gifte seg i Norge?", "Lovlig opphold i Norge", "Norsk statsborgerskap", "Fast jobb i Norge" ],
[ "Kan man gifte seg på nytt hvis man er gift fra før?", "Nei, man må først skille seg", "Ja, hvis den første ektefellen er enig", "Ja, hvis det første bryllupet var i utlandet" ],
[ "Hva kan en domstol gjøre når noen er tvunget til å gifte seg?", "Kjenne ekteskapet ugyldig", "Gi paret råd om å få barn", "Gi familien lov til ekteskapet" ],
[ "Hva er den lengste fristen for å få et tvangsekteskap kjent ugyldig?", "Fem år etter at man giftet seg", "Ti år etter at man giftet seg", "Tjue år etter at man giftet seg" ],
[ "Er det lov å tvinge noen inn i et uoffisielt ekteskap uten papirer?", "Nei, det er også straffbart", "Ja, hvis familien er enig i det", "Ja, fordi staten ikke har registrert det" ],
[ "Er det straffbart å lure noen til utlandet for å tvangsgifte dem?", "Ja, det straffes på samme måte", "Nei, utlandet har sine egne lover", "Nei, personen reiste jo frivillig" ],
[ "En 15-åring blir gift i utlandet. Blir ekteskapet godkjent i Norge?", "Nei, som hovedregel ikke", "Ja, hvis det var lovlig i det landet", "Ja, hvis foreldrene skrev under på det" ],
[ "Hva sier norsk lov om søskenbarn som vil gifte seg med hverandre?", "Det er som hovedregel forbudt", "Det er lov fra de er 16 år", "Det er lov hvis familien er enig" ],
[ "Mina (18) vil studere, men foreldrene vil at hun gifter seg. Hvem bestemmer?", "Mina bestemmer selv om og når hun gifter seg", "Foreldrene bestemmer fordi hun bor hjemme", "Foreldrene bestemmer fordi de betaler for henne" ],
[ "Hvor kan en ung person som er redd for tvangsekteskap, få råd anonymt?", "Hos Røde Kors-telefonen", "Hos Statens vegvesen", "Hos Skatteetaten" ],
[ "Omar er redd for å bli giftet bort på ferie i utlandet. Hva er lurt?", "Å snakke med noen han stoler på før reisen", "Å reise uten å fortelle noen om frykten", "Å vente og se hva som skjer på ferien" ],
[ "Hvordan kan en norsk ambassade hjelpe en som er tvangsgiftet i utlandet?", "Gi råd og hjelp til å komme trygt hjem", "Godkjenne ekteskapet slik at det gjelder", "Sende personen tilbake til familien" ],
] },
{ "emne": "Negativ sosial kontroll", "kilde": "https://samfunnskunnskap.no/nb/retten-til-et-fritt-og-selvstendig-liv/negativ-sosial-kontroll.html", "tillegg": ["https://www.bufdir.no/vold/aresrelatert/kompetanseteamet/", "https://www.bufdir.no/vold/aresrelatert/botilbud/", "https://www.imdi.no/negativ-sosial-kontroll/mangfoldsradgivere/", "https://www.regjeringen.no/no/aktuelt/namnebyte-fra-minoritetsradgivar-til-mangfaldsradgivar/id3012528/", "https://rodekorstelefonen.no/", "https://dinutvei.no/"], "items": [
[ "Hva er sosial kontroll?", "Rammer for oppførsel som familie og samfunn setter", "En støtteordning som man kan søke om hos Nav-kontoret", "En kontroll av pass og ID-kort ved grensen" ],
[ "Når kan sosial kontroll bli negativ?", "Når reglene er så strenge at de tar bort friheten", "Når foreldrene vil at barna skal gjøre lekser", "Når skolen har regler for når timene starter" ],
[ "Hvordan kan negativ sosial kontroll påvirke integreringen til barn og unge?", "Den kan hindre at de blir en del av samfunnet", "Den gjør det mye lettere å få nye venner i Norge", "Den har ingen betydning for barn og unge" ],
[ "Hvilket eksempel kan være negativ sosial kontroll?", "Familien bestemmer hvem du får være venn med", "Familien spør hvordan det gikk på skolen", "Familien ber deg rydde rommet ditt" ],
[ "Merhet (14) må slutte med håndball fordi faren ikke liker klærne. Hva er dette?", "Det kan være negativ sosial kontroll", "Det er et krav fra idrettslaget", "Det er en regel som skolen har laget" ],
[ "Moren til Merhet sjekker telefonen hennes hver kveld. Hva kan dette være?", "Negativ sosial kontroll", "Vanlig hjelp med lekser", "Et krav fra skolen" ],
[ "Hvem kan bli utsatt for negativ sosial kontroll?", "Jenter, gutter, kvinner og menn", "Jenter, men ikke gutter eller voksne", "Voksne, men ikke barn og unge" ],
[ "Hvilken rett kan negativ sosial kontroll ta fra en person?", "Retten til å leve et selvstendig liv", "Retten til å få gratis skolegang", "Retten til å stemme ved valg" ],
[ "Er det lov å true et barn for å bestemme hvem barnet møter?", "Nei, trusler og vold er forbudt", "Ja, foreldre bestemmer over barna", "Ja, hvis barnet er under 18 år" ],
[ "Hva betyr «æresrelatert vold»?", "Vold for å beskytte familiens ære", "Vold mellom to lag under en fotballkamp", "Vold som skjer ved et uhell i trafikken" ],
[ "Hva gjør en mangfoldsrådgiver?", "Hjelper unge som opplever kontroll og press", "Underviser elever i flere ulike språk", "Ansetter folk med ulik bakgrunn i kommunen" ],
[ "Hvor kan en elev møte en mangfoldsrådgiver?", "På noen ungdoms- og videregående skoler", "På noen sykehus og legekontorer", "På noen politistasjoner og tingretter" ],
[ "Hva gjør Kompetanseteamet mot negativ sosial kontroll og æresrelatert vold?", "Gir råd og veiledning i slike saker", "Gir straff til dem som kontrollerer andre", "Gir penger til familier med lav inntekt" ],
[ "Hva er Røde Kors-telefonen om negativ sosial kontroll?", "En hjelpetelefon der man kan være anonym", "En telefon for å bestille time hos legen", "En telefon for å melde fra om ulykker" ],
[ "Hva betyr det å leve et «dobbeltliv»?", "Å skjule deler av livet for familien", "Å ha to ulike jobber på samme tid", "Å ha to hjem i to ulike land samtidig" ],
[ "Hva betyr det å bli «etterlatt i utlandet»?", "Å bli holdt i et annet land mot sin vilje", "Å flytte frivillig til et annet land for å jobbe", "Å reise på ferie til utlandet med familien" ],
[ "Hvem kan få plass i det nasjonale bo- og støttetilbudet?", "Personer over 18 år som trenger beskyttelse", "Studenter som ikke finner en bolig", "Pensjonister som vil bo nær familien" ],
[ "Foreldre synes det er vanskelig å oppdra barn i et nytt land. Hvem kan hjelpe?", "Familievernkontoret", "Skattekontoret", "Passkontoret" ],
] },
{ "emne": "Kjønnslemlestelse", "kilde": "https://samfunnskunnskap.no/nb/retten-til-et-fritt-og-selvstendig-liv/kjonnslemlestelse.html", "tillegg": ["https://lovdata.no/lov/2005-05-20-28/§284", "https://lovdata.no/lov/2005-05-20-28/§5", "https://lovdata.no/lov/2005-05-20-28/§196", "https://www.helsenorge.no/sykdom/underliv/kjonnslemlestelse/", "https://kjonnslemlestelse.nkvts.no/innhold/hvordan-gjennomfore-samtaler-om-kjonnslemlestelse/tilbud-om-samtale-og-frivillig-underlivsundersokelse/"], "items": [
[ "Hva er kjønnslemlestelse?", "Inngrep som skader de ytre kjønnsdelene uten medisinsk grunn", "Inngrep som legen gjør når det er nødvendig for helsen til jenta", "Undersøkelse som legen gjør når en kvinne er gravid" ],
[ "Når regnes et inngrep som kjønnslemlestelse?", "Uansett hvor lite som er skadet eller fjernet", "Først når mye av kjønnsdelene er fjernet", "Først når jenta blir syk etter inngrepet" ],
[ "En kvinne på 20 år sier ja til kjønnslemlestelse. Er det lov?", "Nei, det er forbudt selv om hun sier ja", "Ja, voksne kan bestemme dette selv", "Ja, hvis en lege gjør inngrepet" ],
[ "En familie tar datteren til et annet land for å omskjære henne. Hva gjelder?", "Det er straffbart, også når det skjer i utlandet", "Det er lov hvis det er lovlig i det andre landet", "Det er lov hvis det skjer mens familien har ferie" ],
[ "Hva kan straffen være for kjønnslemlestelse som ikke regnes som grov?", "Fengsel i inntil 6 år", "Bot på inntil 20 000 kroner", "Fengsel i inntil 6 måneder" ],
[ "Er det lov å sy igjen eller gjenskape en tidligere omskjæring?", "Nei, det er også forbudt", "Ja, hvis kvinnen ønsker det", "Ja, etter en fødsel på sykehus" ],
[ "Foreldre bestiller et inngrep for datteren sin. Kan foreldrene straffes?", "Ja, de kan straffes for å medvirke", "Nei, de gjorde ikke inngrepet selv", "Nei, foreldre har rett til å bestemme" ],
[ "Du vet at en jente skal omskjæres neste uke. Hva må du gjøre?", "Prøve å stoppe det, for eksempel ved å varsle politiet", "Ingenting, fordi det er en privat sak for familien hennes", "Vente til etterpå og så snakke med jenta om det" ],
[ "Hvorfor bryter kjønnslemlestelse med viktige verdier i Norge?", "Alle skal få bestemme over sin egen kropp", "Alle skal betale skatt av inntekten sin", "Alle skal kunne snakke norsk på jobben" ],
[ "Hvilke følger kan kjønnslemlestelse få for jenta?", "Smerter og helseplager resten av livet", "Bedre helse og færre infeksjoner", "Lettere fødsler og mindre smerter" ],
[ "Hva tilbyr helsestasjonen for å forebygge kjønnslemlestelse?", "Samtale og frivillig underlivsundersøkelse", "Gratis reise til familien i utlandet", "Kurs i matlaging for hele familien" ],
[ "Hvor kan en kvinne med plager etter kjønnslemlestelse få hjelp?", "Hos fastlegen eller helsestasjonen", "Hos Skatteetaten eller på Nav-kontoret", "Hos Tollvesenet eller Posten" ],
] },
] };
