module.exports = { "tema": "Helse", "emner": [
{ "emne": "Helsetjenester", "kilde": "https://samfunnskunnskap.no/nb/helse/helsetjenester.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/2021-06-11-79", "https://www.helsedirektoratet.no/veiledere/tolketjenester-i-helse-og-omsorgstjenesten"], "items": [
[ "Hva betyr det at Norge har et offentlig helsevesen?", "Staten sørger for behandling uansett hvor mye du tjener", "Private firmaer eier sykehusene og legekontorene i landet", "Pasientene betaler hele prisen for behandlingen selv" ],
[ "Hvem skal du vanligvis kontakte først når du blir syk?", "Fastlegen", "Sykehuset", "Apoteket" ],
[ "Hvor ofte kan du bytte fastlege?", "Inntil to ganger i året", "Én gang hvert femte år", "Når kommunen gir tillatelse" ],
[ "Hva trenger du vanligvis for å få time hos en hudlege?", "En henvisning fra fastlegen", "En attest fra arbeidsgiveren", "En resept fra apoteket" ],
[ "Hvem av disse er en legespesialist?", "En øre-nese-hals-lege", "En legesekretær", "En helsesykepleier" ],
[ "Hva koster det for pasienten å ligge på et offentlig sykehus?", "Det er gratis for pasienten", "Pasienten betaler for maten", "Det koster litt for hvert døgn" ],
[ "Hva betyr poliklinisk behandling?", "Du får behandling på sykehuset og reiser hjem etterpå", "Du blir lagt inn og bor på sykehuset i flere uker", "Du får behandling hjemme av en sykepleier fra kommunen" ],
[ "Fatima får høy feber en lørdag kveld. Hvor kan hun ringe?", "Legevakten på 116 117", "Hjelpetelefonen på 116 123", "Politiet på telefon 112" ],
[ "Omar ser at naboen faller om og ikke puster. Hva gjør han?", "Ringer 113 med en gang", "Ringer legevakten på 116 117", "Bestiller time hos fastlegen" ],
[ "Hvor kan du kjøpe milde smertestillende tabletter?", "På apoteket og i matbutikken", "Hos fastlegen og på legevakten", "På sykehuset og helsestasjonen" ],
[ "Hva er en resept?", "Legens beskjed om medisin du skal få", "En regning for medisin du har kjøpt", "En avtale om time hos legen" ],
[ "Hvem kan få medisiner på blå resept?", "Personer med alvorlig og langvarig sykdom", "Personer som tjener lite eller er uten jobb", "Personer som har bodd kort tid i Norge" ],
[ "Hva betyr taushetsplikt hos legen?", "Legen kan ikke fortelle andre om deg uten lov", "Legen må fortelle familien din alt det du sier", "Legen må gi Nav beskjed om sykdommen din" ],
[ "Hva har du rett til å lese hos legen?", "Det legen skriver om deg i journalen", "Det legen skriver om andre pasienter", "Arbeidsavtalen og lønnen til legen" ],
[ "Leyla forstår lite norsk. Hva har hun rett til hos legen?", "En tolk som er gratis for henne", "En tolk som hun må betale selv", "En lege fra sitt eget hjemland" ],
[ "Hvem bør tolke når en pasient trenger tolk hos legen?", "En kvalifisert tolk", "Pasientens eldste barn", "En venn av pasienten" ]
] },
{ "emne": "Helse og livsstil", "kilde": "https://samfunnskunnskap.no/nb/helse/helse-og-livsstil.html", "tillegg": ["https://www.helsenorge.no/kosthold-og-ernaring/"], "items": [
[ "Hvordan har folkehelsen i Norge endret seg de siste hundre årene?", "Den har blitt mye bedre", "Den har blitt mye dårligere", "Den er omtrent som før" ],
[ "Hva døde mange nordmenn av for omtrent hundre år siden?", "Tuberkulose og underernæring", "Diabetes og for mye vekt", "Allergi og problemer med ryggen" ],
[ "Hva er de vanligste dødsårsakene i Norge i dag?", "Kreft og hjerte- og karsykdommer", "Tuberkulose og andre infeksjoner", "Trafikkulykker og drukning" ],
[ "Hvilke helseproblemer blir stadig vanligere i Norge?", "Diabetes og stor overvekt", "Tuberkulose og kolera", "Malaria og underernæring" ],
[ "Hva øker risikoen for kreft og hjertesykdom?", "Å røyke tobakk", "Å gå lange turer", "Å spise mye fisk" ],
[ "Hva gir oss størst sjanse for å holde oss friske lenge?", "Sunn mat og fysisk aktivitet", "Mye hvile og lite bevegelse", "Vitaminpiller og lite mat" ],
[ "Hvem har ansvar for helsen vår, slik mange tenker i dag?", "Hver av oss, med råd fra helsevesenet", "Helsevesenet alene, ikke pasienten selv", "Arbeidsgiveren til hver enkelt" ],
[ "Hva er vanlig når du går til legen i Norge?", "Lege og pasient snakker sammen om behandlingen", "Du får medisin ved hvert besøk hos legen", "Legen bestemmer alt uten å spørre pasienten" ],
[ "Aygül er forkjølet. Hva sier legen ofte da?", "At det går over av seg selv", "At hun må legges inn på sykehus", "At hun må ta sterk medisin" ],
[ "Hvilket problem har flere innvandrere enn nordmenn, ifølge helsearbeidere?", "Mangel på vitamin D og jern", "For mye vitamin D og jern", "Mangel på salt og sukker" ],
[ "Hvorfor trenger mange ekstra vitamin D i Norge?", "Det er lite sol store deler av året", "Maten i Norge har nesten ikke vitaminer", "Vannet i Norge er for kaldt og rent" ],
[ "Hva er det som gjør at de fleste mennesker trives?", "Å ha god kontakt med andre mennesker", "Å ha mye penger og en stor bolig", "Å bo alene og ha mye tid for seg selv" ],
[ "Hvilken helse er viktigst, den fysiske eller den psykiske?", "Begge er like viktige", "Den fysiske er viktigst", "Den psykiske er viktigst" ],
[ "Hva kan stress og tristhet føre til?", "Dårlige matvaner og dårligere helse", "Bedre søvn og mer energi i hverdagen", "Sterkere tenner og bedre hukommelse" ]
] },
{ "emne": "Psykisk helse", "kilde": "https://samfunnskunnskap.no/nb/helse/psykisk-helse.html", "tillegg": ["https://mentalhelse.no/fa-hjelp/hjelpetelefonen/"], "items": [
[ "Hvem kan få psykiske problemer?", "Alle kan få det, i alle aldre", "Bare personer med svak vilje", "Bare personer som bor alene" ],
[ "Hva kan føre til psykiske lidelser?", "Vanskelige hendelser, som krig", "Å trene ofte og spise sunt", "Å ha mange gode venner" ],
[ "John har vondt i magen, men prøvene er fine. Hva kan årsaken være?", "Han kan ha det vanskelig psykisk", "Han spiser for mye frukt og grønt", "Han har for lite vann i kroppen" ],
[ "Hvem kan henvise deg til psykolog?", "Fastlegen", "Apoteket", "Nav-kontoret" ],
[ "Hva gjør en psykolog?", "Hjelper folk med tanker og følelser", "Opererer pasienter på sykehus", "Gir pasienter vaksiner og sprøyter" ],
[ "Hva gjelder for psykologen når du forteller om problemene dine?", "Psykologen har taushetsplikt", "Psykologen må melde fra til familien", "Psykologen må fortelle det til Nav" ],
[ "Hva mener de fleste i Norge om psykisk sykdom i dag?", "At den skal behandles som fysisk sykdom", "At det er noe man helst ikke bør snakke om", "At de syke må klare seg uten hjelp" ],
[ "Er det mulig å bli frisk av psykiske lidelser?", "Ja, mange blir friske med god hjelp", "Nei, man må leve med det resten av livet", "Nei, sykdommen blir verre med årene" ],
[ "Hvor kan du ringe når du trenger noen å snakke med om natten?", "Mental Helse på 116 123", "Brannvesenet på 110", "Opplysningen på 1881" ],
[ "En venn sier at han vil skade seg selv nå. Hva gjør du?", "Ringer nødnummeret 113", "Sender e-post til fastlegen", "Venter og ser om det går over" ],
[ "Hva kan du selv gjøre for god psykisk helse?", "Være sammen med andre og sove godt", "Være mest mulig alene hjemme", "Jobbe mye og sove lite" ],
[ "Hva betyr det at psykiske problemer er «tabu» i noen kulturer?", "At man ikke snakker åpent om dem", "At man går til legen med en gang", "At det er lett å få medisin for dem" ]
] },
{ "emne": "Familieplanlegging, svangerskap og oppfølging av barn", "kilde": "https://samfunnskunnskap.no/nb/helse/familieplanlegging-svangerskap-og-oppfolging-av-barn.html", "tillegg": ["https://www.helsenorge.no/sex-og-samliv/abort/", "https://lovdata.no/dokument/NL/lov/2024-12-20-96"], "items": [
[ "Hva betyr familieplanlegging?", "At paret selv bestemmer når og hvor mange barn", "At staten bestemmer hvor mange barn man får", "At familien bestemmer hvem man skal gifte seg med" ],
[ "Hvilket prevensjonsmiddel beskytter mot seksuelt overførbare sykdommer?", "Kondom", "P-piller", "Spiral" ],
[ "Hva er en p-stav?", "En liten stav med hormon under huden", "En liten pille som kvinnen tar hver dag", "En krem som dreper sædceller" ],
[ "Hva koster svangerskapskontroll for gravide i Norge?", "Den er gratis", "Rundt 200 kroner", "Halv pris med frikort" ],
[ "Hvem gjør svangerskapskontrollene?", "Helsestasjonen eller fastlegen", "Apoteket eller legevakten", "Nav-kontoret eller kommunen" ],
[ "Må gravide gå til svangerskapskontroll?", "Nei, men det anbefales", "Ja, det er påbudt ved lov", "Ja, ellers mister hun foreldrepenger" ],
[ "Hvor lenge i svangerskapet kan kvinnen få abort når hun ber om det?", "De første 18 ukene", "De første 12 ukene", "De første 22 ukene" ],
[ "Hvem bestemmer om en kvinne skal ta abort i de første ukene?", "Den gravide kvinnen selv", "Kvinnen og mannen sammen", "Legen på sykehuset" ],
[ "Hvor går foreldre med babyer og småbarn til helsekontroll?", "Til helsestasjonen", "Til legevakten", "Til tannlegen" ],
[ "Lille Sara på to år har feber. Hvem skal undersøke henne?", "Fastlegen", "Helsestasjonen", "Skolehelsetjenesten" ],
[ "Hva gjelder for vaksinene i barnevaksinasjonsprogrammet?", "De er gratis og frivillige", "De koster penger og er påbudt", "De er gratis, men påbudt ved lov" ],
[ "Hvem gir helsekontroller og vaksiner til elever på skolen?", "Skolehelsetjenesten", "Fastlegen til barnet", "Legevakten i kommunen" ]
] },
{ "emne": "Tannhelse", "kilde": "https://samfunnskunnskap.no/nb/helse/tannhelse.html", "tillegg": ["https://www.helsenorge.no/betaling-for-helsetjenester/hvem-betaler-tannlegeregningen-din/", "https://www.helsedirektoratet.no/lov-og-forskrift/tannhelsetjenesteloven/tannbehandling-til-unge-voksne-mellom-19-og-28-ar"], "items": [
[ "Hvem får gratis behandling i den offentlige tannhelsetjenesten?", "Barn til og med året de fyller 18", "Voksne som har en fast jobb i Norge", "Pensjonister som er over 67 år gamle" ],
[ "Hvor mye betaler unge voksne fra 19 til 28 år på offentlig tannklinikk?", "25 prosent av prisen", "75 prosent av prisen", "50 prosent av prisen" ],
[ "Hvor ofte er det vanlig at voksne går til tannkontroll?", "Én gang i året", "Én gang i måneden", "Én gang hvert tiende år" ],
[ "Hvor ofte bør man pusse tennene?", "To ganger om dagen", "Én gang i uka", "Fem ganger om dagen" ],
[ "Hva er skadelig for tennene?", "Sukker i mat og drikke", "Vann som tørstedrikk", "Ost og rå grønnsaker" ],
[ "Hvem har ansvaret for tannhelsen til barna?", "Foreldrene", "Skolen", "Tannlegen" ],
[ "Hvorfor er det viktig å stelle melketennene godt?", "Dårlige melketenner kan skade de nye tennene", "Melketennene skal sitte i munnen resten av livet", "Tannlegen vil ellers ikke behandle barnet" ],
[ "Hva må foreldre betale en egenandel for når barnet går til tannlegen?", "Tannregulering", "Tannkontroll", "Fylling av hull" ],
[ "Hvem kaller inn barn til tannkontroll?", "Den offentlige tannklinikken", "Helsesykepleieren på skolen", "Fastlegen til barnet" ],
[ "Hva er den beste tørstedrikken for tennene?", "Vann", "Brus", "Saft" ]
] },
{ "emne": "Å flytte til et nytt land", "kilde": "https://samfunnskunnskap.no/nb/helse/a-flytte-til-et-nytt-land.html", "items": [
[ "Hvor mange faser har den psykiske migrasjonsprosessen?", "Tre faser", "To faser", "Fem faser" ],
[ "Hva er vanlig å føle i den første tiden etter flyttingen?", "Glede og optimisme", "Sorg og savn", "Sinne og frykt" ],
[ "Hva skjer ofte i fase 2 av migrasjonsprosessen?", "Livet føles vanskelig, og savnet blir stort", "Man føler seg glad og har det travelt", "Man har funnet sin plass i det nye samfunnet" ],
[ "Hva skjer ofte i fase 3 av migrasjonsprosessen?", "Livet føles lettere, og man forstår mer", "Man savner hjemlandet mer enn før", "Man tenker mest på nye muligheter" ],
[ "Hvor lenge varer hver fase i migrasjonsprosessen?", "Det er ulikt fra person til person", "Hver fase varer i nøyaktig tolv måneder", "Hver fase varer i omtrent én uke" ],
[ "Amaniel er sliten og savner familien etter noen uker. Hvilken fase er han i?", "Fase 2", "Fase 1", "Fase 3" ],
[ "Hva hjelper en innvandrer å finne sin plass i det nye samfunnet?", "Å kombinere nye og gamle verdier", "Å glemme kulturen fra hjemlandet", "Å leve akkurat som i hjemlandet" ],
[ "Hva er vanlig i en familie som har flyttet til et nytt land?", "Familiemedlemmene kan være i ulike faser", "Hele familien går gjennom fasene likt", "Barna merker ingenting av flyttingen" ]
] },
{ "emne": "Identitet", "kilde": "https://samfunnskunnskap.no/nb/helse/identitet.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/2017-06-16-51"], "items": [
[ "Hva betyr identitet?", "Hvordan vi oppfatter oss selv", "Hvor mye penger vi tjener", "Hvilket pass vi har" ],
[ "Hva er med på å forme identiteten vår?", "Personlighet, interesser og venner", "Blodtypen og øyefargen vi er født med", "Hvor høye og sterke vi er som voksne" ],
[ "Hva forteller noe om en persons seksuelle identitet?", "Hvem personen blir forelsket i", "Hvilke klær personen liker", "Hvilket kjønn personen er født med" ],
[ "Hva kaller vi måten en person viser kjønn på, for eksempel med klær?", "Kjønnsuttrykk", "Seksuell legning", "Kjønnsrolle" ],
[ "Hva betyr kjønnsidentitet?", "Hvilket kjønn en person føler seg som", "Hvem en person blir forelsket i", "Hvilke klær en person bruker" ],
[ "Hva er det større åpenhet for i Norge i dag enn før?", "At ikke alle passer inn i gutt eller jente", "At alle må være enten gutt eller jente", "At kjønnsrollene alltid skal være like" ],
[ "Hva betyr heteroseksuell?", "Å bli forelsket i en av motsatt kjønn", "Å bli forelsket i en av samme kjønn", "Å ikke bli forelsket i noen" ],
[ "Hva sier norsk lov om diskriminering på grunn av seksuell orientering?", "Det er forbudt i loven", "Det er lov for arbeidsgivere", "Det er lov for utleiere av bolig" ]
] }
] };
