module.exports = { "tema": "Historie", "emner": [
{ "emne": "De første nordmenn", "kilde": "https://samfunnskunnskap.no/nb/historie/de-forste-nordmenn.html", "tillegg": ["https://snl.no/steinalderen_i_Norge","https://snl.no/vikingtiden"], "items": [
[ "Hva dekket Nord-Europa under istiden?", "Et tykt lag med is", "En stor og varm skog", "Et grunt og salt hav" ],
[ "Omtrent hvor lenge har det bodd mennesker i Norge?", "I rundt 12 000 år", "I rundt 2000 år", "I rundt 50 000 år" ],
[ "Hva levde de første menneskene i Norge av?", "Fisk, dyr, bær og sopp", "Korn og grønnsaker fra åkeren", "Melk og kjøtt fra kuer og sauer" ],
[ "Hvorfor kaller vi den første perioden steinalderen?", "Mange redskaper var laget av stein", "Folk bodde i store hus laget av stein", "Folk bygde store murer av stein" ],
[ "Omtrent når begynte folk med jordbruk i Norge?", "For rundt 4000 år siden", "For rundt 400 år siden", "For rundt 40 000 år siden" ],
[ "Hva begynte bøndene å gjøre i bronsealderen?", "Å bruke hest til å trekke", "Å lage redskaper og våpen av jern", "Å bygge kirker av stein" ],
[ "Hvor fant folk jernmalm i jernalderen?", "I myrene", "I havet", "I trærne" ],
[ "Hva skjedde da folk fikk redskaper av jern?", "Det ble lettere å dyrke jorda", "Det ble mye vanskeligere å fiske", "Folk sluttet å holde husdyr" ],
[ "Omtrent når var vikingtiden?", "Fra år 800 til 1050", "Fra år 200 til 400", "Fra år 1350 til 1500" ],
[ "Hva var en høvding i vikingtiden?", "En rik og mektig storbonde", "En prest i den kristne kirken", "En fattig bonde uten egen jord" ],
[ "Hva gjorde vikingene på reisene sine i Europa?", "De handlet, men kriget og plyndret også", "De studerte ved skoler i store byer", "De bygde kirker og hjalp de fattige" ],
[ "Hvem regnes som den første kongen over hele Norge?", "Harald Hårfagre", "Olav Haraldsson", "Olav Tryggvason" ],
[ "Hva trodde vikingene på før kristendommen kom?", "Norrøne guder, som Odin og Tor", "Én gud, slik som de kristne", "Guder fra det gamle Egypt og Hellas" ],
[ "Hva skjedde på Stiklestad i år 1030?", "Et slag der Olav Haraldsson døde", "Norge fikk sin første grunnlov", "Den første byen i Norge ble bygd" ]
] },
{ "emne": "Middelalder og unionstid", "kilde": "https://samfunnskunnskap.no/nb/historie/middelalder-og-unionstid.html", "tillegg": ["https://snl.no/svartedauden","https://snl.no/Kalmarunionen","https://snl.no/reformasjonen"], "items": [
[ "Hva gjorde kirken med Olav Haraldsson etter at han døde?", "Gjorde ham til helgen", "Gjorde ham til pave", "Gjorde ham til biskop" ],
[ "Hvorfor ble mange vanlige folk kristne etter hvert?", "Høvdinger og storbønder ble kristne først", "Kongen i Danmark betalte dem for det", "De gamle gudene var forbudt i Europa" ],
[ "Hva måtte folk gi til kirken i middelalderen?", "Skatt, og ofte også jord", "Soldater til kirkens hær", "Barn som skulle bli prester" ],
[ "Hvorfor ble mange bønder fattigere i middelalderen?", "De måtte betale skatt og gi fra seg jord", "De mistet dyrene sine i lange kriger", "De fikk ikke lov til å selge mat" ],
[ "Hva het Trondheim i middelalderen?", "Nidaros", "Bjørgvin", "Kristiania" ],
[ "Hva var svartedauden?", "En farlig sykdom i mange land", "En lang krig mellom to land", "En vinter med mye kulde og snø" ],
[ "Hvorfor fikk sykdommen navnet svartedauden?", "De syke fikk blåsvarte byller", "Den kom i den mørke vinteren", "De døde ble kledd i svarte klær" ],
[ "Hvordan kom svartedauden til Norge i 1349?", "Med et skip som kom til Bergen", "Med soldater som gikk fra Sverige", "Med fugler som fløy fra sør" ],
[ "Omtrent hvor mange døde i Europa under svartedauden?", "Rundt halvparten av folket", "Rundt en tidel av folket", "Rundt ni av ti personer" ],
[ "Hva betyr union mellom to land?", "Landene styres sammen, ofte med én konge", "Landene har krig mot hverandre", "Landene har ingen kontakt med hverandre" ],
[ "Hvilke land var med i unionen fra 1397?", "Norge, Danmark og Sverige", "Norge, Island og Finland", "Norge, Tyskland og England" ],
[ "Hvilket skriftspråk brukte nordmenn i unionen med Danmark?", "Dansk", "Svensk", "Tysk" ],
[ "Hva betyr ordet protestant?", "En som fulgte Luthers protest mot kirken", "En som var prest i den katolske kirken", "En som støttet paven og makten til kirken" ],
[ "Hvor lenge var protestantismen statsreligion i Norge?", "Fram til 2012", "Fram til 1814", "Fram til 1905" ]
] },
{ "emne": "Norge fra 1814 til 1905", "kilde": "https://samfunnskunnskap.no/nb/historie/norge-fra-1814-til-1905.html", "tillegg": ["https://snl.no/Kielfreden","https://snl.no/Unionsoppl%C3%B8sningen_i_1905","https://snl.no/kongevalget_i_1905","https://snl.no/Haakon_7"], "items": [
[ "Hvorfor måtte Danmark gi fra seg Norge i 1814?", "Danmark var på den siden som tapte krigen", "Folk i Norge stemte for å gå ut", "Danmark hadde ikke råd til å ha Norge" ],
[ "Hvilket land skulle få Norge etter freden i Kiel i 1814?", "Sverige", "England", "Frankrike" ],
[ "Hva ville mennene på Eidsvoll i 1814?", "Lage en grunnlov for et fritt Norge", "Gjøre Norge til en del av Sverige", "Bli med i en krig mot England" ],
[ "Hvorfor kom Norge i union med Sverige i 1814?", "Norge ble tvunget inn etter en kort krig", "Folket stemte ja til det i et valg", "Norge ville ha hjelp mot Danmark" ],
[ "Hvordan var unionen med Sverige sammenlignet med unionen med Danmark?", "Løsere, med mer selvstyre i Norge", "Strengere, med mindre selvstyre i Norge", "Helt lik den gamle unionen" ],
[ "Hva ble styrt fra Sverige i unionstiden?", "Utenrikspolitikken", "Skolene i Norge", "Kirkene i Norge" ],
[ "Hvem har Karl Johans gate i Oslo navn etter?", "En svensk konge", "En norsk bonde", "En dansk prest" ],
[ "Hva var nasjonalromantikken?", "En retning i kunst og kultur", "Et politisk parti i Stortinget", "En religiøs bevegelse i kirken" ],
[ "Hva ble sett på som «typisk norsk» i nasjonalromantikken?", "Naturen og livet til bøndene", "Byene og livet på fabrikkene", "Kongen og livet på slottet" ],
[ "Hva er bokmål opprinnelig?", "En fornorsket form av dansk", "En blanding av svensk og tysk", "Det gamle språket til vikingene" ],
[ "Hva brukte Ivar Aasen for å lage nynorsk?", "Dialekter fra mange steder i landet", "Ord fra dansk og svensk skriftspråk", "Språket til folk i de store byene" ],
[ "Hvordan levde mange arbeiderfamilier i byene på 1800-tallet?", "Med lange arbeidsdager og trange boliger", "Med korte arbeidsdager og store, gode boliger", "Med god lønn og mye fritid hver dag" ],
[ "Hvorfor var det vanskelig å bo på landsbygda på 1800-tallet?", "Det var ikke nok jord og arbeid", "Det var forbudt å ha dyr på gården", "Det var for mange fabrikker der" ],
[ "Omtrent hvor mange nordmenn utvandret til Amerika fra 1850 til 1920?", "Mer enn 800 000", "Rundt 8000", "Rundt 80 000" ],
[ "Hva betyr det å utvandre?", "Å flytte fra landet sitt til et annet", "Å flytte fra byen til landsbygda", "Å reise på en lang ferie til et annet land" ],
[ "Hvordan reagerte Sverige på at Norge brøt unionen i 1905?", "Sterkt, og det ble nesten krig", "Svenskene feiret sammen med Norge", "Sverige brydde seg ikke om det" ],
[ "Hva ble bestemt i den andre folkeavstemningen i 1905?", "At Norge skulle være et monarki", "At Norge skulle ha en president", "At kvinner skulle få stemmerett" ],
[ "Hvem ble ny konge i Norge i 1905?", "Prins Carl fra Danmark", "Prins Gustav fra Sverige", "Prins Edward fra England" ]
] },
{ "emne": "Første og andre verdenskrig", "kilde": "https://samfunnskunnskap.no/nb/historie/forste-og-andre-verdenskrig.html", "tillegg": ["https://snl.no/stemmerett","https://snl.no/Holocaust_i_Norge","https://snl.no/Norge_under_andre_verdenskrig"], "items": [
[ "Hva begynte Norge å bruke fossene til på slutten av 1800-tallet?", "Å lage strøm fra vannkraft", "Å vanne store åkre", "Å drive store fiskeoppdrett" ],
[ "Hvor lang kunne en vanlig arbeidsdag være fra 1919?", "Åtte timer", "Ti timer", "Tolv timer" ],
[ "Hva fikk arbeiderne rett til med syketrygd?", "Penger fra staten når de var syke", "Gratis mat på jobben hver eneste dag", "Fri fra jobben om sommeren" ],
[ "Hvem fikk stemmerett ved stortingsvalg i 1898?", "Menn over 25 år", "Kvinner over 25 år", "Menn over 40 år" ],
[ "Hvorfor vedtok Stortinget nye lover for arbeiderne tidlig på 1900-tallet?", "Fagforeningene presset på for endringer", "Kongen krevde det i en tale til folket", "Sverige bestemte det for Norge" ],
[ "Hvordan var Norge med i første verdenskrig?", "Norge var ikke aktivt med", "Norge kjempet på Tysklands side", "Norge kjempet på Englands side" ],
[ "Hva er rasjonering?", "Varene blir delt likt mellom folk", "Varene blir gratis i butikkene", "Prisene på varene går ned" ],
[ "Hva var et stort problem i mellomkrigstiden?", "Mange var uten arbeid", "Det var mangel på arbeidere", "Lønningene steg veldig mye" ],
[ "Hva skjedde i Norge 9. april 1940?", "Tyske soldater okkuperte landet", "Norge ble med i NATO", "Krigen i Europa tok slutt" ],
[ "Hva betyr det at et land blir okkupert?", "Et annet land tar kontroll over det", "Landet velger en ny regjering", "Landet blir enig om fred" ],
[ "Hvor styrte kongen og regjeringen fra under krigen?", "Fra London i England", "Fra Stockholm i Sverige", "Fra Oslo i Norge" ],
[ "Hvem var Vidkun Quisling?", "Leder av en tyskvennlig regjering", "Leder av den norske motstanden mot tyskerne", "Konge i Norge under krigen" ],
[ "Hva gjorde motstandsbevegelsen under krigen?", "Sabotasje og ulovlige aviser", "Hjalp tyskerne med å styre", "Bygde nye veier for tyskerne" ],
[ "Hvor flyktet rundt 50 000 nordmenn under krigen?", "Til Sverige", "Til Tyskland", "Til Finland" ],
[ "Hva gjorde tyskerne i Finnmark og Nord-Troms mot slutten av krigen?", "Brente de fleste husene", "Bygde mange nye byer", "Ga folket mat og hjelp" ],
[ "Hva skjedde med mange norske jøder under krigen?", "De ble deportert og de fleste drept", "De fikk reise trygt til Amerika", "De fikk bo på gårder i Norge" ]
] },
{ "emne": "Det moderne Norge", "kilde": "https://samfunnskunnskap.no/nb/historie/det-moderne-norge.html", "tillegg": ["https://snl.no/Ekofisk","https://snl.no/Gro_Harlem_Brundtland","https://snl.no/likestillingsloven","https://snl.no/terrorangrepene_i_Norge_22._juli_2011","https://snl.no/arbeidsinnvandring","https://snl.no/Norges_historie_fra_1970_til_1990"], "items": [
[ "Hva var en viktig oppgave i Norge rett etter 1945?", "Å bygge opp landet igjen", "Å lete etter olje i havet", "Å starte en ny union" ],
[ "Hvilke to bevegelser har vært særlig viktige for det moderne Norge?", "Arbeiderbevegelsen og kvinnebevegelsen", "Fredsbevegelsen og miljøbevegelsen", "Bondebevegelsen og avholdsbevegelsen" ],
[ "Hvorfor ble arbeiderbevegelsen sterkere fra 1880-årene?", "Det kom flere jobber i industrien", "Kongen ville gi arbeiderne makt", "Bøndene fikk mer jord å dyrke" ],
[ "Hva har arbeiderbevegelsen kjempet for?", "Penger til dem som mister jobben", "Lengre arbeidsdager i fabrikkene", "Lavere lønn for unge arbeidere" ],
[ "Hva har kvinnebevegelsen kjempet for?", "Like muligheter for kvinner og menn", "At kvinner skal være hjemme med barna", "At menn skal bestemme i familien" ],
[ "Når ble kvinnebevegelsen sterk igjen i Norge?", "I 1970-årene", "I 1950-årene", "I 1990-årene" ],
[ "Hvem var Norges første kvinnelige statsminister?", "Gro Harlem Brundtland", "Camilla Collett", "Aasta Hansteen" ],
[ "Hvilken lov fra 1978 skulle sikre like rettigheter for kvinner og menn?", "Likestillingsloven", "Arbeidsmiljøloven", "Barneloven" ],
[ "Hva fant man i Nordsjøen i 1969?", "Det store oljefeltet Ekofisk", "Store mengder med gull og sølv", "Gamle skip fra vikingtiden" ],
[ "Hvem eier olje- og gassressursene på norsk sokkel?", "Staten, altså fellesskapet", "Selskapene som finner oljen", "Folk som bor nær kysten" ],
[ "Hva er mange uenige om når det gjelder oljen i dag?", "Hva den betyr for natur og miljø", "Hvem som fant den første oljen", "Om det finnes noe olje i Nordsjøen" ],
[ "Hvilke rettigheter hadde folk i Norge før oljen ble funnet?", "Gratis skole og syketrygd", "Oljepenger til hver familie", "Gratis bolig for voksne" ],
[ "Hva stemte et flertall i Norge i 1972 og 1994?", "Nei til å bli med i EF og EU", "Ja til å bli med i EF og EU", "Nei til å bli med i FN og NATO" ],
[ "Hva er EØS-avtalen?", "En avtale om handel og samarbeid med EU", "En avtale om forsvar sammen med USA og Canada", "En avtale om fiske med Russland" ],
[ "Hvilket internasjonalt samarbeid er Norge med i?", "FN, NATO og EØS", "EU, FN og OPEC", "EU, NATO og OPEC" ],
[ "Hvor stor del av folket bor i byer og tettsteder i dag?", "Rundt 80 prosent", "Rundt 35 prosent", "Rundt 15 prosent" ],
[ "Hvorfor kom mange arbeidsinnvandrere til Norge rundt 1970?", "Det var mangel på arbeidskraft", "Det var krig i Norge da", "Norge ga dem gratis bolig" ],
[ "Hva skjedde i Norge 22. juli 2011?", "Terrorangrep i Oslo og på Utøya", "En stor flom på Vestlandet", "Et skipsforlis i Nordsjøen" ]
] }
] };
