module.exports = { tema: "Kritisk tenkning og digital dømmekraft", emner: [{ emne: "A2", kilde: "", items: [
["Hva er kildekritikk?","Å tenke kritisk om det du leser","Å være uenig i det du leser","Å ikke like det du leser"],
["Hvorfor må vi være kritiske til informasjon på nettet?","Fordi alle kan legge ut ting på nettet","Fordi alt på nettet er skrevet av staten","Fordi alt på nettet er på engelsk"],
["Hva bør du spørre om når du leser en tekst på nettet?","Hvem har skrevet den, og stemmer det?","Hvor mange har delt teksten på nettet?","Er teksten lett å lese og pen å se på?"],
["Hva er etisk bevissthet?","Å tenke på ulike hensyn når du velger","Å gjøre det som er best for deg selv alene","Å følge reglene uten å tenke selv"],
["Hva er kritisk tenkning?","Å tenke over informasjon","Å være uenig med de fleste hele tiden","Å si noe negativt om alt du hører"],
["Hva er viktig i Norge når det gjelder meninger?","At alle kan ha sin egen mening","At alle skal mene det samme","At alle skal være enige med læreren"],
["Hva må til for at vi skal lære nye ting i samfunnet?","Spørre om det vi vet, og diskutere","Gjenta nøyaktig det som står i boka","Unngå å være uenig med de fleste"],
["Hva må du gjøre hvis du bruker andres tekster, bilder eller musikk?","Oppgi hvem som har laget det","Endre litt på verket så det blir ditt","Spørre vennene dine om lov"],
["Hva kan du gjøre hvis to kilder sier noe ulikt?","Se på hvem som har skrevet, og hvorfor","Tro mest på den med flest følgere","Velge den som passer deg best"],
["Hva kalles et samfunn med mye informasjon?","Informasjonssamfunn","Industrisamfunn","Jordbrukssamfunn"],
["Hva betyr ordet etikk?","Hvordan man bør oppføre seg","Hvordan man tjener penger best","Hvordan man lærer fag på skolen"],
["Hvilken nettside sjekker fakta i debatter?","Faktisk.no","Datatilsynet.no","Medietilsynet.no"],
["Familien vil ha miljøvennlig bil med plass til besteforeldre. Hva må de se på?","Utslipp og hvor mye plass bilen har","Fargen på bilen og hvor pen den er","Hvilket bilmerke som er mest kjent i Norge"],
["Hva betyr det at avsenderen har en agenda?","Avsenderen vil oppnå noe med teksten","Avsenderen har laget en plan for møtet","Avsenderen er sjef i en stor bedrift"],
["Hvilke av disse er sosiale medier?","TikTok, Facebook og Instagram","Gmail, Outlook og Yahoo","Finn.no, Nav.no og Skatteetaten"],
["Hva er personvern?","Retten til å bestemme over dine opplysninger","Retten til å si hva du vil, når du vil","Retten til å bli beskyttet mot all kritikk"],
["Hva er et eksempel på personopplysninger?","Navn, adresse og telefonnummer","Været i byen og dagens dato","Åpningstidene til en butikk"],
["Hva bør du gjøre før du deler bilder av andre?","Spørre personene om lov først","Sjekke at bildet er skarpt nok","Sjekke at bildet ikke er gammelt"],
["Hva er forbudt å skrive på nettet?","Rasistiske og diskriminerende utsagn","Negative meninger om det norske samfunnet","Kritikk av politikere og kjente personer"],
["Hva er et tegn på god digital dømmekraft?","Å skrive det du kan si ansikt til ansikt","Å ikke dele egne meninger på nettet","Å bruke et falskt navn når du skriver"],
["Hva kan skje når man er anonym i kommentarfelt?","Mange skriver stygge eller ulovlige ting","Folk skriver mer høflig enn ellers","Færre mennesker tør å skrive noe"],
["Hva er digitale spor?","Det du gjør på nettet, og som blir lagret","Bilder som forsvinner etter noen timer","Passordene du har lagret på mobilen"],
["Hvordan kan man vise hvem man er på nettet?","Med BankID, passord eller fingeravtrykk","Med fødselsdato og telefonnummeret ditt","Med e-postadressen og profilbildet ditt"],
["Hva begrenser ytringsfriheten?","Personvernet og noen regler i loven","Regler som hver kommune bestemmer selv","Det som flertallet synes er riktig"],
["Hva betyr privatliv?","Ting som hører til deg og dine","Ting du deler med kollegene dine","Ting som staten bestemmer over deg"],
["Hva kan skje hvis noen får passordet ditt?","De kan bruke kontoen din og dele bilder","Du får et nytt og tryggere passord","Politiet gir deg beskjed samme dag"],
["Noen deler et privat bilde av deg og skriver løgn om deg. Hva er dette?","Ulovlig, og du kan melde det til politiet","Lovlig, fordi det er ytringsfrihet","Lovlig, hvis profilen er offentlig"],
["Hvorfor er det viktig å tenke på hva du deler på nettet?","Andre kan få vite ting om deg og bruke dem","Det du deler blir slettet etter noen uker","Det er nærmeste venner som ser det du deler"],
["Hva er falske nyheter?","Usann informasjon som ser ut som nyheter","Nyheter som kommer fra et annet land","Nyheter som mange har delt på nettet"],
["Hva bør du gjøre før du deler en overraskende nyhet?","Sjekke om pålitelige kilder skriver det samme","Dele den raskt slik at andre også får vite det","Spørre vennene dine om de liker saken"],
["Hva er en pålitelig kilde?","En kilde som sier hvem som står bak","En kilde som har mange følgere","En kilde som bruker store overskrifter"],
["Hva betyr ordet avsender?","Den som har laget informasjonen","Den som leser teksten på nettet","Den som betaler for ditt internett"],
["Hva er klikkbait?","En overskrift som lokker deg til å klikke","En advarsel om virus på datamaskinen din","En betaling for å kunne lese hele artikkelen"],
["Hvorfor kan et bilde på nettet lure oss?","Det kan være endret eller tatt ut av sammenheng","Bilder på nett er ofte for gamle til å vise noe nytt","Bilder på nett er ofte tatt i andre land"],
["Hva er en kilde?","Det stedet informasjonen kommer fra","Det stedet informasjonen blir slettet","Den personen som leser først"],
["Hvorfor bør du lese mer enn én kilde om en sak?","Flere kilder gir et bedre bilde av saken","Det gir deg flere sider å dele på sosiale medier","Én kilde kan ikke ha riktig informasjon"],
["Hva kan du gjøre for å sjekke om et bilde er gammelt eller falskt?","Søke etter bildet med et bildesøk","Spørre en fremmed i et kommentarfelt","Se hvor mange likes bildet har fått"],
["Hvilke av disse utsagnene er et eksempel på et faktum?","Oslo er hovedstaden i Norge","Norsk mat er den beste i verden","Vinteren er den vakreste årstiden"],
["Hva er en mening?","Det en person mener om noe","Noe som politikerne har bestemt","Noe som står skrevet i en lov"],
["Hvorfor bør du være kritisk til reklame?","Avsenderen vil at du skal kjøpe noe","Reklamen er skrevet av en offentlig etat","Reklamen er skrevet på et vanskelig språk"],
["Hva gjør journalister?","De undersøker og skriver nyheter","De bestemmer hvilke lover som skal gjelde","De bestemmer hva folk skal mene om saker"],
["Hva er et tegn på et seriøst nyhetsmedium?","Det retter feil når det får vite om dem","Det skriver det som gir flest klikk","Det får betalt av dem det skriver om"],
["Hva er en algoritme i sosiale medier?","Regler som bestemmer hva du ser i appen","En ansatt som godkjenner innleggene","Et program som sletter gamle bilder for deg"],
["Hvorfor er det lurt å lese meninger som er ulike dine egne?","Da får du bedre grunnlag for å vurdere saken","Da blir du automatisk enig med flertallet","Da trenger du ikke å sjekke fakta"],
["Hva er ytringsfrihet?","Retten til å si og skrive det du mener","Retten til å bestemme over andres meninger","Retten til å slippe å høre uenighet"],
["Hvor står det at vi har ytringsfrihet i Norge?","I Grunnloven","I vegtrafikkloven","I ferieloven"],
["Hva er hatprat?","Krenkende utsagn om en bestemt gruppe","Å snakke veldig høyt på offentlig sted","Å være sterkt uenig med en politiker"],
["Hva er diskriminering?","Å behandle noen dårligere på grunn av bakgrunn","Å gi folk de samme rettighetene i samfunnet","Å velge ut den beste søkeren til en jobb"],
["Hva kan du gjøre hvis du ser hatefulle kommentarer på nettet?","Melde fra til nettstedet eller politiet","Svare med enda verre ord enn avsenderen","Dele kommentaren med vennene dine"],
["Hva er nettmobbing?","Å plage eller krenke noen igjen og igjen","Å være uenig med en venn i en samtale på nett","Å skrive en kritisk anmeldelse av en film"],
["Hva er lurt å gjøre hvis du blir mobbet på nettet?","Ta skjermbilde og snakke med en du stoler på","Slette alt og ikke snakke med noen om det","Svare med trusler til den som mobber"],
["Er det lov å true noen på nett?","Nei, trusler er forbudt, også på nett","Ja, det er ytringsfrihet på nettet","Ja, hvis man bruker et falskt navn"],
["Hva er sensur?","At noen forbyr eller stopper en ytring","At noen retter skrivefeil i en tekst","At noen oversetter en tekst til et annet språk"],
["Kan man kritisere regjeringen i Norge?","Ja, det er en viktig del av demokratiet","Nei, det er forbudt å kritisere politikere","Ja, men det krever tillatelse fra politiet"],
["Hva er et personnummer?","Et nummer med 11 siffer som er ditt","Et nummer som viser hvor mye du tjener","Et nummer du får når du kjøper bolig"],
["Hvem bør få vite personnummeret ditt?","De som trenger det, som banken og Nav","Folk som spør om det på sosiale medier","Naboene dine og kollegene på jobben"],
["Hva er Datatilsynet?","En myndighet som passer på personvernet","En myndighet som kontrollerer skatten","En myndighet som utsteder pass og ID-kort"],
["Hva er et eksempel på et sterkt passord?","Et langt passord med tall og tegn","Fornavnet ditt og fødselsåret ditt","Et enkelt ord fra ordboken uten tegn"],
["Hva bør du gjøre med passordene dine?","Bruke ulike passord på ulike nettsteder","Bruke samme passord overalt for å huske det","Gi passordene til nære venner og familie"],
["Hva gjør en kode på mobilen når du logger inn?","Den gjør kontoen din tryggere","Den gjør nettet mye raskere","Den sletter gamle meldinger"],
["Hva er en cookie på en nettside?","En liten fil som husker hva du gjør","Et virus som kan stjele passordene","En avgift man må betale for å logge inn"],
["Hvorfor vil noen firmaer ha opplysninger om deg?","De kan bruke dem til å vise deg reklame","De vil hjelpe deg å få en ny jobb","De må gi dem videre til skolen din"],
["Hva bør du gjøre med personverninnstillingene i sosiale medier?","Sjekke hvem som kan se innleggene dine","Åpne innstillingene så hvem som helst kan se alt","Ikke endre noe, siden det ikke har betydning"],
["Hva bør du gjøre før du gir fra deg opplysninger på et nettsted?","Sjekke hvem som får dem og hvorfor","Fylle ut hele skjemaet uten å lese vilkårene","Oppgi også kontaktinfo til vennene dine"],
["Hva er nettfiske (phishing)?","Svindel der noen later som de er andre","En måte å søke etter bilder på nettet","Et program som gjør nettet mye raskere"],
["En SMS ber deg betale for en stoppet pakke via en lenke. Hva er lurt?","Ikke klikke, men sjekke med postselskapet","Klikke på lenken og betale med en gang","Svare på meldingen og be om mer info"],
["Noen ringer fra «banken» og vil ha BankID-koden din. Hva bør du gjøre?","Avslutte samtalen og ikke si koden","Gi koden hvis personen høres høflig ut","Gi koden hvis de oppgir navnet sitt"],
["Hva er et tegn på at en e-post kan være svindel?","Den har mange skrivefeil og haster med svar","Den kommer fra en kollega du kjenner","Den kommer fra den vanlige bankadressen din"],
["Hvorfor er det risikabelt å bruke åpent wifi til nettbank?","Andre kan se hva du gjør på nettet","Wifi er ulovlig å bruke i Norge","Nettbanken fungerer ikke på kafé"],
["Hvorfor er det lurt å oppdatere telefonen jevnlig?","Oppdateringer retter sikkerhetsfeil i telefonen","Oppdateringer gjør telefonen billigere å bruke","Oppdateringer sletter gamle bilder fra telefonen"],
["Hva er et virus på datamaskinen?","Et skadelig program på datamaskinen","Et program som gjør maskinen raskere","En venn som låner datamaskinen din"],
["Hvorfor bør du logge ut av nettbanken når du er ferdig?","Så ingen andre kommer inn på kontoen","Så banken får mer penger fra deg hvert år","Så nettleseren blir raskere å bruke"],
["Hva er BankID?","En elektronisk ID for trygg innlogging","Et kort du bruker for å handle i butikk","Et nummer som politiet gir deg"],
["Hvor melder du fra om svindel på nett?","Til politiet og til banken din","Til Skatteetaten og Lånekassen","Til kommunen og til barnehagen"],
["Hva er et etisk dilemma?","Et valg mellom to ting som begge er viktige","En situasjon der folk er enige om svaret","En situasjon der loven gir ett klart svar"],
["Du finner en lommebok med penger på gaten. Hva er riktig å gjøre?","Levere den til politiet eller eieren","Beholde pengene og kaste lommeboken","Legge den tilbake på gaten og gå videre"],
["Hva er et tegn på kritisk tenkning?","Å endre mening når man får bedre fakta","Å holde fast ved meningen uansett hva som skjer","Å bytte mening hver gang noen sier noe"],
["Hva er god debattkultur?","Å diskutere saken, ikke personen","Å snakke høyere enn de andre i rommet","Å avbryte den som er uenig med deg"],
["Hva er opphavsrett?","Retten til å bestemme over eget verk","Retten til å bruke alt som er på nettet","Retten til å kopiere andres tekster"],
["Hva er en deepfake?","En falsk video eller et bilde laget med KI","En kjent film som er kopiert uten lov","En video som er tatt opp med dårlig lyd"],
]}]};
