module.exports = { "tema": "Ny i Norge", "emner": [ 
{ "emne": "Et liv i Norge", "kilde": "https://samfunnskunnskap.no/nb/ny-i-norge/et-liv-i-norge.html", "items": [
[ "Omtrent hvor mange barn blir født i Norge hvert år?", "Omtrent 50 000 barn", "Omtrent 5 000 barn", "Omtrent 500 000 barn" ],
[ "Hvor mange barn får en kvinne i Norge i gjennomsnitt?", "Omtrent 1,4 barn", "Omtrent 3 barn", "Omtrent 5 barn" ],
[ "Hvor gammel er en kvinne i Norge når hun får første barn?", "Omtrent 30 år gammel", "Omtrent 20 år gammel", "Omtrent 40 år gammel" ],
[ "Hva sier norsk lov om omskjæring av jenter?", "Det er forbudt, og straffen kan være opptil 15 år i fengsel", "Det er lov hvis foreldrene ønsker det og legen er enig", "Det er lov hvis jenta er over ti år gammel" ],
[ "Hva er en barnehage?", "Et sted for små barn mens foreldrene er på jobb eller skole", "Et sted der barn lærer å lese og skrive før de begynner på skolen", "Et sted der barn bor når foreldrene er syke" ],
[ "Hva betyr ordet «egenandel»?", "En del av prisen som du betaler selv", "Penger som du får fra staten", "Penger som du låner av banken" ],
[ "Hva betaler foreldre for en plass i barnehagen?", "En egenandel hver måned", "Foreldrene betaler full pris selv", "Barnehagen er gratis for foreldrene" ],
[ "Hvem kan få kontantstøtte?", "Foreldre med små barn som ikke har barnehageplass", "Foreldre som har barn på ungdomsskolen og videregående", "Foreldre som tar utdanning i utlandet" ],
[ "Hva er foreldrepenger?", "Penger fra Nav når foreldre er hjemme med et nytt barn", "Penger fra barnehagen når barnet begynner", "Penger fra skolen når barnet er syk" ],
[ "Hvem betaler barnetrygd til foreldrene?", "Staten", "Arbeidsgiveren", "Barnehagen" ],
[ "Hvor lenge får foreldre barnetrygd for et barn?", "Til barnet er 18 år", "Til barnet er 12 år", "Til barnet begynner på skole" ],
[ "Hvor mye barnetrygd får et barn i en rik familie?", "Like mye som et barn i en fattig familie", "Mer enn et barn i en fattig familie", "Mindre enn et barn i en fattig familie" ],
[ "Hvor mange år varer grunnskolen i Norge?", "Ti år", "Syv år", "Tretten år" ],
[ "Hvilke klasser er barneskolen?", "1. til 7. klasse", "1. til 4. klasse", "5. til 10. klasse" ],
[ "Hvor gamle er elever på ungdomsskolen?", "Omtrent 13 til 16 år", "Omtrent 7 til 10 år", "Omtrent 16 til 19 år" ],
[ "Fra hvilken alder må barn gå på skole i Norge?", "Fra de er seks år, i 1. klasse", "Fra de er tre år, som i barnehagen", "Fra de er ti år, i 5. klasse" ],
[ "Hva koster det å gå på offentlig grunnskole?", "Ingenting, skolen er gratis", "En liten pris hver måned", "Halv pris for lav inntekt" ],
[ "Hva er SFO?", "Et tilbud for barn på skolen før og etter skoletid", "Et fag på barneskolen der barna lærer om sport og friluftsliv", "En skole for barn som trenger ekstra hjelp" ],
[ "Omtrent hvor mange barn i 1. til 4. klasse går på SFO?", "Omtrent åtte av ti barn", "Omtrent to av ti barn", "Omtrent én av ti barn" ],
[ "Hvor mange fullfører videregående skole i Norge?", "Nesten åtte av ti elever", "Omtrent fire av ti elever", "Omtrent seks av ti elever" ],
[ "Hvor mange elever velger yrkesfag på videregående?", "Omtrent halvparten", "Omtrent én av ti elever", "Omtrent ni av ti elever" ],
[ "Hva gir studiespesialisering deg?", "Rett til å søke på universitet og høgskole", "Rett til å få fagbrev som lærling", "Rett til å starte i 1. klasse på SFO" ],
[ "Hva kan du få etter yrkesfag og læretid?", "Fagbrev", "Bachelorgrad", "Studielån" ],
[ "Hva er en lærling?", "En person som lærer et yrke på en arbeidsplass", "En elev som tar ekstra fag på ungdomsskolen i helgene", "En student som tar bachelor på universitetet" ],
[ "Hva er en bachelorgrad?", "En utdanning på universitetet som tar omtrent tre år", "En utdanning på videregående som tar to år", "En utdanning for lærlinger som tar fire år" ],
[ "Hva er et stipend?", "Penger til studenter som de ikke må betale tilbake", "Penger til studenter som de må betale tilbake senere", "Penger til lærlinger fra arbeidsgiveren" ],
[ "Hvem gir studielån i Norge?", "Lånekassen", "Nav", "Skatteetaten" ],
[ "Hvor mye studiegjeld har mange studenter etter studiene?", "Over 300 000 kroner", "Under 30 000 kroner", "Omtrent 3 000 kroner" ],
[ "Hva betyr det å være myndig?", "Du bestemmer selv over livet og pengene dine", "Du må begynne å jobbe full tid", "Du må bo hjemme hos foreldrene" ],
[ "Når blir en person myndig i Norge?", "Når personen er 18 år", "Når personen er 16 år", "Når personen er 21 år" ],
[ "Hvem har ansvar for barn under 18 år?", "Foreldrene", "Barna selv", "Skolen" ],
[ "Hvor gamle er mange nordmenn når de gifter seg?", "Mellom 30 og 40 år gamle", "Mellom 18 og 20 år gamle", "Mellom 50 og 60 år gamle" ],
[ "Hva betyr det å være samboer?", "Å bo sammen som par uten å være gift", "Å bo sammen med foreldrene som voksen", "Å bo sammen med en venn for å spare penger" ],
[ "Hva er skilsmisse?", "Når et gift par avslutter ekteskapet", "Når et par flytter sammen uten å gifte seg", "Når et par får et barn og blir foreldre" ],
[ "Hva betyr likestilling?", "Kvinner og menn har samme rettigheter og muligheter", "Kvinner og menn må gjøre det samme arbeidet", "Kvinner og menn må være like gamle" ],
[ "Hva er et boliglån?", "Penger fra banken som du bruker til å kjøpe bolig", "Penger fra staten som du får når du flytter", "Penger som du betaler til utleier hver måned" ],
[ "Hvor mye gjeld tar mange med seg når de kjøper bolig?", "Over to millioner kroner", "Omtrent 200 000 kroner til hver bolig", "Omtrent 20 000 kroner til hver bolig" ],
[ "Hvilken etat betaler ut pensjon fra folketrygden?", "Nav", "Lånekassen", "Skatteetaten" ],
[ "Hvor gamle er mange nordmenn når de slutter å jobbe?", "Omtrent 67 år gamle", "Omtrent 50 år gamle", "Omtrent 80 år gamle" ],
[ "Hva er kremasjon?", "Når en død person blir brent", "Når en død person blir lagt i jorden", "Når en død person blir sendt til hjemlandet" ],
[ "Hva er arv?", "Penger og ting du får når et familiemedlem dør", "Penger du får når du gifter deg med noen", "Penger du får fra staten når du fyller 18 år og blir myndig" ],
[ "Hva er et testament?", "Et dokument om hvem som skal arve etter en person", "Et dokument om hvem som eier en bolig", "Et dokument om hvem som er gift med hvem" ] ] }, 
{ "emne": "Regler for opphold", "kilde": "https://samfunnskunnskap.no/nb/ny-i-norge/regler-for-opphold.html", "items": [
[ "Hva er en innvandrer?", "En person som har flyttet til Norge fra et annet land", "En person som er på ferie hos familie i Norge i to uker", "En person som er født og oppvokst i Norge" ],
[ "Hva betyr ordet «oppholdstillatelse»?", "En tillatelse til å bo i Norge", "En tillatelse til å kjøre bil i Norge", "En tillatelse til å jobbe på sykehus" ],
[ "Hvem behandler søknader om oppholdstillatelse i Norge?", "Utlendingsdirektoratet (UDI)", "Arbeids- og velferdsetaten (Nav)", "Integrerings- og mangfoldsdirektoratet (IMDi)" ],
[ "Hva er nettsiden til UDI?", "udi.no", "nav.no", "skatteetaten.no" ],
[ "Hvor registrerer borgere fra EU og EØS seg når de flytter til Norge?", "Hos politiet", "Hos Nav", "Hos kommunen" ],
[ "Hva er en midlertidig oppholdstillatelse?", "En tillatelse som varer en periode, og du må søke på nytt", "En tillatelse som du får for resten av livet", "En tillatelse som du får som turist" ],
[ "Hva betyr permanent oppholdstillatelse?", "Du kan bo i Norge uten å søke om ny tillatelse", "Du har fått norsk pass og norsk statsborgerskap", "Du må søke om ny tillatelse hvert år" ],
[ "Hva er et statsborgerskap?", "Du tilhører et land og har rettigheter og plikter der", "Du har lov til å besøke et land som turist i tre måneder", "Du har lov til å jobbe i et land i ett år" ],
[ "Hva er en flyktning?", "En person som må forlate landet sitt fordi livet er i fare", "En person som flytter til et nytt land for å jobbe", "En person som flytter til et nytt land for å studere" ],
[ "Hva er en arbeidsinnvandrer?", "En person som flytter til Norge for å jobbe", "En person som får hjelp av FN til å flytte", "En person som flytter for å være sammen med familie" ],
[ "Hva er en asylsøker?", "En person som har søkt om beskyttelse og venter på svar", "En person som har fått norsk statsborgerskap for noen år siden", "En person som jobber for UDI og behandler saker" ],
[ "Hva er asyl?", "Beskyttelse for en person som er forfulgt i hjemlandet", "Tillatelse til å jobbe i Norge i ett år", "Tillatelse til å besøke familie i Norge" ],
[ "Hvordan vurderer Norge en søknad om asyl?", "Hver søker får sin egen vurdering", "Familien får én felles vurdering", "Søkere fra samme land får samme svar" ],
[ "Hvem er kvoteflyktninger?", "Flyktninger som er valgt ut før de kommer til Norge", "Flyktninger som kommer til den norske grensen på egen hånd", "Flyktninger som får jobb i Norge først" ],
[ "Hvilken organisasjon hjelper Norge med å velge kvoteflyktninger?", "UNHCR, FNs flyktningorganisasjon", "NATO, en forsvarsorganisasjon", "EU, et samarbeid mellom europeiske land" ],
[ "Hvilken tillatelse får kvoteflyktninger først?", "En midlertidig tillatelse", "En permanent tillatelse", "Norsk statsborgerskap" ],
[ "Hva er familiegjenforening?", "Et familiemedlem får flytte til familie som bor i Norge", "En familie får lavere skatt de første årene i Norge", "En familie får gratis bolig fra kommunen" ] ] }, 
{ "emne": "Introduksjonsprogrammet", "kilde": "https://samfunnskunnskap.no/nb/ny-i-norge/introduksjonsprogrammet-og-integreringsloven.html", "items": [
[ "Hva er introduksjonsprogrammet?", "Et opplæringstilbud for nyankomne flyktninger", "Et program på TV for nye innbyggere", "Et kurs for norske barn om andre land" ],
[ "Hva er målet med introduksjonsprogrammet?", "Å lære norsk og komme i jobb eller utdanning", "Å få norsk pass og statsborgerskap så raskt som mulig", "Å finne en ny bolig i en annen kommune" ],
[ "Hvem tilbyr introduksjonsprogram?", "Kommunen", "Arbeidsgiveren", "Politiet" ],
[ "Hvem får tilbud om introduksjonsprogram?", "Flyktninger som har fått opphold", "Arbeidsinnvandrere fra EU", "Studenter fra utlandet" ],
[ "Hvor lenge kan et introduksjonsprogram vare?", "Fra tre måneder til tre år", "Fra én uke til noen få måneder", "Fra fem år til ti år, hvis man ønsker det" ],
[ "Hva får deltakere i introduksjonsprogrammet?", "Økonomisk støtte", "Gratis bil", "Norsk pass" ],
[ "Hvorfor får deltakerne økonomisk støtte?", "Slik at de kan leve mens de lærer norsk", "Fordi de har fått gode karakterer i norskprøven", "Fordi de skal betale for kurset" ],
[ "Hva er en del av introduksjonsprogrammet?", "Opplæring i norsk", "Betalt reise hjem", "Studier i utlandet" ],
[ "Hva betyr ordet «integrering»?", "Nyankomne blir en del av samfunnet", "Nyankomne må reise hjem igjen", "Nyankomne bor i egne områder" ],
[ "Hva heter loven om introduksjonsprogrammet?", "Integreringsloven", "Folketrygdloven", "Utlendingsloven" ],
[ "Hvem har vedtatt integreringsloven?", "Stortinget", "Kommunen", "UDI" ],
[ "Hvor kan en flyktning spørre om introduksjonsprogrammet?", "I kommunen der personen bor", "Hos politiet i nærmeste by", "Hos banken som personen bruker" ] ] }, 
{ "emne": "Ny i Norge – hovedside", "kilde": "https://samfunnskunnskap.no/nb/ny-i-norge.html", "items": [
[ "Omtrent hvor mange mennesker bor i Norge?", "Over fem millioner", "Omtrent én million", "Nesten ti millioner" ],
[ "Hva slags styre har Norge?", "Et demokrati der kongen har en symbolsk rolle", "Et demokrati der kongen bestemmer over landets lover", "Et land uten konge og uten valg" ],
[ "Hvor ofte er det stortingsvalg i Norge?", "Hvert fjerde år", "Hvert annet år", "Hvert tiende år" ],
[ "Hvem kan stemme ved stortingsvalg?", "Norske statsborgere som er 18 år eller eldre", "Personer som har bodd tre år i Norge", "Norske statsborgere fra 16 år" ],
[ "Hva betyr velferdsstat?", "Staten hjelper innbyggerne med blant annet skole og helse", "Staten eier selskapene i landet og bestemmer lønnen", "Staten gir innbyggerne like mye penger i året" ],
[ "Hva bruker staten til å betale for velferden?", "Skatt som innbyggerne betaler", "Penger fra andre land i EU", "Penger som kongen eier" ],
[ "Når feirer Norge nasjonaldagen?", "17. mai", "1. mai", "8. mai" ],
[ "Hvilket år fikk Norge grunnloven sin?", "1814", "1905", "1945" ],
[ "Hvilken union gikk Norge ut av i 1905?", "Unionen med Sverige", "Unionen med Danmark", "Unionen med Finland" ] ] } ]
};
