module.exports = { "tema": "Personlig økonomi", "emner": [
{ "emne": "Personlig økonomi", "kilde": "https://samfunnskunnskap.no/nb/personlig-okonomi/personlig-okonomi.html", "tillegg": ["https://samfunnskunnskap.no/nb/personlig-okonomi.html", "https://www.skatteetaten.no/person/skatt/skattekort/", "https://www.skatteetaten.no/bedrift-og-organisasjon/arbeidsgiver/skattekort-og-skattetrekk/slik-trekker-du-riktig-skatt/", "https://www.skatteetaten.no/person/skatt/skattekort/frikort/", "https://www.skatteetaten.no/person/skatt/skattemelding/skattemelding-for-person/", "https://www.skatteetaten.no/person/skatt/skatteoppgjor/se-skatteoppgjoret-ditt/", "https://www.skatteetaten.no/presse/nyhetsrommet/derfor-trekkes-det-ikke-skatt-av-feriepengene/", "https://www.skatteetaten.no/person/skatt/hjelp-til-riktig-skatt/bank-og-lan/bsu", "https://www.nav.no/okonomi-gjeld", "https://www.forbrukerradet.no/forside/angrer-du-pa-et-kjop/", "https://www.forbrukerradet.no/klageguide/", "https://www.forbrukerradet.no/finansportalen/bank/", "https://www.norskgjeld.no/ofte-stilte-sporsmaal/", "https://lovdata.no/dokument/NL/lov/1992-07-17-99", "https://lovdata.no/dokument/NL/lov/2020-12-18-146", "https://www.okokrim.no/hvitvasking-gjennom-pengemuldyr.6267456-411472.html", "https://www.finanstilsynet.no/"], "items": [
[ "Hva er en utgift?", "Penger vi bruker, for eksempel på husleie", "Penger vi får, for eksempel lønn og trygd", "Penger vi har spart på en egen konto" ],
[ "Hva er nettolønn?", "Lønnen etter at skatten er trukket", "Lønnen før skatten er trukket", "Lønnen for overtid og arbeid i helgene" ],
[ "Hva er et budsjett?", "En plan for inntekter og utgifter", "En liste over alt du eier og skylder", "Et brev fra banken om lånet" ],
[ "Hvorfor bør et budsjett ha en sum til sparing?", "For å kunne betale uventede utgifter", "For å få lavere skatt neste år", "For å få mer barnetrygd fra Nav hver måned" ],
[ "Hva bruker norske husholdninger mest penger på?", "Bolig", "Mat", "Reiser" ],
[ "Hvem har ansvaret for økonomien i en familie?", "Begge de voksne i familien", "Den voksne som tjener mest", "Den eldste personen i familien" ],
[ "Hvordan kan en familie spare penger på klær og møbler?", "Kjøpe brukt, for eksempel hos Fretex", "Kjøpe nytt hver gang noe blir litt slitt", "Handle i butikker med høye priser" ],
[ "Hvordan kan du bruke mindre strøm hjemme?", "Slå av lyset og senke temperaturen", "Ha vinduet åpent når ovnen står på", "La TV-en og lyset stå på om natten" ],
[ "Hva trenger du for å åpne en bankkonto i Norge?", "Personnummer eller D-nummer", "Norsk statsborgerskap", "En fast jobb i en norsk bedrift" ],
[ "Hva trenger du for å logge inn i nettbanken?", "BankID eller kodebrikke", "Pass eller førerkort", "Adresse og telefonnummer" ],
[ "Hva er renter på et lån?", "Prisen du betaler for å låne penger", "Den delen av lånet du betaler ned", "Et gebyr for å åpne en bankkonto" ],
[ "Hva er et avdrag?", "Den delen av lånet du betaler ned", "Prisen du betaler for å låne penger", "Penger banken gir deg når du sparer" ],
[ "Hva viser en nedbetalingsplan?", "Hvor mye du skal betale på lånet hver gang", "Hvor mye du kan låne av banken de neste årene", "Hvor mye boligen din er verdt i dag" ],
[ "Hva viser den effektive renten på et lån?", "Hva lånet koster med renter og gebyrer", "Hvor mye du får i renter når du sparer", "Hvor lang tid du har til å betale lånet" ],
[ "Hva er et forbrukslån?", "Et lån uten sikkerhet, ofte med høy rente", "Et lån til bolig, ofte med lav rente", "Et lån fra Lånekassen til skole og studier" ],
[ "Hvorfor bør du tenke deg godt om før du tar forbrukslån?", "Renten er ofte mye høyere enn på boliglån", "Lånet må betales tilbake i løpet av en uke", "Du kan ikke ha bankkonto samtidig med lånet" ],
[ "Hva skjer hvis du ikke betaler hele kredittkortregningen?", "Du må betale høy rente på resten", "Banken sletter resten av regningen", "Du får lavere pris neste måned" ],
[ "Hva viser Gjeldsregisteret på gjeldsinformasjonen.no?", "Forbrukslån og kredittkort du har", "Boliglånet og studielånet ditt", "Regninger du har betalt i år" ],
[ "Hvor kan du få gratis råd hvis du har problemer med gjeld?", "Hos Nav", "Hos Skatteetaten", "Hos inkassobyrået" ],
[ "Ali har mye gjeld og klarer ikke å betale. Hva bør han gjøre?", "Be om hjelp tidlig, for eksempel hos Nav", "Ta opp et nytt forbrukslån for å betale", "Vente og ikke åpne brevene han får" ],
[ "Hva skjer ofte hvis du betaler en regning for sent?", "Du må betale gebyr og renter", "Regningen blir slettet etter en måned", "Nav betaler regningen for deg" ],
[ "Hva gjør et inkassobyrå?", "Krever inn penger som noen skylder", "Gir lån til folk med lav inntekt", "Hjelper folk med å lage et budsjett" ],
[ "Hva kan en person med alvorlige gjeldsproblemer søke om hos namsfogden?", "Gjeldsordning", "Bostøtte", "Startlån" ],
[ "Hva betyr det å kausjonere for et lån?", "Du lover å betale hvis låntakeren ikke kan", "Du får en del av pengene fra lånet", "Du hjelper banken med å finne nye lånekunder" ],
[ "Hva er et KID-nummer på en regning?", "Et nummer som viser hva betalingen gjelder", "Et nummer som viser hvor mye du skylder banken", "Et nummer som viser når du må betale" ],
[ "Hva er forfallsdatoen på en regning?", "Den siste dagen du kan betale", "Dagen regningen ble sendt", "Dagen du kjøpte varen" ],
[ "Hva betyr det å ha AvtaleGiro?", "Banken betaler faste regninger automatisk", "Banken gir deg lån til å betale regninger", "Butikken sender regningen i posten" ],
[ "Hva skjer hvis arbeidsgiveren ikke har skattekortet ditt?", "Arbeidsgiveren trekker 50 prosent skatt", "Du betaler ingen skatt før det kommer", "Arbeidsgiveren trekker 10 prosent skatt" ],
[ "Hvor bestiller du skattekort?", "Hos Skatteetaten", "Hos Nav", "Hos banken" ],
[ "Hva betyr det å ha frikort?", "Du betaler ikke skatt av en lav inntekt", "Du kan reise gratis med buss og tog i byen", "Du får gratis tannlege i kommunen" ],
[ "Hva er fristen for å levere skattemeldingen?", "30. april", "31. desember", "1. september" ],
[ "Hva skjer hvis du ikke leverer skattemeldingen innen fristen?", "Den regnes som levert slik den er", "Du må betale dobbelt så mye skatt", "Du får ikke lov til å jobbe mer" ],
[ "Hva viser skatteoppgjøret?", "Om du får penger igjen eller skylder", "Hvor mye lønn du skal få neste år", "Hvor mye skatt naboene dine betaler" ],
[ "Hvorfor får mange mer utbetalt i desember?", "De har bare halv skatt i desember", "Arbeidsgiveren gir julebonus til de ansatte", "Nav betaler ekstra barnetrygd før jul" ],
[ "Hva er BSU?", "Sparing til bolig for unge under 34 år", "Lån til bolig for familier med barn", "Støtte til husleie for studenter i byene" ],
[ "En ukjent vil bruke bankkontoen din mot betaling. Hva er riktig?", "Det er ulovlig, og du kan bli straffet", "Det er lov hvis dere har en skriftlig avtale", "Det er lov hvis beløpet er lite" ],
[ "Noen lover deg rask og stor gevinst hvis du investerer. Hva bør du tenke?", "Det er trolig svindel, så si nei", "Det er trygt hvis nettsiden ser fin ut", "Det er trygt hvis en venn har delt det" ],
[ "Du har kjøpt en jakke på nett. Hvor lenge har du angrerett?", "14 dager etter at du fikk varen", "3 dager etter at du bestilte", "1 måned etter at du betalte" ],
[ "Har du angrerett når du handler i en vanlig butikk?", "Nei, da gjelder butikkens egne bytteregler", "Ja, du har 14 dagers angrerett der også", "Ja, hvis du tar vare på kvitteringen og esken" ],
[ "Mobilen din får en feil etter ett år. Kan du klage til butikken?", "Ja, du kan klage i minst to år", "Nei, klagefristen er seks måneder", "Nei, du må klage innen fjorten dager" ],
[ "Hvem kan hjelpe deg hvis butikken sier nei til klagen din?", "Forbrukerrådet", "Skatteetaten", "Husbanken" ],
[ "Hvor kan du sammenligne priser på lån og sparing?", "På Finansportalen fra Forbrukerrådet", "På nettsidene til Skatteetaten", "På nettsidene til Lånekassen" ],
[ "Hva gjør Finanstilsynet?", "Passer på at banker følger reglene", "Gir boliglån til folk med lav inntekt", "Krever inn skatt fra folk som jobber" ],
[ "Du har mistet bankkortet ditt. Hva bør du gjøre?", "Sperre kortet med en gang", "Vente noen dager og se om det kommer", "Bestille nytt kort neste måned" ]
] },
{ "emne": "Bolig", "kilde": "https://samfunnskunnskap.no/nb/personlig-okonomi/bolig.html", "tillegg": ["https://lovdata.no/dokument/NL/lov/1999-03-26-17", "https://lovdata.no/dokument/NL/lov/2003-06-06-39", "https://lovdata.no/dokument/SF/forskrift/2020-12-09-2648", "https://www.regjeringen.no/no/aktuelt/utlansforskriften-senker-kravet-til-egenkapital-for-boliglan/id3077641/", "https://lovdata.no/dokument/SF/forskrift/2007-11-23-1318", "https://nef.no/slik-kjoper-du-bolig/regler-for-budgivning/", "https://www.husbanken.no/person/startlaan/soke-startlaan-og-tilskudd", "https://www.husbanken.no/person/bostotte/", "https://www.forbrukerradet.no/forside/bolig/husleie/", "https://www.forbrukerradet.no/forside/bolig/husleie/depositum/", "https://www.forbrukerradet.no/kontrakter/hus/husleiekontrakt-bokmal/", "https://www.skatteetaten.no/person/folkeregister/flytte/i-norge/", "https://www.htu.no/"], "items": [
[ "Hvor mange husholdninger i Norge eier boligen sin?", "Omtrent åtte av ti", "Omtrent fem av ti", "Omtrent tre av ti" ],
[ "Hvilken boligtype er vanligst i Norge?", "Enebolig", "Blokkleilighet", "Rekkehus" ],
[ "Hvor bor mange i store byer som Oslo?", "I blokker og bygårder", "I eneboliger med stor hage", "På gårder utenfor byen" ],
[ "Hva kjennetegner en selveierbolig?", "Du eier den og betaler alle utgiftene selv", "Du eier en andel og betaler husleie til laget", "Du leier den og betaler husleie til kommunen" ],
[ "Hva eier du når du kjøper bolig i et borettslag?", "En andel i borettslaget", "Hele bygningen og tomten", "Ingenting, du er leietaker" ],
[ "Hva dekker de månedlige felleskostnadene i et borettslag?", "Fellesgjeld, kommunale avgifter og forsikring", "Strøm, internett og mat til beboerne", "Møbler, maling og oppussing inne i leiligheten" ],
[ "Hvem må du spørre før du leier ut boligen din i et borettslag?", "Styret i borettslaget", "Kommunen der du bor", "Banken der du har lån" ],
[ "Hva eier du når du kjøper en leilighet i et sameie?", "Din egen leilighet og en del av fellesarealene", "En andel i et borettslag og del av fellesgjelden", "Ingenting, sameiet eier leilighetene" ],
[ "Hva er egenkapital?", "Penger du har spart selv", "Penger du låner i banken", "Penger du får fra kommunen" ],
[ "Hvor mye egenkapital må du vanligvis ha når du kjøper bolig?", "10 prosent av prisen", "40 prosent av prisen", "1 prosent av prisen" ],
[ "Hva krever banken før du kan få boliglån?", "Fast inntekt eller annen økonomisk trygghet", "At du har bodd og jobbet i Norge i minst ti år", "At du har norsk statsborgerskap" ],
[ "Hvor mye gjeld kan du vanligvis ha i forhold til årsinntekten?", "Opptil fem ganger årsinntekten", "Opptil to ganger årsinntekten", "Opptil tjue ganger årsinntekten" ],
[ "Hvem kan søke om startlån?", "De som ikke får vanlig lån i banken", "De som allerede eier flere boliger", "De som vil kjøpe hytte på fjellet" ],
[ "Hvor søker du om startlån?", "Hos kommunen", "Hos Skatteetaten", "Hos Forbrukerrådet" ],
[ "Hva er bostøtte?", "Hjelp til boutgifter for folk med lav inntekt", "Et rimelig lån fra banken til å kjøpe ny bolig", "Penger til å pusse opp en gammel bolig" ],
[ "Hvem har ansvaret for bostøtte?", "Husbanken, sammen med kommunen", "Nav, sammen med arbeidsgiveren", "Banken, sammen med utleieren" ],
[ "Hva betyr det at et bud på en bolig er bindende?", "Du må kjøpe hvis selgeren sier ja", "Du kan trekke budet når du vil", "Selgeren må selge til deg" ],
[ "Hva viser et finansieringsbevis fra banken?", "Hvor mye du kan låne til bolig", "Hvor mye boligen er verdt", "Hvor mye skatt du har betalt" ],
[ "Hva bør du lese før du gir bud på en bolig?", "Salgsoppgaven og tilstandsrapporten", "Lånepapirene til selgeren", "Kontrakten til de andre budgiverne" ],
[ "Hvor blir det registrert hvem som eier en bolig?", "I grunnboken hos Kartverket", "I Folkeregisteret hos Skatteetaten", "I et register hos Nav" ],
[ "Hva betaler du for med kommunale avgifter?", "Vann, avløp og søppel", "Strøm og internett", "Husleie og depositum" ],
[ "Fatima leier en leilighet. Hvilken forsikring bør hun ha selv?", "Innboforsikring for sine egne ting", "Husforsikring for selve bygningen", "Bilforsikring for utleierens bil" ],
[ "Kan du kreve en skriftlig husleiekontrakt?", "Ja, begge parter kan kreve det", "Nei, det er utleieren som bestemmer", "Nei, en muntlig avtale er nok" ],
[ "Hvor stort kan et depositum høyst være?", "Seks måneders husleie", "Tolv måneders husleie", "To års husleie" ],
[ "Hvor skal depositumet stå?", "På en egen konto i leietakerens navn", "På den private kontoen til utleieren", "Kontant hjemme hos utleieren" ],
[ "Hva er et tegn på svindel når du skal leie bolig?", "Utleieren vil ha penger før du har sett boligen", "Utleieren viser deg boligen og skriver kontrakt", "Utleieren ber om å se ID-en din på visningen" ],
[ "Hva er vanlig oppsigelsestid når du leier bolig?", "Tre måneder", "To uker", "Ett år" ],
[ "Hvor ofte kan utleieren øke husleien etter prisstigningen?", "Én gang i året", "Hver måned", "Når utleieren vil" ],
[ "Hvem skal teste røykvarsleren og bytte batteri i en leid bolig?", "Leietakeren", "Brannvesenet", "Kommunen" ],
[ "Hvem har hovedansvaret for vedlikehold av en leid bolig?", "Utleieren", "Leietakeren", "Kommunen" ],
[ "Kan en utleier si nei til deg på grunn av religionen din?", "Nei, det er forbudt", "Ja, utleieren velger fritt", "Ja, hvis det står i annonsen" ],
[ "Hvem kan hjelpe når leietaker og utleier er uenige?", "Husleietvistutvalget", "Skatteetaten", "Arbeidstilsynet" ],
[ "Hva må du gjøre når du flytter til ny adresse i Norge?", "Melde flytting til Folkeregisteret", "Sende brev til de nye naboene", "Søke om en ny bankkonto" ],
[ "Hvorfor bør du ta bilder av boligen når du flytter inn?", "For å vise skader som var der før", "For å legge dem ut på sosiale medier", "For å sende dem til Skatteetaten" ],
[ "Kan utleieren gå inn i leiligheten din uten å si fra?", "Nei, vanligvis må du få varsel først", "Ja, fordi utleieren eier boligen", "Ja, hvis du ikke er hjemme" ],
[ "Hvor lang må en tidsbestemt leiekontrakt for bolig vanligvis minst være?", "Tre år", "Tre måneder", "Én uke" ]
] }
] };
