module.exports = { tema: "Skole og utdanning", emner: [{ emne: "A2", kilde: "", items: [
["Hva ble bestemt i Norge på 1700-tallet?","At alle barn skulle gå på skole","At bare barn fra rike familier skulle gå på skole","At bare gutter skulle gå på skole"],
["Hva lærte barna på skolen på 1700-tallet?","Kunnskap om kristendommen","Hvordan man driver en gård","Hvordan man blir soldat"],
["Hvor lenge har Norge hatt skoleplikt?","I omtrent 300 år","I omtrent 100 år","I omtrent 50 år"],
["Hva lærer elevene når de bruker nettet på skolen?","Å finne god informasjon og bruke den","Å spille spill og snakke med venner","Å lese mye og lære alt utenat fra nettsider"],
["Hvem betaler mest for barnehagen?","Kommunen","Arbeidsgiveren","Fylkeskommunen"],
["Hvem har bestemt makspris for barnehage?","Stortinget","Kommunen","Fylkeskommunen"],
["Hva kalles det når du betaler mindre fordi du har flere barn i barnehagen?","Søskenmoderasjon","Barnetrygd","Kjernetid"],
["Hva kan familier med lite penger søke om i barnehagen?","Lavere pris eller gratis kjernetid","Gratis plass til søsknene deres","Penger fra barnehagen til klær og sko"],
["Hva har foreldre som ikke kan norsk rett til på foreldremøte?","Å ha med seg en tolk på møtet","Å få møtet holdt på morsmålet","Å sende en venn i stedet for seg selv"],
["Hvilke verdier bygger barnehagen på ifølge loven?","Kristne og humanistiske verdier","Verdiene til de store partiene","Verdiene som hver kommune velger"],
["Hva er viktig i barnehagen ifølge loven?","Demokrati og likestilling","Konkurranse og gode resultater","Lydighet og streng disiplin"],
["Hvor mange barn mellom 1 og 5 år går i barnehage?","De aller fleste barna","Omtrent halvparten av dem","Svært få av barna"],
["Hvordan jobber barnehagen sammen med foreldrene?","Den har foreldremøter og foreldresamtaler","Den sender karakterer hjem hver måned","Foreldrene lager planen for hver dag"],
["Hvor mange år er grunnskolen i Norge?","10 år","7 år","13 år"],
["Når begynner barn på skolen i Norge?","I august det året de blir seks år","I september det året de blir seks år","I august det året de blir sju år"],
["Hvilke trinn er barnetrinnet?","1. til 7. trinn","1. til 5. trinn","1. til 6. trinn"],
["Hva får elevene på barnetrinnet i stedet for karakterer?","En vurdering, muntlig eller skriftlig","Poeng fra 0 til 100 i hvert fag","Et diplom fra rektor hvert halvår"],
["Hvilke karakterer bruker ungdomstrinnet?","1 til 6, og 6 er best","1 til 10, og 10 er best","A til F, og A er best"],
["Hvilke fag har elevene i grunnskolen?","Matematikk, norsk, engelsk og naturfag","Jus, psykologi, filosofi og økonomi","Medisin, arkitektur og ingeniørfag"],
["Hva skjer med elevene i grunnskolen etter sommerferien?","De begynner automatisk i neste klasse","De må bestå en prøve først","Læreren må godkjenne det først"],
["Hva sier loven om å slå barn?","Det er forbudt, både hjemme og på skolen","Det er lov hjemme, men ikke på skolen","Det er lov hvis foreldrene er enige"],
["Hvilke verdier bygger grunnskolen blant annet på?","Nestekjærlighet, likeverd og solidaritet","Konkurranse, resultater og suksess","Tradisjon, orden og lydighet"],
["Hva gjelder for læreplanene i grunnskolen?","Læreplanene er like i hele landet","Hver kommune lager sin egen læreplan","Hver skole lager sin egen læreplan"],
["Hva får elever som trenger ekstra hjelp?","De får hjelp, vanligvis på sin egen skole","De må flytte til en spesialskole i en annen by","De får hjelp først på ungdomstrinnet"],
["Hva gjelder for retten til opplæring?","Alle barn har samme rett, gutter og jenter","Gutter og jenter har rett til ulike fag","Barn i byer har rett til lengre skole"],
["Har elevene skoleuniform i Norge?","Nei, elevene har ikke uniform","Ja, elevene må ha uniform","Ja, men ikke på de yngste trinnene"],
["Hvor ofte skal foreldre, elev og lærer snakke sammen om eleven?","Minst to ganger i året","Én gang hvert skoleår","Når eleven har gjort noe galt"],
["Hva heter samtalen mellom lærer, elev og foreldre?","Utviklingssamtale","Foreldremøte","Kontaktmøte"],
["Hvem har hovedansvaret for barna?","Foreldrene","Skolen","Kommunen"],
["Hva bør foreldre gjøre med informasjon fra skolen?","Lese den nøye og følge med","Lese den hvis noe er galt","La barnet lese den og svare selv"],
["Hva kan foreldre gjøre hvis de lurer på noe om skolen?","Kontakte læreren eller skolen","Vente til neste foreldremøte på skolen","Spørre vennene til barnet"],
["Hva betyr det at skolen skal være et godt sted for alle?","Alle elever skal ha det bra og bli respektert","Alle elever skal få gode karakterer","Alle elever skal like de samme tingene"],
["Hvordan lærer elevene å være med i et demokrati?","De er med og bestemmer, som i elevrådet","De bestemmer reglene selv, uten lærere","De følger reglene uten å spørre"],
["Hva forventer skolen av foreldre?","At de kommer på møter og samtaler","At de lærer barna skolefagene hjemme","At de velger lærere til barna"],
["Hvorfor jobber elevene ofte i grupper?","For å lære å samarbeide med andre","For å lære å konkurrere mot hverandre","For å lære å jobbe uten hjelp fra andre"],
["Hvem har rett til plass på videregående skole?","Elever som har fullført grunnskolen","Elever med de beste karakterene","Elever som har bodd i Norge i fem år"],
["Hva får elevene etter yrkesfaglig utdanning?","Et fagbrev eller svennebrev","Et vitnemål fra universitetet","En mastergrad fra en høgskole"],
["Hvilken utdanning er yrkesfaglig?","Utdanning som bilmekaniker","Utdanning som sykepleier","Utdanning som ingeniør"],
["Når må elevene søke videregående skole?","Før 1. mars","Før 1. mai","Før 1. juni"],
["Må studenter betale skolepenger på offentlige universiteter?","Nei, de fleste betaler bare en liten semesteravgift","Ja, alle studenter betaler mye hvert semester","Nei, kommunen betaler hele studiet for dem"],
["Når må man søke om plass på universitet eller høgskole?","Før 15. april","Før 15. mai","Før 1. juni"],
["Hva kan elever og studenter få fra Lånekassen?","Penger til studiene, som lån og stipend","Gratis bolig i hele studietiden","Lønn fra staten mens de studerer"],
["Hva er forskjellen på lån og stipend?","Lån må du betale tilbake, stipend ikke","Stipend må du betale tilbake, lån ikke","Du må betale tilbake begge deler med rente"],
["Når betaler man vanligvis tilbake lånet fra Lånekassen?","Etter at man er ferdig med å studere","Hver måned mens man fortsatt studerer","Først når man har fått fast jobb"],
["Hvilket år startet Lånekassen?","1947","1957","1974"],
["Hvorfor finnes Lånekassen?","Alle skal kunne ta høyere utdanning","De beste studentene skal få penger","Flere utenlandske studenter skal komme"],
["Kan voksne få penger fra Lånekassen til grunnskole og videregående?","Ja, voksne kan få stipend og lån","Nei, de får ikke penger til dette","Ja, men ikke hvis de er over 25 år"],
["Hva kalles det når man lærer hele livet?","Livslang læring","Fjernundervisning","Grunnopplæring"],
["Hvorfor må mange lære noe nytt i arbeidslivet?","Fordi ny teknologi endrer jobbene","Fordi loven krever nye kurs hvert år","Fordi lønnen går ned uten kurs"],
["Hvem har rett til forberedende opplæring for voksne (FOV)?","Voksne som ikke har fullført grunnskole","Voksne som har bodd i Norge i ti år","Voksne over 25 år som har jobb"],
["Hvem tilbyr grunnskole for voksne?","Kommunen","Staten","Fylkeskommunen"],
["Hva må voksne ha for å få rett til videregående opplæring?","Fullført grunnskole, i Norge eller utlandet","Minst to år med fast bosted i Norge","En bestått norskprøve på nivå B2 eller C1"],
["Er videregående skole for voksne gratis?","Ja, på de offentlige skolene","Nei, voksne må selv betale","Ja, også på de private skolene"],
["Hvor søker du om godkjenning av utdanning fra utlandet?","HK-dir","UDI","Lånekassen"],
["Hvor søker helsepersonell om godkjenning (autorisasjon)?","Helsedirektoratet","Arbeidstilsynet","Statsforvalteren"],
["Hva er realkompetansevurdering?","En vurdering av det du kan fra jobb og skole","En prøve som viser hvor mye norsk du kan","En test som viser hvilken jobb du skal ha"],
["Hvilke nivåer har norskopplæringen for voksne?","A1, A2, B1 og B2","Nivå 1, 2, 3 og 4","Lav, middels, høy og høyest"],
["Hvor lenge kan du få norskopplæring hvis du har videregående skole eller høyere utdanning?","Opptil 18 måneder","Opptil 12 måneder","Opptil 24 måneder"],
["Hvor lenge kan du få norskopplæring hvis du ikke har videregående skole?","Opptil tre år","Opptil fem år","Opptil to år"],
["Hvordan bestemmer man norskmålet ditt?","Etter utdanningen du har fra før","Etter hvor gammel du er når du søker","Etter hvilken kommune du bor i"],
["Hva betyr et felles språk for samfunnet?","Det skaper fellesskap mellom folk","Folk må mene det samme om det meste","Folk må jobbe i de samme yrkene"],
["Hva er en god måte å øve norsk på hver dag?","Å snakke norsk med naboer og kolleger","Å snakke morsmålet hjemme og på jobb","Å vente til du snakker helt riktig"],
["Hvor mange år tar grunnskole og videregående vanligvis til sammen?","13 år","10 år","16 år"],
["Hva får elevene etter studieforberedende utdanning?","Vitnemål, så de kan studere videre","Fagbrev til et praktisk yrke","Kursbevis fra et privat firma"],
["Hvor lenge har du rett til plass på videregående skole?","Til du har fullført en utdanning","Til du har gått tre år på skolen","Til du har fått jobb og bolig"],
["Hva ble en del av skolen etter hvert, i tillegg til kristendom?","Praktiske ting, som skriving og regning","Opplæring i å bruke datamaskiner","Opplæring i å lede en stor bedrift"],
["Hvilke verdier er viktige mellom elevene på skolen?","Respekt, omtanke og felles ansvar","Konkurranse, fart og høye karakterer","Lydighet, taushet og streng disiplin"],
["Hva er leirskole?","Klassen bor og lærer sammen noen dager","En ferie som skolen betaler for familien","En leir for lærere i sommerferien"],
["Hva bør foreldre gjøre hvis familien reiser til utlandet i skoletiden?","Snakke med skolen på forhånd","Reise uten å si fra til skolen","Be barnet snakke med læreren selv"],
["Hva heter 8. til 10. trinn?","Ungdomstrinnet","Mellomtrinnet","Videregående skole"],
["Hvorfor er det bra for demokratiet at folk er godt utdannet?","De kan vurdere informasjon og velge bra","Politikerne trenger ikke å forklare seg selv","Folk får samme lønn og samme jobb"],
["Hvem har ansvar for videregående opplæring for voksne?","Fylkeskommunen","Kommunen","Staten"],
["Hvordan slutter norskopplæringen?","Med en norskprøve om nivået ditt","Med en samtale med læreren om nivået","Med et kursbevis uten noen prøve"],
["Hva kan realkompetansevurdering føre til?","Kortere utdanning eller studieplass","Mindre skatt resten av livet","En gratis bolig fra kommunen"],
["Hva er HK-dir?","Direktoratet for høyere utdanning og kompetanse","En forening for lærere på videregående skole","Et firma som låner ut penger til studenter"],
["Hva er barnehage?","Et sted der små barn leker og lærer","Et sted der foreldre tar kurs","Et sted for barn som er syke"],
["Hva lærer barna i barnehagen?","Å ta hensyn til andre og klare seg selv","Å lese lange tekster og skrive stiler","Å regne med brøk og prosent i store tabeller"],
["Hva gjelder for kroppsøving i grunnskolen?","Alle elever skal delta sammen","Elevene velger selv om de deltar","Jenter og gutter har ulike regler"],
["Hvilket fag lærer elevene om samfunnet?","Samfunnsfag","Naturfag","Matematikk"],
["Hva avgjør ofte hvilken videregående skole du kommer inn på?","Karakterene fra grunnskolen","Hvem som søker først på nettet","Hvilken jobb foreldrene har"],
]}]};
