module.exports=[
["Målet er at flest mulig voksne har jobb.","Målet gjelder alle voksne, ikke bare én bransje, og ikke at voksne jobber 40 timer i uken."],
["Omtrent en tredel av dem som jobber, jobber i offentlig sektor.","Andelen er større enn en tidel, men mindre enn halvparten."],
["Staten kan gi penger til bedrifter i vanskelige tider, så de beholder jobbene.","Staten vil beholde jobber, ikke fjerne dem. Tenk på støtte i stedet for mer skatt."],
["Digitalisering gir nye jobber, og noen jobber kan forsvinne.","Teknologi endrer arbeidslivet. Det blir ikke likt som før."],
["Omtrent halvparten av arbeidstakerne er med i en fagforening.","Andelen er større enn en tidel, men mindre enn ni av ti."],
["Fagforeningen forhandler om lønn og rettigheter for medlemmene.","Fagforeningen forhandler. Den finner ikke jobber til alle og betaler ikke lønn."],
["Hvis partene ikke blir enige, kan arbeidstakerne gå ut i streik, innenfor reglene.","Arbeidstakerne har en lovlig rett her. Den handler ikke om politi eller bot."],
["Verneombudet passer på sikkerheten til de ansatte.","Verneombudet representerer de ansatte, ikke lederen."],
["Medbestemmelse betyr at de ansatte får si sin mening og være med.","Medbestemmelse betyr at flere er med å bestemme, ikke bare sjefen."],
["Når forhandlingene er ferdige, skriver partene en avtale som begge må følge.","Avtalen er bindende, og lederen kan ikke endre den alene."],
["Fagforeningene kjempet blant annet for kortere arbeidsdager.","Kortere arbeidsdager kom etter lang kamp fra arbeiderne."],
["Fagforeninger forhandler også om arbeidstid, ferie og kurs i jobben.","Fagforeninger forhandler om arbeidsforhold, ikke om skatt eller boligpriser."],
["Arbeidsmiljøloven gjelder for alle arbeidsgivere og arbeidstakere.","Loven gjelder alle arbeidsplasser, store og små."],
["Arbeidsmiljøloven har regler om ansettelse, arbeidstid og fravær.","Feriepenger og skatt har andre lover."],
["Arbeidsgiveren har hovedansvaret for arbeidsmiljøet.","Verneombudet og fagforeningen hjelper til, men hovedansvaret ligger hos en annen."],
["Du har rett til fire uker og én dag ferie.","Tenk på fire uker pluss én dag, ikke tre eller fem uker."],
["Du får feriepenger når du har ferie.","Sykepenger og dagpenger får du i andre situasjoner."],
["Feriepengene avhenger av hvor mye du tjente året før.","Feriepengene regnes ut fra inntekten din, ikke fra størrelsen på bedriften."],
["Politikerne på Stortinget bestemmer lovene.","Lovene vedtas av politikere, ikke av partene i arbeidslivet eller etatene."],
["Lover gjelder for alle, og avtaler gjelder for bestemte bransjer.","Husk: Lover gjelder bredt, avtaler er mer spesielle."],
["Arbeidstakeren skal hjelpe til med et godt arbeidsmiljø.","Arbeidstakeren er med i arbeidet, men betaler ikke for tiltakene."],
["I en velferdsstat gir staten og kommunene tjenester til innbyggerne.","Velferd betyr at fellesskapet hjelper, ikke at alle betaler alt selv."],
["Velferdssamfunnet bygger på likeverd: Alle mennesker er like viktige.","Velferd handler om at alle er like mye verdt, ikke om konkurranse."],
["Gratis sykehusopphold er en velferdsordning.","Se etter noe alle kan trenge, og som fellesskapet betaler."],
["Politikerne bestemmer velferdsordningene gjennom lover og budsjett.","Det er politikerne som bestemmer, ikke de som jobber i Nav, og ikke partene i arbeidslivet."],
["Nav gir trygd og hjelper folk å få jobb.","Lønnsforhandlinger og kontroll av arbeidsmiljø hører til andre."],
["Det finnes et Nav-kontor i alle kommuner.","Nav er lokalt og finnes over hele landet."],
["Velferdsstaten virker når mange jobber og betaler skatt.","Velferden betales av skatt fra mange, ikke bare fra bedriftene."],
["Velferdsstaten bygger i stor grad på tillit mellom staten og innbyggerne.","Systemet bygger ikke på daglig kontroll eller betaling hver gang."],
["Sykepleier på offentlig sykehus er en jobb i offentlig sektor.","Offentlig sektor betyr jobber for stat, fylke eller kommune."],
["Bruttolønn er lønnen før skatt.","Brutto er det du tjener før noe er trukket fra."],
["En lønnsslipp viser deg lønn og skattetrekk.","Lønnsslippen er til deg som ansatt, ikke til Skatteetaten eller sjefen."],
["Du får vanligvis lønn én gang i måneden, på en fast dato.","I Norge er månedslønn mest vanlig."],
["De som tjener mest, betaler mest skatt.","Skatten stiger med lønnen. Den er ikke lik for alle."],
["Arbeidsgiveren trekker skatt fra bruttolønnen.","Det er den som utbetaler lønnen som trekker skatt."],
["Si fra til Skatteetaten på nett når du får høyere lønn.","Skatt hører til Skatteetaten, ikke til Nav eller kommunen."],
["Skattemeldingen kommer hvert år i mars eller april.","Du får den én gang i året, om våren."],
["Hvis du har betalt for lite skatt, får du en regning.","Du må betale det du skylder. Lønnen din blir ikke trukket automatisk."],
["Alle ansatte har rett til en skriftlig arbeidsavtale.","Retten gjelder en avtale på papir, ikke fast jobb eller mer lønn."],
["En arbeidsavtale sier hva jobben er, hva du får i lønn og hvor mye du skal jobbe.","Avtalen handler om din egen jobb, ikke om andre ansatte eller gamle karakterer."],
["Svart arbeid er jobb uten kontrakt og uten skatt.","Svart arbeid handler om kontrakt og skatt, ikke om ulovlige varer eller farlig arbeid."],
["Når du jobber svart, får du ikke feriepenger og dagpenger.","Svart arbeid gir færre rettigheter, ikke flere."],
["For 150 år siden var jordbruk, skogbruk og fiske viktigst.","Dette var før industrien kom og før helsevesenet ble stort."],
["På slutten av 1800-tallet ble det bygd fabrikker, og mange flyttet til byene.","Folk flyttet til byene for å jobbe, ikke tilbake til gårdene."],
["Oljen ble funnet i Nordsjøen på slutten av 1960-tallet.","Funnet kom i Nordsjøen, ikke i Barentshavet eller Norskehavet."],
["Maskiner gjør at vi lager mer mat med færre bønder.","Maskiner gjør arbeidet raskere. Bøndene jobber ikke flere timer."],
["I dag er det flest jobber i serviceyrker, som butikk og helse.","Industri og olje er viktige, men det er flere jobber i service."],
["Bussjåfør er et serviceyrke fordi du hjelper andre mennesker.","Serviceyrker hjelper folk. Bonde og fisker produserer mat."],
["I 1950 jobbet mer enn 20 prosent i jordbruket.","Andelen var høy, men ikke halvparten."],
["En jobbsøknad er et brev til arbeidsgiveren om deg selv.","En søknad skriver du til arbeidsgiveren, ikke til kommunen eller Nav."],
["En CV forteller om jobbene og skolene du har hatt.","CV handler om det du har gjort, ikke om hvorfor du vil ha jobben."],
["På intervju bør du gi et fast håndtrykk og se folk i øynene.","Gode intervjuer viser interesse. Se på dem, snakk og kom i tide."],
["Søknad og CV må ha riktig norsk og riktig innhold.","Dokumentene skal være tydelige, og alt må stemme."],
["Arbeidsgiveren ser etter utdanning, erfaring, referanser og væremåte.","Alder og kjønn skal ikke avgjøre, og karakterer er ikke alt."],
["Det er ofte mange som søker på de samme jobbene.","Selv med få arbeidsledige er konkurransen stor. Du trenger fortsatt CV."],
["En referanse er en tidligere sjef som sier hvordan du jobbet.","En referanse forteller om arbeidet ditt, ikke om fritiden din."],
["Nettverket er alle du kjenner, møter og har kontakt med.","Nettverket er mer enn naboer eller kolleger i samme yrke."],
["arbeidsplassen.nav.no og finn.no brukes for å søke jobb.","Se etter nettsider med jobbannonser, ikke nettsider for politikere eller skatt."],
["Praksis og småjobber gir referanser og nettverk.","Du får nettverk ved å være blant folk, ikke bare hjemme."],
["Du kan lete etter jobb via nettverk, nett og vikarbyrå.","Skatteetaten, Lånekassen og fylkeskommunen hjelper ikke med jobbsøking."],
["Hvis du har betalt for mye skatt, får du pengene tilbake.","Du blir ikke straffet. Du får det du har betalt for mye, tilbake."],
["Kvinner jobber oftere deltid og i yrker med lav lønn.","Kvinner har lov til å jobbe i alle yrker, og de kan være med i fagforening."],
["Fagforeningen din kan forhandle om lønn for deg.","Skatteetaten og Arbeidstilsynet forhandler ikke om lønn."],
["HMS betyr helse, miljø og sikkerhet.","Tenk på tre ord som handler om å ha det trygt på jobben."],
["Arbeidsgiveren ansetter deg og betaler lønn.","Arbeidsgiveren er den du jobber for."],
["Regjeringen foreslår nye lover, og Stortinget bestemmer dem.","Forslag kommer fra dem som styrer landet, ikke fra domstolene."],
["Sosialhjelp er hjelp fra Nav når du ikke har penger.","Sosialhjelp er ikke for alle, bare for dem som trenger det."],
["Barnetrygd er penger fra staten til familier med barn.","Barnetrygden kommer fra staten til foreldrene, ikke fra skolen."],
["Dagpenger er penger fra Nav hvis du mister jobben.","Dagpenger får du når du er arbeidsledig, ikke for hver dag du jobber."],
["Pensjon er penger du får som gammel etter å ha jobbet.","Pensjon er for eldre, ikke for nye ansatte eller skolestart."],
["Staten, fylket eller kommunen er arbeidsgiver i offentlig sektor.","Offentlig sektor eies av fellesskapet, ikke av private."],
["Et vikarbyrå finner midlertidige jobber til folk.","Vikarbyråer formidler jobber. De gir ikke lån og kontrollerer ikke skatt."],
["Mellom 60 og 80 prosent av jobbene lyses ikke ut.","De fleste jobber lyses ikke ut, så tallet er høyt."],
["Både arbeidsgiveren og du kan stille spørsmål.","Intervjuet er en samtale der begge kan spørre."],
["Skriv hvorfor du passer til jobben.","Søknaden handler om deg og jobben, ikke om ferie eller politikk."],
["Streik betyr at de ansatte stopper arbeidet for å få endring.","Det er de ansatte som streiker, ikke sjefen. Det er ikke ferie."],
["Grønne jobber er bra for klima og miljø.","Grønn jobb betyr miljøvennlig, ikke bare jobb ute i naturen."],
["En arbeidstaker jobber for en bedrift.","En arbeidstaker er den som er ansatt, ikke eier eller leder av en fagforening."],
["Deltakere i introduksjonsprogrammet får introduksjonsstønad.","Stønaden gis til dem som deltar i introduksjonsprogrammet."],
["IT er en næring som får flere jobber.","Fabrikker, jordbruk og skogbruk får færre jobber."],
];
