module.exports=[["Riktig. Bærekraftig utvikling betyr at vi får dekket behovene våre i dag, uten å ødelegge mulighetene for generasjonene som kommer etter oss.","Tenk på barna og barnebarna våre. De skal også ha en god jord å leve på."],
["Riktig. Begrepet ble kjent i hele verden på slutten av 1980-årene, gjennom en rapport fra FN.","Begrepet kom med en stor FN-rapport. Den kom ut mot slutten av 1900-tallet, ikke etter år 2000."],
["Riktig. Kommisjonen ble ledet av den tidligere norske statsministeren Gro Harlem Brundtland. Derfor kalles den ofte Brundtlandkommisjonen.","Kommisjonen er oppkalt etter lederen sin, som var en tidligere norsk statsminister."],
["Riktig. Brundtlandkommisjonen ble startet av FN i 1983 og la fram rapporten sin i 1987.","Kommisjonen ble startet i 1983 og brukte noen år på arbeidet. Rapporten kom i samme tiår."],
["Riktig. FNs bærekraftsmål er en felles plan for hele verden. Målet er å utrydde fattigdom, bekjempe ulikhet og stoppe klimaendringene.","Bærekraftsmålene gjelder ikke bare ett land eller én del av verden. De gjelder alle land."],
["Riktig. FN har 17 bærekraftsmål. Til sammen har de 169 delmål.","Antallet er mellom 10 og 20. Hvert mål har også flere delmål."],
["Riktig. FNs medlemsland vedtok bærekraftsmålene i 2015.","Målene er ganske nye. De ble vedtatt mange år etter Brundtland-rapporten."],
["Riktig. Planen er at bærekraftsmålene skal være nådd innen 2030.","Målene skal nås i løpet av omtrent 15 år etter at de ble vedtatt i 2015."],
["Riktig. Bærekraft handler om tre ting som henger sammen: klima og miljø, økonomi og sosiale forhold.","Bærekraft handler om naturen, om penger og arbeid, og om hvordan menneskene har det."],
["Riktig. Mål nummer 1 er å utrydde fattigdom i hele verden.","Det første målet handler om folk som har for lite penger til mat, bolig og klær."],
["Riktig. Likestilling mellom kjønnene er bærekraftsmål nummer 5.","Bærekraftsmålene handler om å gjøre livet bedre for mennesker og natur, ikke om å bruke mer."],
["Riktig. Bærekraftsmålene gjelder alle land, og både stater, næringsliv og vanlige mennesker skal bidra.","Målene er en felles plan. Alle har en rolle, både land, bedrifter og hver enkelt av oss."],
["Riktig. Klima er gjennomsnittet av været målt over lang tid. Været er det vi opplever hver dag.","Vær og klima er ikke det samme. Det ene er det du ser ute i dag, det andre måles over mange år."],
["Riktig. De fleste klimaforskere mener at menneskenes utslipp av karbongasser er årsaken til de store og raske endringene.","Forskerne mener at det er noe vi mennesker gjør som er hovedårsaken."],
["Riktig. Når kloden blir varmere, stiger havet og blir surere. Isen smelter også.","Når isen smelter, blir det mer vann i havet. Havet tar også opp mye CO₂."],
["Riktig. Ekstremvær er svært kraftig vær, for eksempel storm, flom, tørke eller ekstrem hete. Det blir mer av det med klimaendringene.","«Ekstrem» betyr veldig mye eller veldig sterk. Tenk på vær som kan gjøre stor skade."],
["Riktig. Klimagasser, for eksempel CO₂, holder på varmen rundt jorda. Mer klimagasser gjør jorda varmere.","Klimagasser er knyttet til at temperaturen på jorda stiger."],
["Riktig. Karbondioksid (CO₂) er den klimagassen mennesker slipper ut mest av, blant annet fra olje, gass og kull.","Denne gassen kommer når vi brenner olje, gass, kull og ved."],
["Riktig. En fornybar ressurs fornyer seg selv. Hvis vi bruker den riktig, blir den ikke brukt opp.","«Fornybar» betyr at noe kan komme tilbake igjen og igjen, som vind og regn."],
["Riktig. Vind er en fornybar ressurs. Den tar ikke slutt selv om vi bruker den.","Olje og kull har blitt laget i bakken over millioner av år. Når de er brukt, er de borte."],
["Riktig. Naturgass er ikke fornybar. Når den er brukt, er den borte, akkurat som olje og kull.","Sol og regn kommer tilbake hele tiden. Tenk på hva vi henter opp fra bakken under havet."],
["Riktig. Hvis vi bruker en fornybar ressurs raskere enn naturen klarer å fornye den, kan den likevel bli borte.","Tenk på fisk eller skog. Naturen trenger tid for å lage nytt."],
["Riktig. Kortreist mat er produsert i nærheten av forbrukeren, altså der du bor.","«Kortreist» betyr at maten ikke har reist langt for å komme til deg."],
["Riktig. Når maten er produsert lokalt, trengs det mindre transport. Da blir det mindre klimagassutslipp.","Tenk på hvor langt maten må fraktes med bil, båt eller fly."],
["Riktig. Med lokal mat er det lettere å kontrollere sprøytemidler, bruk av antibiotika og dyrenes levekår.","Når maten blir laget i nærheten, er det lettere å se hvordan den blir laget."],
["Riktig. Et land som er selvforsynt, produserer nok mat selv og trenger ikke å kjøpe mat fra andre land.","«Selv» og «forsyne» betyr at landet klarer seg med det det lager selv."],
["Riktig. Å sykle, gå eller reise kollektivt gir mindre utslipp enn å kjøre bil.","Tenk på hva som gir minst forurensning og bruker minst ressurser."],
["Riktig. I Parisavtalen fra 2015 ble landene i verden enige om å begrense den globale oppvarmingen.","Parisavtalen er en klimaavtale mellom nesten alle land i verden."],
["Riktig. Norge har blitt rikt fordi landet har mange naturressurser, og fordi folk har lært å bruke dem godt.","Rikdommen i Norge kommer fra naturen, for eksempel fra havet, skogen og fossene."],
["Riktig. De viktigste naturressursene i Norge er fisk, skog og olje. I tillegg har vi mye vann som gir strøm.","Tenk på havet, de store skogene og det som blir hentet opp i Nordsjøen."],
["Riktig. Det meste av strømmen i Norge kommer fra vannkraft, altså vann i elver og fosser.","Norge har mange fosser og elver. Vannet blir brukt til å lage strøm."],
["Riktig. De senere årene har Norge også begynt å lage strøm med vindmøller.","Denne energikilden er fornybar. Den bruker luft som beveger seg."],
["Riktig. Det trengs mye strøm for å lage aluminium. Vannkraften gjør det mulig å produsere mye metall i Norge.","Å lage metall krever mye energi. Tenk på hva Norge har mye av."],
["Riktig. Tømmer blir blant annet brukt til papir og bygningsmaterialer. Noe blir også eksportert.","Tømmer er tre fra skogen. Tenk på hva vi kan lage av tre."],
["Riktig. Havbruk eller oppdrett betyr at fisk, særlig laks, vokser opp i store merder i sjøen.","Oppdrett er ikke vanlig fiske. Fisken blir født og vokser opp i anlegg."],
["Riktig. Myndighetene bestemmer kvoter, altså hvor mye fisk som kan fiskes. Da blir ikke fisken i havet brukt opp.","Fisk er en fornybar ressurs, men bare hvis vi ikke fisker for mye."],
["Riktig. I Statens pensjonsfond utland sparer staten inntektene fra olje og gass. Fondet eies av staten.","Navnet sier at det er statens fond. Pengene kommer fra olje- og gassvirksomheten."],
["Riktig. Handlingsregelen sier at staten over tid skal bruke omtrent den forventede avkastningen av fondet, som i dag er anslått til 3 prosent.","Staten bruker bare en liten del av fondet hvert år, slik at fondet varer."],
["Riktig. Olje og gass tar slutt en gang. Ved å spare pengene i et fond kan også de som kommer etter oss, få glede av dem.","Olje er ikke fornybar. Tenk på bærekraft og generasjonene som kommer etter oss."],
["Riktig. Naturen er også en ressurs. Turister kommer fra hele verden for å se fjordene og midnattssola.","Tenk på hva som er spesielt med naturen i Norge, særlig langs kysten og i nord."],
["Riktig. Allemannsretten betyr at alle kan ferdes fritt i naturen, for eksempel gå på tur, gå på ski og telte i utmark.","Allemannsretten gir rett til å ferdes i naturen, ikke til å eie eller ta fra naturen."],
["Riktig. Utmark er udyrket mark, som strand, myr, skog og fjell. Der kan du ferdes fritt.","Utmark er natur der ingen dyrker jorda eller bor. Hager og åkre er innmark."],
["Riktig. En åker er innmark. Der kan du ikke gå om sommeren uten lov fra eieren.","Allemannsretten gjelder fritt i utmark. Dyrket mark, hager og gårdsplasser er innmark."],
["Riktig. Du kan ikke sette opp telt nærmere enn 150 meter fra et hus eller en hytte der folk bor.","Folk som bor i huset eller hytta, skal få være i fred. Det må være god avstand."],
["Riktig. Du kan telte på samme sted i to døgn. Vil du være lenger, må du som regel spørre grunneieren. På høyfjellet langt fra hus kan du være lenger.","Det er en kort periode. Grunneieren skal ikke få noen på eiendommen lenge uten å bli spurt."],
["Riktig. Fra 15. april til 15. september er det forbudt å tenne bål i eller nær skog. Det gjelder også grill, så sjekk reglene i kommunen.","Om sommeren er det ofte tørt i skogen, og det kan lett bli skogbrann. Da gjelder et forbud."],
["Riktig. Bålforbudet gjelder fra 15. april til 15. september, fordi det da er stor fare for skogbrann.","Forbudet varer i omtrent fem måneder, fra midt i april til midt i september."],
["Riktig. Når du bruker allemannsretten, må du rydde etter deg, ikke skade dyr eller natur og være forsiktig med ild.","Rettigheter gir også plikter. Tenk på hvordan naturen skal se ut når du går hjem."],
["Riktig. De fleste steder kan du plukke bær, sopp og blomster i utmark.","Du kan ta med deg det naturen gir hvert år, men du må ikke skade trær eller dyr."],
["Riktig. Voksne trenger som regel fiskekort for å fiske i elver og innsjøer. Barn under 16 år kan ofte fiske gratis.","Det er grunneieren som har retten til fisken i elver og vann. Du kjøper en tillatelse."],
["Riktig. I sjøen kan du som hovedregel fiske med stang eller snøre uten fiskekort.","Reglene er forskjellige for ferskvann og saltvann. Tenk på havet."],
["Riktig. For å jakte må du blant annet ha bestått jegerprøven og ha lov fra den som eier jakten, som regel grunneieren.","Jakt er ikke en del av allemannsretten. Du må ha en egen prøve og lov fra eieren."],
["Riktig. Fra 1. april til 20. august må hunder holdes i bånd i hele landet. Da får ville dyr og fugler fred mens de får unger.","Båndtvangen gjelder om våren og sommeren, når dyrene får unger og sauene går ute."],
["Riktig. Det er som hovedregel forbudt å kjøre motorkjøretøy i utmark. Du trenger tillatelse.","Allemannsretten gjelder ferdsel til fots, på ski og på sykkel. Motorer kan skade og forstyrre naturen."],
["Riktig. Natur- og miljøvern handler om å ta vare på naturen og økosystemene, og om å reparere skader som mennesker har laget.","«Vern» betyr å beskytte. Målet er at mennesker, dyr og planter skal ha et godt livsmiljø."],
["Riktig. Gjenbruk betyr at ting du ikke trenger lenger, blir brukt på nytt av andre.","Når noe blir smeltet om eller tatt fra hverandre, er det gjenvinning. Gjenbruk er noe annet."],
["Riktig. Gjenvinning betyr at ting blir tatt fra hverandre til råvarer, eller smeltet om til nye produkter.","Når andre bruker tingen din slik den er, kalles det gjenbruk. Gjenvinning er noe annet."],
["Riktig. Når du kjøper brukt, trengs det ikke å lages en ny jakke. Det sparer ressurser, og det er ofte billigere.","Tenk på hva som trengs for å lage nye klær: råvarer, vann, energi og transport."],
["Riktig. Kildesortering betyr at du sorterer søppelet ditt, for eksempel matavfall, papir, plast og restavfall.","Ordet «sortere» betyr å dele inn i grupper. Ulikt søppel skal i ulike dunker."],
["Riktig. Hver innbygger i Norge kaster flere hundre kilo søppel i året.","Det er mye mer enn det mange tror, men ikke så mye som et tonn."],
["Riktig. Store ting som møbler, vaskemaskiner og malingsspann kan du levere på en gjenvinningsstasjon.","Store ting får ikke plass i søppeldunken. Mange kommuner har egne steder for dette."],
["Riktig. Flasker og bokser med pantemerke kan du levere i en panteautomat. Da får du pengene tilbake.","Når du kjøper drikke, betaler du litt ekstra. Du får pengene tilbake i butikken."],
["Riktig. Med pant kommer nesten alle flaskene og boksene tilbake, og materialet kan brukes på nytt.","Pant er en måte å få folk til å levere tomme flasker tilbake, slik at de kan gjenvinnes."],
["Riktig. Batterier og maling er farlig avfall. Du kan levere dem på gjenvinningsstasjonen, og batterier også i butikker som selger dem.","Noe søppel kan skade naturen og mennesker. Det skal ikke kastes sammen med vanlig søppel."],
["Riktig. Butikker som selger elektronikk, må ta imot gammel elektronikk av samme type gratis.","Elektronikk skal ikke i vanlig søppel. Du kan levere den der slike varer blir solgt."],
["Riktig. Matsvinn er når mat som kunne vært spist, blir kastet eller brukt til noe annet enn menneskemat.","«Svinn» betyr at noe går tapt. Tenk på mat som havner i søppelet."],
["Riktig. I verden blir omtrent en tredjedel av all maten kastet. Det ville vært nok til å gi mat til alle som sulter.","Det er mye mat som blir kastet, mer enn hver tiende matvare, men mindre enn halvparten."],
["Riktig. «Best før» betyr at kvaliteten er garantert til datoen. Maten er ofte god etterpå. Bruk sansene: se, lukt og smak. «Siste forbruksdag» er strengere.","«Best før» handler om kvalitet, ikke om fare. Den strenge merkingen heter «siste forbruksdag»."],
["Riktig. Hvis du planlegger hva du skal kjøpe og spiser opp restene, kaster du mindre mat.","Tenk på hvorfor mat havner i søppelet: vi kjøper for mye og glemmer restene."],
["Riktig. De største utslippene i Norge kommer fra olje- og gassutvinning, industri og bergverk og veitrafikk.","Tenk på den største næringen i Norge til havs."],
["Riktig. Utslippene av klimagasser i Norge har gått ned de siste årene, men ikke like mye hvert år.","Utslippene har endret seg, men de har ikke økt de siste årene."],
["Riktig. En nullutslippsbil, for eksempel en elbil, slipper ikke ut klimagasser når den kjører.","«Null utslipp» betyr at ingenting kommer ut av eksosrøret. En bil med diesel slipper ut gass."],
["Riktig. I 2024 var det for første gang flere elbiler enn bensinbiler registrert i Norge.","Det har blitt veldig mange elbiler i Norge de siste årene."],
["Riktig. Målet er at flere reiser i de store byene skal skje med kollektivtransport, sykkel eller gange, slik at biltrafikken ikke øker.","Målet er at biltrafikken i byene ikke skal øke, selv om det blir flere innbyggere."],
["Riktig. En nasjonalpark er et stort naturområde som er vernet, slik at naturen blir tatt vare på. Norge har mange nasjonalparker.","Nasjonalparker ligger ute i naturen, ofte på fjellet. Naturen der er beskyttet."],
["Riktig. I nasjonalparker kan du gå på tur, fiske med fiskekort og overnatte i telt. Bygging og motorkjøring er som regel forbudt.","Nasjonalparker er laget for at naturen skal få være i fred, men folk kan fortsatt bruke den til friluftsliv."],
["Riktig. Isbjørnen har vært fredet siden 1973. Det betyr at det er forbudt å jakte på den.","«Fredet» betyr at dyret er beskyttet av loven."],
["Riktig. Miljødirektoratet er en statlig etat som jobber for å ta vare på naturen og passer på at miljølovene blir fulgt.","Navnet sier det: dette er statens etat for miljø."],
["Riktig. Det er forbudt å kaste søppel i naturen. Det kalles forsøpling, og du kan få bot.","Du må ta med deg søppelet ditt hjem eller kaste det i en søppeldunk. Det gjelder overalt."],
["Riktig. Fisk, fugler og andre dyr kan spise plast og bli syke eller dø.","Plast blir ikke borte i naturen. Tenk på dyrene som lever i havet."]];
