module.exports=[["Riktig. Demokrati betyr folkestyre. Folket bestemmer gjennom valg.","Ordet har to deler på gresk: «folk» og «styre». Tenk på hvem som har makten."],
["Riktig. Folket velger representanter fra partiene til Stortinget, fylkestinget og kommunestyret.","Norge har et representativt demokrati. Folket velger politikere som bestemmer for dem."],
["Riktig. Flertallet bestemmer, men skal ta hensyn til mindretallets meninger.","I et demokrati vinner flertallet, men de som er færre, skal også bli hørt."],
["Riktig. Staten setter rammer, men kommunene bestemmer selv i en del saker.","Kommunene har selvbestemmelse i noen saker. Men det er en større myndighet som setter rammene."],
["Riktig. Staten har ansvar for sykehusene, lover, utenrikspolitikk og læreplaner.","Barnehager har kommunen ansvar for, og fylkesveier har fylkeskommunen ansvar for."],
["Riktig. Fylkeskommunen har ansvar for fylkesveier og videregående opplæring.","Navnet på veien gir et hint. Kommunen har ansvar for de kommunale veiene."],
["Riktig. Byråkratene er de ansatte. De gjør det politikerne har bestemt, for eksempel på Nav.","Politikerne bestemmer, og de ansatte i det offentlige gjør jobben i praksis."],
["Riktig. Stortinget er nasjonalforsamlingen og den øverste statsmakten.","Regjeringen foreslår lover, men det er nasjonalforsamlingen som vedtar dem."],
["Riktig. Folket velger 169 representanter til Stortinget for fire år om gangen.","Stortinget har litt mer enn 150 representanter. Tallet er det samme etter hvert valg."],
["Riktig. Grunnloven sier at Stortinget sitter i fire år. Det er ikke mulig å skrive ut nyvalg.","I Norge kan verken kongen eller regjeringen oppløse Stortinget. Valget skjer hvert fjerde år."],
["Riktig. Stortinget vedtar lover og statsbudsjettet og kontrollerer regjeringen.","Domstolene dømmer, og statsrådene leder departementene. Stortinget har andre oppgaver."],
["Riktig. Stortinget passer på at regjeringen gjør jobben sin og følger vedtakene.","Kontroll betyr å følge med og passe på. Stortinget gjør dette med regjeringen."],
["Riktig. Demokratiet er åpent. Alle kan høre på, men publikum kan ikke snakke i salen.","Stortingsmøtene er åpne for publikum. Men bare representantene kan snakke i debatten."],
["Riktig. På en høring kan fagmiljøer og vanlige folk si hva de mener om et forslag.","En høring er en måte å samle meninger på før politikerne bestemmer."],
["Riktig. Regjeringen lager forslaget, og Stortinget vedtar statsbudsjettet.","Stortinget vedtar budsjettet, men det er en annen statsmakt som lager forslaget."],
["Riktig. Regjeringen består av statsministeren og statsrådene, som leder hvert sitt departement.","Stortingsrepresentantene sitter i nasjonalforsamlingen. Regjeringen er noe annet."],
["Riktig. Møtet heter statsråd. Statsrådene informerer kongen om politiske saker.","Ordet er det samme som tittelen på dem som leder et departement."],
["Riktig. Norge har en konge, men det er folkevalgte politikere som styrer landet.","Kongen har liten politisk makt i Norge. Makten ligger hos de folkevalgte."],
["Riktig. Makten er delt mellom Stortinget, regjeringen og domstolene.","Maktfordeling handler om de tre statsmaktene. Ingen av dem skal få for stor makt alene."],
["Riktig. Domstolene dømmer i rettssaker etter lovene som Stortinget har vedtatt.","Stortinget vedtar lovene, men det er en annen statsmakt som dømmer i rettssaker."],
["Riktig. Regjeringen er den utøvende makten. Den sørger for at lovene blir gjennomført.","Stortinget lager lovene, og domstolene dømmer. Regjeringen setter lovene ut i livet."],
["Riktig. Parlamentarisme betyr at regjeringen må ha Stortingets tillit for å sitte.","I Norge velger folket Stortinget, ikke regjeringen. Regjeringen er avhengig av Stortinget."],
["Riktig. Regjeringen må gå av hvis flertallet på Stortinget sier at det ikke har tillit til den.","Dette er parlamentarisme. Regjeringen trenger tillit fra Stortinget for å kunne sitte."],
["Riktig. Etter valget danner ett eller flere partier en ny regjering.","Det er de politiske partiene som danner regjering, ut fra resultatet på Stortinget."],
["Riktig. I et demokrati har vi både frihet og rettigheter, og ansvar og plikter.","Frihet og rettigheter hører sammen med noe du må gjøre for samfunnet."],
["Riktig. Ytringsfriheten gjelder både privatpersoner og radio, tv og aviser.","Pressen er fri i Norge. Mediene trenger ikke tillatelse fra staten for å skrive."],
["Riktig. Valgloven sier at den som blir valgt, har plikt til å ta imot valget. Bare noen få kan få fritak.","Å være folkevalgt er en plikt, ikke bare en rettighet. Det finnes bare noen få unntak."],
["Riktig. Ærekrenkelse er ikke straffbart siden 2015, men retten kan kreve at du betaler erstatning.","Du får ikke fengsel for ærekrenkelse i dag. Men å skade andres rykte kan likevel koste penger."],
["Riktig. Å stemme er en rettighet. Ingen kan tvinge deg til å stemme.","I Norge er det frivillig å stemme. Lav valgdeltakelse er likevel et problem for demokratiet."],
["Riktig. Rettssikkerhet betyr blant annet at ingen kan dømmes til fengsel uten en rettssak først.","I et demokrati er det uavhengige dommere som avgjør skyld og straff, ikke politiet."],
["Riktig. Alle tiltalte har rett til et forsvar, for eksempel en advokat.","Rettssikkerhet gjelder for alle. Den tiltalte får hjelp til å forsvare seg i retten."],
["Riktig. Det er påtalemyndigheten som må bevise at personen er skyldig, ikke den tiltalte.","Ingen skal straffes før det er bevist at personen har gjort noe galt."],
["Riktig. Grunnloven sier at domstolene og dommerne skal være uavhengige og upartiske.","Dommerne skal dømme etter loven. Regjeringen og partiene kan ikke bestemme utfallet."],
["Riktig. Du har rett til å være med i partier, foreninger og fagforeninger.","Organisasjonsfrihet handler om å få være med i grupper uten å bli straffet."],
["Riktig. Myndighetene stoler på innbyggerne, og innbyggerne stoler på myndighetene.","Tillit betyr å stole på noen. «Gjensidig» betyr at det går begge veier."],
["Riktig. Du har plikt til å gi riktige og sanne opplysninger til Nav og andre etater.","Samfunnet bygger på tillit. Nav må kunne stole på det du forteller."],
["Riktig. Alle som har inntekt eller formue over visse grenser, må betale skatt i Norge.","Skatteplikten handler om inntekt og formue, ikke om statsborgerskap."],
["Riktig. Alle har plikt til å møte som vitne og forklare seg for retten når de blir innkalt.","Vitneplikt betyr at du må komme når retten kaller deg inn. Det er ikke frivillig."],
["Riktig. Norge har allmenn verneplikt for kvinner og menn født i 1997 eller senere.","Siden 2015 har verneplikten vært lik for begge kjønn i Norge."],
["Riktig. Barn har plikt til grunnskoleopplæring, vanligvis i en offentlig skole.","Plikten gjelder barn i grunnskolealder. De fleste går på en offentlig og gratis skole."],
["Riktig. Du må følge loven, men du kan jobbe for å endre den på demokratisk vis.","I et demokrati må vi følge reglene flertallet har vedtatt, også når vi er uenige."],
["Riktig. Når få stemmer, blir demokratiet svakere.","Frie medier og mange partier styrker demokratiet. Tenk på hva som skjer hvis få deltar."],
["Riktig. Loven sier at du må hjelpe en person i fare, eller ringe etter hjelp.","Alle har hjelpeplikt. Du må hjelpe hvis du kan gjøre det uten stor fare for deg selv."],
["Riktig. Når du flytter, må du melde flytting til Folkeregisteret innen åtte dager.","Folkeregisteret hos Skatteetaten må vite hvor du bor. Du trenger ikke lov til å flytte."],
["Riktig. En meddommer er en vanlig person som dømmer sammen med en fagdommer.","Også vanlige innbyggere er med og dømmer i norske domstoler. De kalles meddommere."],
["Riktig. Alle kan be om innsyn i dokumenter fra stat og kommune, med noen unntak.","Det offentlige skal være åpent. Du kan be om å få se saksdokumenter."],
["Riktig. Menneskerettighetene er universelle. De gjelder for alle mennesker i hele verden.","Universell betyr «for alle». Menneskerettighetene gjelder uansett land og alder."],
["Riktig. Vi har menneskerettighetene fordi vi er mennesker.","Menneskerettighetene avhenger ikke av hvor du bor, eller hvem du er."],
["Riktig. FNs verdenserklæring om menneskerettighetene ble vedtatt i 1948.","FN ble grunnlagt i 1945. Erklæringen kom noen år senere, etter andre verdenskrig."],
["Riktig. FN har 193 medlemsland. Alle har sluttet seg til verdenserklæringen.","Nesten alle land i verden er med i FN. Tallet er under 200."],
["Riktig. Erklæringen ble vedtatt 10. desember 1948. Derfor er det menneskerettighetenes dag.","17. mai er nasjonaldagen i Norge, og 24. oktober er FN-dagen."],
["Riktig. Tortur i alle former er forbudt, også i krig.","Forbudet mot tortur har ingen unntak. Det gjelder i alle situasjoner."],
["Riktig. Grunnloven § 93 sier at ingen kan dømmes til døden.","Norge har ikke dødsstraff. Det står i Grunnloven."],
["Riktig. I 2014, da Grunnloven fylte 200 år, fikk den et nytt kapittel om menneskerettigheter.","Endringen kom da Grunnloven hadde 200-årsjubileum."],
["Riktig. Menneskerettsloven sier at konvensjonene i loven går foran andre lover hvis de sier ulike ting.","Menneskerettsloven gjør viktige konvensjoner til norsk lov. De har sterk stilling."],
["Riktig. EMK er en avtale i Europarådet om menneskerettigheter. Den er norsk lov.","EMK handler om menneskerettigheter, ikke handel. Norge er med selv om Norge ikke er med i EU."],
["Riktig. Når saken er ferdig i norske domstoler, kan du klage til Den europeiske menneskerettsdomstolen i Strasbourg.","Det finnes en egen domstol for EMK. Den ligger i Frankrike."],
["Riktig. NIM følger med og gir råd, men behandler ikke enkeltsaker.","NIM er knyttet til Stortinget. Institusjonen dømmer ikke, men overvåker og informerer."],
["Riktig. Alle har rett til å påvirke politikken gjennom frie, hemmelige valg.","Menneskerettighetene handler om frihet, sikkerhet og deltakelse, ikke om ting eller penger."],
["Riktig. Alle mennesker er født frie, med samme menneskeverd og rettigheter.","Erklæringen sier at alle har samme verd fra de blir født."],
["Riktig. Sivilombudet er Stortingets ombud. Du kan klage dit hvis du mener det offentlige har gjort feil mot deg.","Det finnes et ombud som Stortinget har valgt, og som passer på hele forvaltningen, ikke bare én gruppe."],
["Riktig. Loven gjelder likt for alle. Ingen skal få usaklig forskjellsbehandling.","«Like for loven» betyr at penger og makt ikke gir deg andre regler."],
["Riktig. Det er lokalvalg to år etter et stortingsvalg. Det er valg annethvert år.","Det er valg annethvert år. Stortingsvalg og lokalvalg bytter på."],
["Riktig. Stortingsvalg er hvert fjerde år, så neste valg er i 2029.","Stortinget blir valgt for fire år. Regn fire år fram fra 2025."],
["Riktig. Programmet viser hvilke saker partiet vil jobbe med de neste fire årene.","Partiprogrammet er en plan for politikken i valgperioden."],
["Riktig. Partiene vedtar programmet sitt på landsmøtet.","Landsmøtet er det øverste møtet i et parti. Der vedtar medlemmene politikken."],
["Riktig. De som har stemmerett ved stortingsvalg, kan bli valgt til Stortinget.","For å bli valgt til Stortinget må du ha stemmerett, altså være norsk statsborger og minst 18 år i valgåret."],
["Riktig. De største partiene kan grovt plasseres fra sosialistisk til borgerlig.","Partiene kan plasseres på en politisk skala, fra venstre til høyre."],
["Riktig. Valget er hemmelig, og alle bestemmer selv hvilket parti de stemmer på.","Det er vanlig at folk i samme familie stemmer på ulike partier."],
["Riktig. Stortingsvalget holdes på en mandag i september, hvert fjerde år.","Valget er om høsten, like etter sommerferien."],
["Riktig. Du har stemmerett hvis du fyller 18 år senest i løpet av valgåret.","Det holder at du blir 18 år i løpet av det året valget er."],
["Riktig. Ved stortingsvalg er listene lukket. Kandidatene blir valgt i den rekkefølgen partiet har satt.","Etter valgloven som gjelder fra 2024, kan du ikke endre stemmeseddelen ved stortingsvalg."],
["Riktig. Du kan gi personstemme med et kryss ved kandidater du vil støtte.","Personstemmer gir du til personer på stemmeseddelen ved kommunestyrevalg og fylkestingsvalg."],
["Riktig. Ved kommunestyrevalg kan du skrive inn navn fra andre partiers lister.","En slenger er en personstemme til en kandidat som står på en annen liste."],
["Riktig. Et parti må få minst fire prosent i hele landet for å få utjevningsmandater.","Sperregrensen gjelder utjevningsmandatene. Den regnes ut fra stemmene i hele landet."],
["Riktig. Utjevningsmandater gjør at antall seter passer bedre med stemmene i hele landet.","Hvert valgdistrikt har ett utjevningsmandat. Det gjør fordelingen av setene rettere."],
["Riktig. Når flere partier sitter sammen i regjering, kalles det en koalisjonsregjering.","Koalisjon betyr samarbeid mellom flere partier."],
["Riktig. En mindretallsregjering har ikke flertall og må få støtte fra andre partier.","Mindretall betyr at man er færre enn halvparten på Stortinget."],
["Riktig. Opposisjonen er partiene som ikke sitter i regjering.","Disse partiene følger med på regjeringen og foreslår annen politikk."],
["Riktig. Partiene velger selv kandidatene sine på nominasjonsmøter.","Hvert parti lager sin egen liste. Medlemmene er med og bestemmer."]];
