module.exports=[["Riktig. Norge har grense mot Sverige, Finland og Russland.","Danmark og Island ligger ved havet. Norge har grense mot tre land, og ett av dem ligger lengst øst i nord."],
["Riktig. Fra 1. januar 2024 har Norge 15 fylker. Før det var det 11 fylker.","Antallet fylker ble endret 1. januar 2024. Noen store fylker ble delt opp igjen."],
["Riktig. Norge har 357 kommuner. Mange kommuner ble slått sammen i 2020.","Norge har mer enn 300 kommuner, men færre enn 400."],
["Riktig. Omtrent tre av fire innbyggere bor langs kysten.","De fleste i Norge bor nær havet. Store fjell- og skogområder har nesten ingen innbyggere."],
["Riktig. Omtrent halvparten av befolkningen bor på Østlandet, der Oslo ligger.","Tenk på landsdelen rundt hovedstaden. Der bor flest mennesker."],
["Riktig. Lindesnes er det sørligste punktet på fastlandet. Der står det et kjent fyr.","Det sørligste punktet ligger på Sørlandet. Nordkapp ligger helt i nord."],
["Riktig. Svalbard er en øygruppe langt mot nord, og den hører til Norge.","Svalbard ligger i havet langt nord for fastlandet. Det er ikke et fylke."],
["Riktig. Mjøsa er Norges største innsjø. Den ligger på Østlandet.","Glomma er en elv, og Sognefjorden er en fjord. Spørsmålet gjelder en innsjø."],
["Riktig. En isbre er et stort område med is og snø som ligger der hele året. Jostedalsbreen er den største.","En isbre finnes høyt oppe i fjellet. Isen ligger der også om sommeren."],
["Riktig. Bare omtrent tre prosent av Norge er dyrket mark. Det meste er fjell og skog.","Norge har mye fjell og skog. Det er lite jord der man kan dyrke mat."],
["Riktig. Golfstrømmen tar med seg varmt vann fra sør opp langs norskekysten.","Grunnen er havet. En varm havstrøm kommer fra sør og går langs kysten."],
["Riktig. Midnattssol betyr at sola er oppe hele døgnet om sommeren i nord.","Midnattssola gjør sommeren i Nord-Norge lys. Tenk på hva sola gjør om natten da."],
["Riktig. Bokmål og nynorsk er to måter å skrive norsk på. Begge er offisielle.","Det handler om hvordan man skriver norsk. Norsk har to offisielle skriftspråk."],
["Riktig. Norsk og samisk er offisielle språk, og loven sier at de er likeverdige.","Det ene språket er norsk. Det andre er språket til urfolket i Norge."],
["Riktig. Folketallet øker fordi folk flytter hit, og fordi det blir født flere enn det dør.","Det bor stadig flere mennesker i Norge. Mange flytter hit fra andre land."],
["Riktig. Norge er et monarki. Tittelen går i arv fra forelder til barn.","Kongen eller dronningen blir ikke valgt. Tittelen går videre i familien."],
["Riktig. Likeverd betyr at alle har like stor verdi, uansett kjønn, alder, bakgrunn eller legning.","Likeverd handler om verdien til hvert menneske, ikke om penger eller tro."],
["Riktig. Norskopplæring for innvandrere er et eksempel på at samfunnet gir like muligheter.","Samfunnet prøver å gi alle en god start. Tenk på et tilbud som hjelper nye i Norge."],
["Riktig. Likestilling gjelder også mellom generasjoner, religioner, etniske grupper og folk med ulik funksjonsevne.","Likestilling handler om viktige sider ved et menneske, som alder, tro og helse. Ingen skal behandles dårligere for det."],
["Riktig. Nesten like mange kvinner som menn er i jobb i Norge i dag.","De fleste kvinner i Norge har jobb. Antallet er nesten likt med menn."],
["Riktig. Nesten to av tre ledere i arbeidslivet er menn.","Det er fortsatt flest menn i ledende stillinger, selv om mange kvinner jobber."],
["Riktig. Kvinner velger oftere omsorg og undervisning. Menn velger oftere teknikk og naturfag.","Mange velger fortsatt på en tradisjonell måte. Tenk på yrker som sykepleier og lærer."],
["Riktig. Undersøkelser viser at kvinner fortsatt bruker mer tid på husarbeid enn menn.","Mange par deler mer nå enn før, men det er ikke helt likt ennå."],
["Riktig. Den som jobber deltid, tjener mindre. Det kan gi lavere pensjon senere.","Deltid gir mindre lønn. Tenk på hva det betyr for pengene du får når du blir gammel."],
["Riktig. Hver familie bestemmer selv hvordan de deler oppgavene hjemme.","Arbeidet hjemme er en sak for familien selv. Men alle må følge loven."],
["Riktig. § 185 forbyr hatefulle eller diskriminerende ytringer, for eksempel om hudfarge, religion eller legning.","I Norge er det lov å kritisere politikere. Paragrafen gjelder hat mot grupper av mennesker."],
["Riktig. Rasismeparagrafen skal beskytte minoriteter mot hat og diskriminering.","Paragrafen begrenser ytringsfriheten litt for å verne grupper som lett blir utsatt for hat."],
["Riktig. Loven forbyr diskriminering på grunn av blant annet alder, kjønn, etnisitet og religion.","Loven skal hindre at noen blir behandlet dårligere. Alder er ett av grunnlagene i loven."],
["Riktig. Diskrimineringsnemnda behandler klager på diskriminering. Det er gratis å klage. Ombudet kan gi råd først.","Det finnes en egen nemnd som avgjør saker om diskriminering. Navnet sier hva den jobber med."],
["Riktig. Kvinner og menn skal ha lik lønn for samme arbeid, eller arbeid av lik verdi.","Prinsippet handler om kjønn. En kvinne skal ikke tjene mindre enn en mann for den samme jobben."],
["Riktig. Arbeidsgiveren har ikke lov til å spørre om graviditet eller planer om å få barn.","Loven beskytter jobbsøkere. Arbeidsgiveren skal ikke spørre om familieplaner."],
["Riktig. Universell utforming betyr at bygg og tjenester er laget slik at flest mulig kan bruke dem.","Det handler om at også folk med for eksempel rullestol eller dårlig syn skal komme fram."],
["Riktig. 1. nyttårsdag er en helligdag. Butikkene er stengt, og mange har fri.","Den første dagen i året er en fridag for de fleste. Butikkene har ikke åpent."],
["Riktig. Samefolkets dag er offisiell flaggdag, men ikke fridag.","Denne dagen heiser mange flagg, men folk går på jobb og skole som vanlig."],
["Riktig. 8. mars er den internasjonale kvinnedagen. Noen går i tog for kvinners rettigheter.","Datoen handler om kvinners rettigheter. Mange går i tog og holder appeller."],
["Riktig. Kvinnedagen ble markert første gang i 1915, og hvert år siden 1972.","Kvinnedagen ble markert første gang i 1915. Men den ble ikke markert hvert år før i 1970-årene."],
["Riktig. Påsken er en kristen høytid til minne om at Jesus døde og sto opp igjen.","Jesu fødsel feires i julen. Påsken handler om slutten av Jesu liv."],
["Riktig. Skjærtorsdag, langfredag, 1. påskedag og 2. påskedag er helligdager.","Helligdagene i påsken starter på torsdagen og slutter på mandagen etter påskedag."],
["Riktig. Kristi himmelfartsdag er alltid en torsdag, 40 dager etter påske.","Dagen kommer om våren, en stund etter påske. Den er alltid på en torsdag."],
["Riktig. Pinsen kommer ti dager etter Kristi himmelfartsdag.","Det er litt over en uke mellom Kristi himmelfartsdag og pinsen."],
["Riktig. På arbeidernes dag går mange i tog og viser hvilke politiske saker de er opptatt av.","1. mai handler om arbeidere og politikk. Barnetog med skolen hører til 17. mai."],
["Riktig. 17. mai er først og fremst barnas dag, med barnetog, flagg, is og pølser.","På nasjonaldagen går barnehager og skoler i tog. Det er barna som står i sentrum."],
["Riktig. På julaften spiser mange julemiddag sammen med familien og gir hverandre gaver.","Julaften er en familiefest 24. desember. Raketter hører til nyttårsaften."],
["Riktig. 1. og 2. juledag er helligdager. Julaften og nyttårsaften er ikke helligdager.","Helligdagene i julen er de to dagene rett etter julaften."],
["Riktig. Konfirmasjon er en markering for ungdom rundt 15 år, i kirken eller borgerlig.","Konfirmasjon er en tradisjon for unge i tenårene. Det er ikke dåp eller bryllupsdag."],
["Riktig. Skolen lærer elevene om religioner og tradisjoner, men ingen trenger å tro på dem.","Å lære om en tradisjon er ikke det samme som å tro. Det er religionsfrihet i Norge."],
["Riktig. Majoriteten er den største gruppen. I Norge har de fleste norsk familiebakgrunn.","Majoritet betyr flertall. Det motsatte er minoritet, som er en mindre gruppe."],
["Riktig. Nasjonale minoriteter er grupper som har bodd i Norge i flere hundre år.","En nasjonal minoritet er ikke nyankomne innvandrere. Gruppen har bodd her svært lenge."],
["Riktig. De fem er jøder, kvener/norskfinner, rom, romanifolk/tatere og skogfinner.","Det er flere enn to, men færre enn ti. Samene regnes som urfolk, ikke som nasjonal minoritet."],
["Riktig. Kvener/norskfinner er en nasjonal minoritet. Det er også jøder, rom, romanifolk/tatere og skogfinner.","De nasjonale minoritetene har bodd i Norge i flere hundre år. Nyere innvandrergrupper er ikke med."],
["Riktig. Kvensk, romani og romanes er nasjonale minoritetsspråk i Norge.","Dette er språk som noen av de nasjonale minoritetene snakker. De er ikke samiske."],
["Riktig. Norge lovet å legge til rette for at minoritetene kan bevare språk, religion og kultur.","Avtalen handler om kultur, språk og tradisjoner. Staten skal hjelpe gruppene å ta vare på dem."],
["Riktig. Mer enn én million i Norge er innvandrere eller har to foreldre som er innvandrere.","Det er mange, men langt fra halvparten av de omtrent 5,6 millioner innbyggerne."],
["Riktig. Polen er landet flest innvandrere i Norge kommer fra. Ukraina og Litauen følger etter.","Den største gruppen kommer fra et land i Europa. Mange kom for å jobbe."],
["Riktig. En norskfødt med innvandrerforeldre er født i Norge, og begge foreldrene er født i utlandet.","Personen er født i Norge selv. Det er foreldrene som har flyttet hit."],
["Riktig. Det bor innvandrere i alle kommuner, men flere bor i byene enn på landsbygda.","Innvandrere bor over hele landet. Mange velger byene, blant annet fordi det er lettere å finne jobb."],
["Riktig. Målet er at innvandrere kan bruke ressursene sine og bidra på lik linje med andre.","Integrering handler om å delta i fellesskapet. Ingen skal måtte gi opp sin egen kultur."],
["Riktig. Gode norskkunnskaper er en av nøklene til integrering.","Det som hjelper mest, er å kunne snakke med folk. Tenk på hva du lærer på kurs nå."],
["Riktig. Et sekulært samfunn er ikke styrt av religion, verken i lovene eller i hverdagen.","Sekulær betyr at religion ikke styrer samfunnet. Det er religionsfrihet i Norge."],
["Riktig. Omtrent åtte av ti gravferder skjer i Den norske kirke, også for mange som ikke er religiøse.","Mange bruker kirken ved viktige hendelser i livet. Gravferd i kirken er svært vanlig."],
["Riktig. Grunnloven kaller Den norske kirke Norges folkekirke. Staten støtter den, men den er ikke statskirke.","Norge har ikke lenger statsreligion. Grunnloven bruker et annet ord om kirken i dag."],
["Riktig. Omtrent seks av ti er medlem av Den norske kirke. Andelen går ned år for år.","Mange er medlem, men færre enn før. Det er litt mer enn halvparten."],
["Riktig. Den norske kirke er evangelisk-luthersk. Det er en protestantisk kirke.","Den norske kirke er protestantisk. Retningen har navn etter Martin Luther."],
["Riktig. Jonas bestemmer selv. Alle i Norge har rett til å bytte religion.","Det er full religionsfrihet i Norge. Ingen andre kan bestemme hva du tror på."],
["Riktig. Godkjente tros- og livssynssamfunn får like mye støtte per medlem som Den norske kirke.","Støtten følger antall medlemmer. Det gjelder alle godkjente samfunn, ikke bare kristne."],
["Riktig. Et livssynssamfunn samler folk rundt et livssyn uten religion, som humanismen.","Human-Etisk Forbund er ikke en kirke eller et parti. Medlemmene har et livssyn uten gud."],
["Riktig. Islam er den største religionen i Norge etter kristendommen.","Etter kristendommen er det en religion med omtrent 200 000 medlemmer i trossamfunn i Norge."],
["Riktig. Fra 1845 kunne nordmenn melde seg ut av statskirken. Før det var det forbudt.","Før 1845 måtte alle nordmenn være medlem av statskirken. Tenk på hva som da ble lov."],
["Riktig. For mange er bryllup i kirken en tradisjon, selv om de ikke er religiøse.","Det er lov å gifte seg hos kommunen. Mange velger kirken fordi det er en tradisjon."],
["Riktig. De fleste i Norge ser på religion som en privatsak.","Mange i Norge snakker lite om sin egen tro med folk de ikke kjenner godt."],
["Riktig. Samene er urfolk fordi de bodde i området lenge før dagens landegrenser ble laget.","Urfolk har bodd i et område lenge før staten og grensene kom. Samene er den eldste folkegruppen i Norge."],
["Riktig. Samene bor i Norge, Sverige, Finland og Russland.","Samene bor i nord i fire land. Danmark og Island er ikke blant dem."],
["Riktig. Det første samiske landsmøtet var i Trondheim 6. februar 1917. Derfor er samefolkets dag 6. februar.","Datoen for samefolkets dag kommer fra et viktig møte i 1917. Sametinget åpnet først i 1989."],
["Riktig. Kofte er en samisk folkedrakt. Den brukes ved fest, og noen bruker den til hverdags.","Kofte er noe man har på seg. Mange samer bruker den i for eksempel bryllup."],
["Riktig. Joik er en gammel samisk måte å synge på.","Joik har med musikk og stemme å gjøre. Det er ikke mat eller dans."],
["Riktig. Samisk og norsk er helt forskjellige språk. Det finnes også flere samiske språk.","Samisk er ikke en dialekt. Den som bare kan norsk, forstår ikke samisk."],
["Riktig. Fornorsking betyr at staten prøvde å gjøre samene norske, blant annet ved å ta fra barna språket.","Fornorsking var en politikk fra staten. Samiske barn fikk ikke lære samisk på skolen."],
["Riktig. I 1959 ble det igjen tillatt å bruke samisk i skolen.","Det tok lang tid før samisk igjen ble tillatt i skolen. Det skjedde etter andre verdenskrig."],
["Riktig. Sametinget åpnet i 1989 og jobber for samenes rettigheter, kultur, språk og utdanning.","Sametinget er samenes eget folkevalgte organ. Det jobber med saker som gjelder samene."],
["Riktig. For å stemme må du stå i Sametingets valgmanntall. Det er valg hvert fjerde år.","Det finnes et eget register for dem som kan stemme ved sametingsvalget. Du må melde deg inn."]];
