module.exports=[["Riktig. Alle som bor i et demokrati, har ansvar for at demokratiet skal fungere.","Demokratiet er ikke bare politikernes ansvar. Alle innbyggere har et ansvar."],
["Riktig. Alle kan foreslå en sak i sin egen kommune. Du trenger ikke stemmerett eller være 18 år.","Et innbyggerforslag krever ikke stemmerett. Også unge og utenlandske statsborgere kan lage et forslag."],
["Riktig. Fra 2007 til 2011 økte valgdeltakelsen blant de yngste velgerne med mer enn ti prosent.","Unge nordmenn er mer politisk aktive enn før. Flere unge stemmer ved valg nå."],
["Riktig. De politiske ungdomsorganisasjonene har fått flere medlemmer.","Unge er mer politisk aktive enn før. Derfor har ungdomsorganisasjonene fått flere medlemmer."],
["Riktig. I en organisasjon trener du på diskusjoner, styrearbeid, valg og avstemninger.","Som medlem i en organisasjon er du med på møter, diskusjoner og valg av styre."],
["Riktig. Underskriftskampanjer, demonstrasjoner og diskusjoner på sosiale medier er uformell deltakelse.","Uformell deltakelse skjer utenfor partiene. Et eksempel er å skrive under for en sak."],
["Riktig. Å fremme saker i et parti eller delta i valgkamp er formell politisk deltakelse.","Formell deltakelse skjer gjennom partiene og valgene, for eksempel i et politisk parti."],
["Riktig. Å være politisk engasjert er å bry seg om samfunnet og delta, for eksempel i debatter eller valg.","Du trenger ikke være politiker for å være engasjert. Det handler om å bry seg og delta."],
["Riktig. I en demonstrasjon samles folk, ofte ute, for å vise hva de mener om en sak.","En demonstrasjon er en måte å vise meningen sin på. Folk samles for eksempel i en gate."],
["Riktig. Den som vil ha en demonstrasjon på et offentlig sted, skal melde fra til politiet i god tid.","Du trenger ikke lov fra politikerne. Men du må melde fra til politiet på forhånd."],
["Riktig. I en underskriftskampanje skriver mange navnet sitt for å vise at de støtter en sak.","En underskriftskampanje samler navn fra folk som er enige i en sak."],
["Riktig. Kari kan skrive et innlegg i avisen. Hun kan også kontakte politikere eller samle underskrifter.","Kari må følge loven. Hun kan bli hørt på lovlige måter, for eksempel i avisen."],
["Riktig. Et leserinnlegg er en tekst der en leser skriver hva han eller hun mener om en sak.","I et leserinnlegg skriver vanlige lesere sin mening. Nyheter blir skrevet av journalister."],
["Riktig. En interesseorganisasjon er en gruppe som jobber for en sak som medlemmene bryr seg om.","En interesseorganisasjon er ikke en del av kommunen. Den jobber for en felles sak."],
["Riktig. Du melder deg inn i partiet og betaler en medlemsavgift. Partiene har ulike regler, men det er lett å melde seg inn.","Det er lett å bli medlem i et parti. Du melder deg inn og betaler en avgift."],
["Riktig. Mange partier har en ungdomsorganisasjon der unge medlemmer diskuterer og jobber politisk.","En politisk ungdomsorganisasjon hører til et parti. Der er unge politisk aktive."],
["Riktig. Etter tre år i Norge kan utenlandske statsborgere stemme ved kommunestyrevalg og fylkestingsvalg.","Ved stortingsvalg må du være norsk statsborger. Ved lokalvalg kan du stemme etter tre år i Norge."],
["Riktig. Du må ha vært registrert som bosatt i Norge de tre siste årene før valgdagen.","Regelen er tre år. Statsborgere fra de andre nordiske landene har en egen, enklere regel."],
["Riktig. Det er kommunestyrevalg hvert fjerde år, to år etter stortingsvalget.","Kommunestyrevalg og fylkestingsvalg er hvert fjerde år, samme dag i hele landet."],
["Riktig. Ved kommunestyrevalget velger innbyggerne politikerne som skal styre kommunen.","Kommunestyret er politikerne som styrer kommunen. De blir valgt av innbyggerne."],
["Riktig. Politikere som innbyggerne har valgt, bestemmer for eksempel hvor mye penger bussene får.","Mye i hverdagen er politikk. Det er de folkevalgte politikerne som bestemmer til slutt."],
["Riktig. Valget er hemmelig. Du stemmer alene, og ingen ser hva du stemmer.","Ingen skal se hva du stemmer, heller ikke partiene. Du kan selv velge om du vil fortelle det."],
["Riktig. Du må vise legitimasjon når du stemmer, for eksempel pass eller førerkort.","Når du stemmer, må du vise hvem du er. Ta med legitimasjon med bilde."],
["Riktig. Ali kan forhåndsstemme. Da stemmer han i ukene før valgdagen.","Du kan ikke stemme etter valget eller la andre stemme for deg. Men du kan stemme før valgdagen."],
["Riktig. Du må ha stemmerett ved lokalvalget og bo i kommunen. Da kan du stille til valg.","Du trenger ikke være partimedlem eller norsk statsborger. Du må ha stemmerett og bo i kommunen."],
["Riktig. Hvis nok innbyggere skriver under, må kommunestyret behandle forslaget.","Et innbyggerforslag kommer fra innbyggerne. Med nok underskrifter må kommunestyret behandle saken."],
["Riktig. På minsak.no kan du foreslå en sak og samle underskrifter.","Nettstedet for innbyggerforslag heter minsak.no. Der kan du også skrive under på andres forslag."],
["Riktig. I ungdomsrådet kan unge si sin mening om saker i kommunen.","Kommunen har et ungdomsråd eller noe lignende. Der får unge si sin mening til politikerne."],
["Riktig. I valgkampen forteller partiene velgerne hva de vil gjøre hvis de blir valgt.","Valgkampen er før valget. Da prøver partiene å få folk til å stemme på dem."],
["Riktig. Politikk påvirker mye i hverdagen, som skatt, busser og barnehager.","Politikere bestemmer ikke hva du skal mene. Men politikk påvirker mye i livet ditt."],
["Riktig. I Norge blir folk oppmuntret til å engasjere seg politisk.","I Norge er det positivt å engasjere seg. Alle får ha og si sine meninger."],
["Riktig. Du kan engasjere deg på mange måter, også uten å være med i et parti.","Du trenger ikke være med i et parti. Du kan for eksempel skrive i avisen eller skrive under for en sak."],
["Riktig. Dugnad er frivillig, ubetalt arbeid som blir gjort i et fellesskap.","På dugnad får du ikke lønn. Folk jobber sammen frivillig."],
["Riktig. Dugnad er en gammel skikk i Norge.","Dugnad er ikke nytt. Folk i Norge har hatt dugnad i flere hundre år."],
["Riktig. Dugnad er ikke bare norsk. De fleste landbrukssamfunn i verden har en lignende tradisjon.","Mange land har en tradisjon der folk hjelper hverandre med arbeid. Det er ikke bare i Norge."],
["Riktig. I 2004 ble dugnad kåret til Norges nasjonalord.","Dugnad er et viktig ord i Norge. Det ble kåret til nasjonalord i 2004."],
["Riktig. Vafler og kaffe er typisk dugnadsmat i Norge.","På en norsk dugnad er det ofte vafler med syltetøy og kaffe."],
["Riktig. Om våren har mange borettslag dugnad for å gjøre det pent ute etter vinteren.","Vårdugnaden handler om å rydde og gjøre det fint ute når vinteren er over."],
["Riktig. På dugnad i barnehagen vasker foreldrene for eksempel leker eller fikser uteområdet.","De ansatte lager planer og betaler regninger. Foreldrene hjelper til med praktiske ting."],
["Riktig. Foreldre lager ofte loppemarked for å få inn penger til foreningen.","Pengene fra et loppemarked går til foreningen, for eksempel et idrettslag eller et korps."],
["Riktig. På et loppemarked blir brukte ting solgt. Folk gir ofte tingene gratis til foreningen.","På et loppemarked kjøper du brukte ting, for eksempel klær, leker og bøker."],
["Riktig. Mange fritidsaktiviteter for barn blir drevet av foreldrene på dugnad.","Mange idrettslag og korps har ikke mange ansatte. Foreldrene gjør mye av arbeidet frivillig."],
["Riktig. Dugnad er frivillig, men de fleste føler at de bør delta. Det blir forventet.","Ingen lov sier at du må delta. Men folk forventer at du er med."],
["Riktig. Alle får nytte av det dugnaden lager. Derfor synes mange at alle bør hjelpe til.","Det er ikke ulovlig å la være. Men mange synes det tar seg dårlig ut."],
["Riktig. Det er lurt å si fra og tilby å hjelpe en annen gang.","Det er høflig å si fra hvis du ikke kan komme. Da vet de andre det."],
["Riktig. Noen lag lar foreldrene betale et beløp i stedet for å delta på dugnad.","Noen lag har en ordning der du kan betale penger hvis du ikke vil være med på dugnaden."],
["Riktig. På dugnad blir du kjent med naboer og andre, og du får et større nettverk.","Du får ikke penger for dugnad. Men du kan bli kjent med mange nye mennesker."],
["Riktig. Ordet dugnad kommer fra et gammelt norrønt ord som betyr «hjelp, støtte».","Ordet dugnad er gammelt. Det betydde opprinnelig hjelp og støtte."],
["Riktig. Før i tiden hjalp folk hverandre på dugnad med store jobber, som å bygge hus og legge tak.","Før i tiden var dugnad vanlig for store, praktiske jobber som var vanskelige å gjøre alene."],
["Riktig. Idrettslag, borettslag og fritidsaktiviteter for barn har ofte dugnad.","Dugnad er vanlig i lag og foreninger, ikke i bedrifter."],
["Riktig. Dugnad er vanlig i lag og foreninger, ikke på arbeidsplasser der folk får lønn.","På jobben får du lønn for arbeidet. Dugnad er frivillig arbeid i lag og foreninger."],
["Riktig. I et borettslag er det vanligvis styret som kaller inn til dugnad.","Borettslaget organiserer dugnaden selv. Det er ikke kommunen eller politiet som gjør det."],
["Riktig. Når medlemmene gjør jobben gratis, trenger ikke laget å betale andre for den.","Dugnad er ubetalt. Laget sparer penger fordi folk jobber frivillig."],
["Riktig. På vårdugnaden raker folk ofte løv, plukker søppel og planter blomster.","Vårdugnaden handler om å rydde og gjøre det pent ute, i fellesområdene."],
["Riktig. Barn er ofte med på dugnad sammen med de voksne.","Dugnad er for hele familien. Barn kan gjerne være med og hjelpe."],
["Riktig. Hvis du aldri kommer, kan andre bli irritert. Du blir også mindre kjent med folk.","Det er ikke straff for å la være. Men andre kan synes det tar seg dårlig ut."],
["Riktig. En sosial arena er et sted der mennesker møtes for å være sammen.","Sosiale arenaer er steder der folk møtes, for eksempel skolen, jobben eller et kor."],
["Riktig. Arbeidsplassen er en viktig sosial arena for mange voksne.","En sosial arena er et sted der du møter andre mennesker, for eksempel på jobben."],
["Riktig. Korps er en organisert fritidsaktivitet. Idrettslag og speideren er andre eksempler.","En organisert aktivitet har en leder og faste tider, for eksempel korps eller fotball."],
["Riktig. Når barna er med på aktiviteter, kan foreldrene bli kjent med folk i nærmiljøet.","Foreldre møter ofte andre foreldre på barnas aktiviteter. Slik blir de kjent med folk."],
["Riktig. Foreldre bytter ofte på å kjøre og hente barna til aktivitetene.","Mange foreldre hjelper til i barnas aktiviteter, for eksempel med kjøring."],
["Riktig. Frivillige får ikke lønn for arbeidet.","Det viktigste med frivillig arbeid er at du ikke får lønn."],
["Riktig. Frivillig arbeid går over kortere perioder. Ingen jobber full tid som frivillig.","Frivillig arbeid er ikke en fulltidsjobb. De fleste gjør det noen timer i blant."],
["Riktig. Røde Kors er en frivillig organisasjon. Mange jobber der som frivillige.","Skatteetaten og Nav er offentlige kontorer med ansatte. Røde Kors har mange frivillige."],
["Riktig. Mange frivillige organisasjoner sier sin mening og påvirker politikken, lokalt og nasjonalt.","Organisasjonene vedtar ikke lover. Men de kan påvirke politikerne."],
["Riktig. Som frivillig kan du lære nye ting, få nye venner og et større nettverk.","Frivillige får ikke lønn. Men de får nye venner og blir kjent med folk."],
["Riktig. En uskreven regel er en regel som alle kjenner, men som ikke er skrevet ned.","Uskrevne regler står ikke i loven. Folk lærer dem ved å se hva andre gjør."],
["Riktig. Uskrevne regler er forskjellige fra kultur til kultur.","Hver kultur har sine egne uskrevne regler, også Norge."],
["Riktig. I Norge er det vanlig å håndhilse, både for kvinner og menn.","Når vi møter noen første gang i Norge, tar vi hverandre i hånden."],
["Riktig. Venner sier ofte «hei», gir en klem eller slår hverandre lett på skulderen.","Venner hilser ofte enkelt, for eksempel med «hei» eller en klem."],
["Riktig. Et vanlig svar er «Takk, bare bra. Og med deg?»","Spørsmålet er en vanlig hilsen. Folk svarer ofte kort og spør tilbake."],
["Riktig. I Norge er det vanlig å invitere til en bestemt dag og tid.","Nordmenn kommer sjelden på besøk uten avtale. Du må invitere til en bestemt dag."],
["Riktig. Nordmenn går sjelden på besøk uten at det er avtalt på forhånd.","I Norge er det vanlig å avtale besøk før du kommer."],
["Riktig. «Takk for sist» sier du når du møter noen du har vært sammen med før.","Når du møter noen du har vært sammen med nylig, sier du ofte «Takk for sist»."],
["Riktig. På folkebiblioteket kan du låne bøker gratis. Det er også en møteplass.","Biblioteket selger ikke bøker. Du låner dem gratis, og du kan møte andre der."],
["Riktig. Ifølge loven skal alle kommuner i Norge ha et folkebibliotek.","Folkebibliotek finnes ikke bare i byene. Alle kommuner skal ha et."],
["Riktig. Målet er at alle barn kan være med på minst én organisert fritidsaktivitet.","Fritidserklæringen handler om at alle barn skal få være med, uansett hvor mye penger familien har."],
["Riktig. En frivilligsentral er en lokal møteplass som skaffer frivillige oppgaver.","På frivilligsentralen kan du bli frivillig. Du får ikke lønn eller fast jobb der."],
["Riktig. I et lag eller en forening blir du kjent med folk der du bor.","Det er lettere å bli kjent med folk hvis du er med i en aktivitet sammen med dem."],
["Riktig. Et barn som ikke får være med der vennene er, kan føle seg utenfor.","Fritidsaktiviteter er viktige for vennskap. Barn som ikke er med, kan føle seg alene."]];
