module.exports=[["Riktig. En husholdning er personer som bor i samme bolig og har felles økonomi.","En husholdning handler om å bo i samme bolig og ha felles økonomi. Slekt eller naboer er ikke nok."],
["Riktig. En kjernefamilie er foreldre og barna deres. Det kan være én eller to foreldre.","Kjernefamilien er den minste familien: foreldre og barn. Tanter, onkler og besteforeldre hører til storfamilien."],
["Riktig. I en storfamilie bor flere generasjoner sammen, for eksempel besteforeldre, foreldre og barn.","En storfamilie handler ikke om stort hus eller venner. Det er flere generasjoner i samme familie som bor sammen."],
["Riktig. I Norge i dag kan en kjernefamilie være to mødre eller to fedre med barn, eller en mor eller far alene med barn.","En kjernefamilie er foreldre og barn. I Norge kan foreldrene være to av samme kjønn."],
["Riktig. I en norsk husholdning bor det i gjennomsnitt litt mer enn to personer.","Norske husholdninger er små. Mange bor alene, og gjennomsnittet er litt mer enn to personer."],
["Riktig. Omtrent sju av ti par som bor sammen, er gift. De andre er samboere.","De fleste par som bor sammen, er gift. Omtrent tre av ti er samboere."],
["Riktig. Siden 2009 har to av samme kjønn hatt rett til å gifte seg i Norge.","Loven om ekteskap ble lik for alle par i 2009. Siden da kan to kvinner eller to menn gifte seg."],
["Riktig. Omtrent fire av ti som gifter seg, vil sannsynligvis skille seg senere.","Skilsmisse er ganske vanlig i Norge. Omtrent 40 prosent av dem som gifter seg, skiller seg senere."],
["Riktig. Et par kan gifte seg hos kommunen. Det kalles borgerlig vielse. De kan også gifte seg i et tros- eller livssynssamfunn.","Det er ikke Nav eller politiet som vier par. Et par som ikke vil ha religiøs vielse, kan gifte seg hos kommunen."],
["Riktig. Ektefeller har plikt til å forsørge hverandre. Det betyr at de skal hjelpe hverandre økonomisk.","Loven sier ikke noe om religion eller hvor man skal bo. Ektefeller har plikt til å forsørge hverandre."],
["Riktig. Når et ektepar tar opp et lån sammen, er begge ansvarlige for lånet.","Det spiller ingen rolle hvem som tjener mest eller er eldst. Når begge har tatt opp lånet, er begge ansvarlige."],
["Riktig. Barn som er født fra og med 2020, får i utgangspunktet felles foreldreansvar. Det gjelder også når foreldrene ikke er gift.","Foreldre har i utgangspunktet felles foreldreansvar for barn som er født fra og med 2020, også når de ikke er gift."],
["Riktig. Foreldreansvar betyr at foreldrene har rett og plikt til å ta avgjørelser for barnet i personlige spørsmål.","Foreldreansvar handler om å ta avgjørelser for barnet og gi god omsorg. Ingen kan bestemme hvem et barn skal gifte seg med."],
["Riktig. Når man er separert, er man fortsatt gift, men man bor ikke lenger sammen. Separasjon kommer ofte før skilsmisse.","Separert betyr at paret fortsatt er gift, men har flyttet fra hverandre. Det er ofte et steg før skilsmisse."],
["Riktig. Hovedregelen er at man må være separert i minst ett år før man kan be om skilsmisse.","Tiden er kortere enn tre år. Vanligvis må man være separert i ett år før skilsmisse."],
["Riktig. Hvis det har vært vold i ekteskapet, eller ekteskapet var tvang, kan man få skilsmisse med en gang.","Krangel eller flytting gir ikke skilsmisse med en gang. Vold eller tvang i ekteskapet kan gi skilsmisse med en gang."],
["Riktig. Foreldre med felles barn under 16 år må gå til mekling før separasjon eller skilsmisse. Meklingen er gratis.","Foreldre med barn under 16 år skal først gå til mekling, for eksempel på familievernkontoret."],
["Riktig. Målet med mekling er at foreldrene blir enige om det som er best for barna, for eksempel om bosted og samvær.","Mekling handler ikke om skyld eller hus. Den skal hjelpe foreldrene å bli enige om ordninger for barna."],
["Riktig. Familievernkontoret hjelper par og familier. Det er gratis, og du trenger ikke henvisning fra lege.","Par som krangler mye, kan få samtaler på et familievernkontor. Det er gratis."],
["Riktig. Etter en skilsmisse har både moren og faren plikt og rett til omsorg for barnet.","Hus og penger bestemmer ikke hvem som skal gi omsorg. Både mor og far har plikt og rett til omsorg."],
["Riktig. Delt bosted betyr at barnet bor omtrent like mye hos mor og hos far.","Delt bosted betyr at barnet har to faste hjem. Barnet bor omtrent halve tiden hos hver av foreldrene."],
["Riktig. Barnebidrag er penger som forelderen som barnet ikke bor fast hos, betaler for barnet.","Barnebidrag kommer ikke fra skolen eller banken. Det er penger fra forelderen som barnet ikke bor fast hos."],
["Riktig. Samboere har ikke automatisk de samme økonomiske og juridiske rettighetene som ektepar.","Samboere og ektepar har ikke like rettigheter automatisk. Derfor skriver mange samboere en avtale."],
["Riktig. Samboere har ikke automatisk de samme rettighetene som ektepar. Derfor skriver mange avtaler om arv og deling av verdier.","Samboere trenger ikke tillatelse for å bo sammen eller få barn. Avtalen handler om arv og verdier hvis forholdet slutter."],
["Riktig. I kulturen lærer vi hvordan vi skal leve sammen, og hva som er riktig og galt.","Kulturen bestemmer ikke jobb eller lønn. Den lærer oss hvordan vi skal leve sammen med andre."],
["Riktig. Barn lærer både av foreldrene og av samfunnet rundt seg.","Barn lærer ikke mest fra bøker eller bare fra slekta. De lærer både av foreldrene og samfunnet rundt."],
["Riktig. For å forstå kulturforskjeller kan vi dele kulturer i jeg-kulturer og vi-kulturer.","De to gruppene heter jeg-kulturer og vi-kulturer. I den ene er enkeltmennesket viktigst, i den andre gruppa."],
["Riktig. Inndelingen er en forenkling. Den gjør det lettere å forstå forskjeller, men ingen kultur er bedre enn en annen.","Modellen er en enkel måte å forstå forskjeller på. Den sier ikke at én kultur er best."],
["Riktig. I en jeg-kultur er enkeltmennesket viktigst.","Jeg-kultur betyr at enkeltmennesket, «jeg», er viktigst. I en vi-kultur er gruppa viktigst."],
["Riktig. I en vi-kultur er gruppa viktigst, for eksempel familien.","Vi-kultur betyr at gruppa, «vi», er viktigere enn hver enkelt person."],
["Riktig. Selvstendighet, likeverd og likestilling er eksempler på positive verdier i en jeg-kultur.","Lydighet og respekt er typiske verdier i vi-kulturer. I jeg-kulturer er selvstendighet og likestilling viktig."],
["Riktig. Lydighet, respekt og gode relasjoner er eksempler på positive verdier i en vi-kultur.","Selvstendighet og likestilling er typisk for jeg-kulturer. I vi-kulturer er lydighet, respekt og gode relasjoner viktig."],
["Riktig. Å være selvstendig betyr å klare seg selv og ta egne valg.","Selvstendig betyr ikke å følge andre. Det betyr å klare seg og bestemme selv."],
["Riktig. Barn med to kulturer kan møte ett sett regler hjemme og et annet sett ute.","Barn med to kulturer går på vanlig skole. Det vanskelige kan være ulike regler og forventninger hjemme og ute."],
["Riktig. Å være tospråklig betyr å kunne to språk godt, for eksempel morsmålet og norsk.","Tospråklig handler om språk, ikke om pass eller hvor man har bodd."],
["Riktig. Foreldre bør snakke det språket de kan best. Det hjelper barnet å lære både morsmålet og norsk.","Det beste for barnet er at foreldrene snakker det språket de kan best. Barnet lærer norsk i barnehagen og på skolen."],
["Riktig. Barn med to kulturer kan forstå flere måter å tenke og leve på. Det kan være en styrke.","Alle barn lærer norsk på skolen, og karakterer avhenger ikke av kultur. Styrken er at de kan forstå flere måter å tenke på."],
["Riktig. Når Manar ikke får bli med hjem, kan vennene slutte å invitere henne. Da kan Manar bli mer alene.","Hvis Manar aldri kan bli med hjem, kan vennene slutte å invitere henne. Da kan hun bli ensom."],
["Riktig. Det er vanlig å bli kjent med vennene til barna og foreldrene deres. Da blir det lettere å si ja.","Lærere velger ikke venner for barna. Foreldrene kan bli trygge ved å bli kjent med vennen og foreldrene hennes."],
["Riktig. Når familien flytter til et nytt land, er det viktig å støtte hverandre og snakke sammen.","Familiemedlemmer kan reagere ulikt på å flytte. Da hjelper det å snakke sammen og støtte hverandre."],
["Riktig. Barneoppdragelse kan være forskjellig i ulike familier, samfunn og kulturer.","Barneoppdragelse er ikke lik overalt, og den endrer seg over tid."],
["Riktig. Foreldrene har hovedansvaret, men voksne i barnehage, skole og fritid påvirker også barna.","Tenk på hvor barna er hver dag. Voksne i barnehage, skole og fritidsaktiviteter påvirker dem."],
["Riktig. Et mål er at barna skal lære å delta i samfunnet, få gode verdier og leve et godt liv.","Målet er ikke penger eller å gjøre alt foreldrene sier. Barna skal kunne delta i samfunnet og leve et godt liv."],
["Riktig. Tidligere ble barn sett på som små voksne. Mange måtte jobbe.","Før i tiden ble barn sett på som «små voksne». De fikk mye ansvar og måtte ofte jobbe."],
["Riktig. Før måtte mange barn jobbe for å bidra til familiens inntekt. I dag er det ikke slik.","Før var barn en del av arbeidet i familien. Mange barn måtte jobbe for å skaffe penger."],
["Riktig. I dag er barndommen en tid for lek og læring.","I dag stilles det ikke de samme kravene til barn som før. Barndommen er en tid for lek og læring."],
["Riktig. Foreldre vil vite mye om barnas liv. Derfor er samarbeid med barnehagen og skolen viktig.","Foreldrene skal fortsatt følge opp barna. Samarbeidet gir dem mer kunnskap om barnas hverdag."],
["Riktig. De fleste foreldre synes det er viktig å kjenne vennene til barna og foreldrene deres.","Antall venner eller klasse er ikke det viktigste. Mange foreldre vil kjenne vennene og foreldrene deres."],
["Riktig. Foreldre kan søke råd hos noen som kan mye om barn, snakke med andre foreldre eller lese om emnet.","Det er vanlig at oppdragelse er vanskelig av og til. Det er lurt å be om råd og snakke med andre."],
["Riktig. Det er et godt råd å lytte til barnet og gi ros når barnet gjør noe bra.","Barn trenger at voksne lytter og snakker med dem. Ros hjelper barnet, også når det ikke er stille."],
["Riktig. Å være konsekvent betyr å gjøre det man har sagt og følge reglene man har satt.","Konsekvent betyr ikke straff eller nye regler hele tiden. Det betyr å gjøre det man har sagt."],
["Riktig. I 1987 ble det forbudt i Norge å slå barn, også i oppdragelsen.","Forbudet mot å slå barn kom i 1987. Siden da har all fysisk avstraffelse av barn vært forbudt."],
["Riktig. All vold mot barn er forbudt i Norge, også et lett klaps i oppdragelsen.","Loven forbyr all vold mot barn. Det gjelder også hjemme og også et lett klaps."],
["Riktig. Det er lurt å tenke gjennom vanskelige situasjoner før de skjer. Da vet man bedre hvordan man skal reagere.","Barn trenger fortsatt regler. Når foreldre har tenkt gjennom vanskelige situasjoner, vet de bedre hva de skal gjøre."],
["Riktig. Foreldreveiledning er obligatorisk i introduksjonsprogrammet for deltakere som har barn under 18 år.","Foreldreveiledning er for deltakere som har eller får barn under 18 år."],
["Riktig. Foreldreveiledning er samtaler og kurs om å være forelder, i gruppe eller alene med en veileder.","Foreldreveiledning er hjelp til foreldre. Det er samtaler og kurs, ikke kontroll."],
["Riktig. Det finnes en barnevernstjeneste i alle norske kommuner. Den er åpen på dagtid.","Barnevernet finnes i alle kommuner, også små kommuner."],
["Riktig. Norges første lov om barnevern, vergerådsloven, trådte i kraft i år 1900.","Norge var det første landet i verden med offentlig barnevern. Den første loven kom i år 1900."],
["Riktig. Barnevernets viktigste oppgave er å beskytte barna, helst i samarbeid med familien.","Barnevernet prøver først å hjelpe barnet hjemme, sammen med familien. Å flytte barnet er siste utvei."],
["Riktig. Barnevernet kan for eksempel gi veiledning, avlastning og støttekontakt.","Barnevernet gir ikke lån eller jobb. Det gir hjelp som veiledning, avlastning og støttekontakt."],
["Riktig. Foreldre kan selv be barnevernet om hjelp. Det er bra å ta kontakt tidlig.","Foreldre trenger ikke vente på andre. De kan selv kontakte barnevernet i kommunen."],
["Riktig. Et fosterhjem er et hjem der et barn bor når det ikke kan bo hos foreldrene sine.","Fosterhjem er for barn. Barnevernet kan finne et nytt, trygt hjem når et barn ikke kan bo hjemme."],
["Riktig. Taushetsplikt betyr at de ansatte ikke kan fortelle andre om det de får vite i saken.","Taushetsplikt betyr å ikke fortelle andre om saken. De ansatte kan fortsatt snakke med barnet."],
["Riktig. Avlastning betyr at barnet er hos en annen familie eller et annet sted noen dager. Da får foreldrene hvile.","Avlastning er ikke vasking eller SFO. Barnet er hos andre en kort tid, så foreldrene får hvile."],
["Riktig. En bekymringsmelding er en beskjed til barnevernet når noen er bekymret for et barn.","En bekymringsmelding går til barnevernet. Den sier at noen er bekymret for et barn."],
["Riktig. Barneverns- og helsenemnda bestemmer om barnevernet kan overta omsorgen for et barn.","Barnevernstjenesten kan ikke bestemme dette alene. Det er barneverns- og helsenemnda som bestemmer."],
["Riktig. Alle barn som kan danne seg en mening, har rett til å si den. Det er ingen nedre aldersgrense.","Også små barn har rett til å si sin mening. Det gjelder alle barn som kan danne seg en mening."],
["Riktig. En privatperson kan melde fra til barnevernet uten å si navnet sitt, for eksempel på telefon. På kveld og natt kan man ringe 116 111.","Alle som er bekymret for et barn, bør melde fra til barnevernet. En privatperson kan være anonym."],
["Riktig. Barneloven gjelder for barn og unge under 18 år.","Barneloven gjelder til barnet blir myndig. Myndighetsalderen i Norge er 18 år."],
["Riktig. Når et barn blir født, sendes en melding til Folkeregisteret om mor, far og om de bor sammen.","Fødselen blir meldt til Folkeregisteret. Pass må foreldrene søke om senere."],
["Riktig. Foreldrene må sørge for mat, klær og det barnet trenger, til barnet har fylt 18 år. Går barnet på videregående skole, kan plikten vare lenger.","Foreldrene har dette ansvaret til barnet er myndig, altså 18 år."],
["Riktig. Foreldrene skal passe på at barnet går på grunnskolen. Opplæringen skal passe til barnets evner og interesser.","Foreldrene kan ikke kreve beste karakter eller velge yrke for barnet. De skal passe på at barnet går på skolen."],
["Riktig. Barnet har rett til samvær med begge foreldrene, også når de bor hver for seg.","Penger og alder bestemmer ikke samværet. Barnet har rett til å være sammen med begge foreldrene."],
["Riktig. Når barnet er sju år, skal det få si sin mening. Yngre barn som kan danne seg en mening, skal også få si den.","Barnet får si sin mening mye tidligere enn 15 år. Senest når barnet er sju år, skal det få si sin mening."],
["Riktig. Når barnet har fylt 12 år, skal det legges stor vekt på hva barnet mener.","Barnet bestemmer ikke alt selv når det er 12 år. Men foreldrene skal legge stor vekt på barnets mening."],
["Riktig. Når barnet har fylt 15 år, bestemmer det selv om utdanning og om å melde seg inn i eller ut av foreninger.","Man må være 18 år for å gifte seg og ta opp lån. Med 15 år kan Sofie selv velge utdanning."],
["Riktig. Barn som har fylt 15 år, bestemmer selv om de vil melde seg inn i eller ut av foreninger.","Når barnet har fylt 15 år, bestemmer barnet selv om medlemskap i foreninger og organisasjoner."],
["Riktig. FNs barnekonvensjon er en avtale om barns rettigheter. Den gjelder som norsk lov.","Barnekonvensjonen handler om barn. Den er en avtale mellom land om barns rettigheter."],
["Riktig. Barneombudet passer på at barns rettigheter blir fulgt i Norge.","Barneombudet bestemmer ikke skole og betaler ikke ut penger. Barneombudet passer på barns rettigheter."],
["Riktig. Barnets beste skal være viktigst når voksne tar avgjørelser om barn.","Pris og foreldrenes ønsker er ikke det viktigste. Det som er best for barnet, skal komme først."]
];
