module.exports=[["Riktig. Staten tar ansvar for at alle får den behandlingen de trenger, uansett personlig økonomi.","I et offentlig helsevesen er det staten som har ansvaret. Alle skal få hjelp, også de som har lite penger."],
["Riktig. Når du eller barnet ditt blir syk, kontakter du først fastlegen.","Alle i Norge har rett til en fast lege. Det er denne legen du kontakter først."],
["Riktig. Du kan bytte fastlege inntil to ganger i året, for eksempel på helsenorge.no.","Du velger fastlegen selv. Hvis du ikke er fornøyd, kan du bytte to ganger i året."],
["Riktig. For å komme til en legespesialist trenger du som hovedregel en henvisning fra fastlegen.","En henvisning er et brev fra fastlegen til en spesialist. Det er fastlegen som sender deg videre."],
["Riktig. En øre-nese-hals-lege er en legespesialist. Gynekolog og hudlege er andre eksempler.","En legespesialist er en lege med ekstra utdanning, for eksempel gynekolog, hudlege eller øre-nese-hals-lege."],
["Riktig. På offentlig sykehus er behandling, opphold og mat gratis for pasienten.","Det offentlige betaler alt når du ligger på et offentlig sykehus: behandling, seng og mat."],
["Riktig. Poliklinisk betyr at du får behandling på sykehuset, men ikke blir lagt inn.","Ved poliklinisk behandling har du en time på sykehuset. Når behandlingen er ferdig, drar du hjem."],
["Riktig. Når legekontoret er stengt, ringer du legevakten på 116 117.","Fastlegen har ikke åpent på kvelden og i helgen. Da er det legevakten på 116 117 som hjelper."],
["Riktig. Ved alvorlig sykdom eller skade ringer du medisinsk nødnummer 113 med en gang.","Når noen ikke puster, er det akutt. Da må du ringe 113 med en gang."],
["Riktig. Milde smertestillende tabletter kan du kjøpe på apoteket, i matbutikken og på bensinstasjoner.","De fleste medisiner selges bare på apoteket. Men milde smertestillende kan du også kjøpe i butikken."],
["Riktig. På resepten står navnet på medisinen og hvordan du skal bruke den.","En resept kommer fra legen. Den sier hvilken medisin du skal få, og hvordan du skal bruke den."],
["Riktig. Ved alvorlig og langvarig sykdom kan du få medisiner på blå resept. Da betaler du en liten egenandel.","Blå resept er for personer med alvorlig sykdom som varer lenge. Det handler ikke om inntekt eller botid."],
["Riktig. Alle som jobber i helsevesenet, har taushetsplikt. De kan ikke gi informasjon om deg videre uten at du vil det.","Taushetsplikt betyr at legen ikke kan fortelle andre om deg. Det gjelder også familien din."],
["Riktig. Du har rett til å vite hva legen skriver om deg i journalen din.","Journalen er legens notater om helsen din. Du har rett til å se det som står om deg."],
["Riktig. Hvis du og legen ikke forstår hverandre, har du rett til tolk. Det er gratis for deg.","Du har rett til tolk hos legen når dere ikke forstår hverandre. Du betaler ikke for tolken."],
["Riktig. Helsetjenesten skal bruke en kvalifisert tolk. Tolken har taushetsplikt. Barn skal ikke brukes som tolk.","Familie og venner bør ikke tolke, og loven forbyr å bruke barn som tolk. En kvalifisert tolk er nøytral og har taushetsplikt."],
["Riktig. Folkehelsen i Norge har blitt mye bedre de siste hundre årene. Folk lever lenger.","Velferdssamfunnet har gitt bedre liv. Folk i Norge lever lenger og er friskere enn før."],
["Riktig. Tidligere døde mange av sykdommer som kom av fattigdom, som tuberkulose og underernæring.","For hundre år siden var mange fattige. Da døde mange av tuberkulose og av å få for lite mat."],
["Riktig. Kreft og hjerte- og karsykdommer er de vanligste dødsårsakene i Norge.","Tuberkulose er ikke lenger vanlig i Norge. I dag dør flest av kreft og sykdommer i hjertet og blodårene."],
["Riktig. Diabetes og fedme, det vil si stor overvekt, blir et stadig større problem i Norge.","Sykdommer som henger sammen med livsstil øker. Diabetes og stor overvekt er eksempler."],
["Riktig. De som røyker, har større risiko for å få kreft og hjerte- og karsykdommer.","Tobakk skader kroppen. Røyking øker risikoen for kreft og sykdom i hjertet."],
["Riktig. Vi har større sjanse for å holde oss friske lenger hvis vi spiser sunt og er fysisk aktive.","Kroppen trenger sunn mat og bevegelse. Lite aktivitet og lite mat er ikke bra for helsen."],
["Riktig. I dag tenker mange at vi selv har et stort ansvar. Helsevesenet gir råd, og vi må følge dem.","Helsevesenet gir råd og veiledning. Men måten du lever på, er ditt eget ansvar."],
["Riktig. I Norge er det vanlig at lege og pasient snakker sammen om ulike muligheter for behandling.","Legen i Norge bestemmer ikke alt alene. Du får heller ikke alltid medisin når du går til legen."],
["Riktig. En forkjølelse går ofte over av seg selv i løpet av en ukes tid.","Ved en vanlig forkjølelse trenger du ofte ikke medisin. Kroppen blir frisk av seg selv."],
["Riktig. Helsearbeidere ser at mange innvandrere mangler jern og vitamin D.","Feilernæring betyr at kroppen får for lite av noe den trenger. Mange innvandrere får for lite jern og vitamin D."],
["Riktig. Kroppen lager vitamin D når huden får sol. I Norge er det lite sol store deler av året.","Huden lager vitamin D av sollys. I Norge er vinteren lang og mørk, og da får kroppen for lite."],
["Riktig. De fleste trives godt når de har sosial kontakt med familie, venner eller kolleger.","Mennesker trenger hverandre. God kontakt med andre er viktig for helsen."],
["Riktig. Psykisk helse er like viktig som fysisk helse.","Kropp og tanker henger sammen. Derfor er den fysiske og den psykiske helsen like viktige."],
["Riktig. Stress og tristhet kan gi dårlige matvaner og påvirke både den psykiske og fysiske helsen.","Når vi har det vanskelig, spiser vi ofte dårligere. Det kan gjøre helsen dårligere."],
["Riktig. Alle kan få psykiske problemer, og det kan ha mange årsaker.","Psykiske problemer er vanlige. Mange får det i løpet av livet, uansett hvem de er."],
["Riktig. Psykiske lidelser kan komme etter kriser, dødsfall, ulykker eller opplevelser i krig.","Vanskelige ting i livet, som krig, ulykker eller familieproblemer, kan gi psykiske problemer."],
["Riktig. Kropp og psyke henger sammen. Når vi har det vondt inni oss, kan kroppen også få vondt.","Hvis legen ikke finner noe galt i kroppen, kan årsaken være psykisk, for eksempel tristhet eller stress."],
["Riktig. Fastlegen kan gi deg henvisning til psykolog hvis du trenger det.","Det er fastlegen som kan sende deg videre til en psykolog."],
["Riktig. En psykolog snakker med deg om tanker og følelser og hjelper deg å finne løsninger.","En psykolog er en fagperson som hjelper folk med psykiske problemer, ofte gjennom samtaler."],
["Riktig. Psykologen har taushetsplikt og kan ikke fortelle videre det du sier.","Alle i helsevesenet har taushetsplikt, også psykologen. Du kan snakke trygt."],
["Riktig. De fleste mener at psykisk syke skal få hjelp på lik linje med dem som har fysiske sykdommer.","Synet på psykisk sykdom har endret seg. I dag er de fleste i Norge åpne og vil at psykisk syke skal få hjelp."],
["Riktig. Mange blir friske av psykiske lidelser når de får god hjelp.","De fleste i Norge tror at det er mulig å bli frisk av psykiske lidelser."],
["Riktig. Mental Helse har en gratis hjelpetelefon på 116 123. Den er åpen hele døgnet.","Hvis du trenger noen å snakke med, kan du ringe hjelpetelefonen 116 123. Den er gratis og åpen hele døgnet."],
["Riktig. Når noens liv er i fare, skal du ringe 113 med en gang.","Hvis noen er i akutt fare, må du ikke vente. Ring nødnummeret 113."],
["Riktig. Gode venner, sosial kontakt og god søvn er viktig for den psykiske helsen.","Det er godt for psyken å være sammen med andre og å sove nok."],
["Riktig. Tabu betyr at noe er vanskelig å snakke om. I Norge har det blitt mer åpenhet om psykisk helse.","Når noe er tabu, snakker folk ikke om det. Det er ikke lurt, for det kan gjøre det vanskelig å få hjelp."],
["Riktig. Familieplanlegging betyr at paret selv planlegger når de vil få barn, og hvor mange.","I Norge bestemmer paret selv. Prevensjon gjør det mulig å planlegge barn."],
["Riktig. Kondom er det eneste prevensjonsmiddelet som beskytter mot seksuelt overførbare sykdommer.","P-piller og spiral hindrer graviditet, men beskytter ikke mot smitte. Det gjør bare kondom."],
["Riktig. En p-stav er en liten plaststav under huden. Den skiller ut hormon som hindrer eggløsning.","P-staven legges under huden av en lege. Den gir litt hormon hver dag."],
["Riktig. Gravide i Norge har rett til gratis svangerskapskontroller.","Svangerskapskontroll koster ingenting. Målet er å passe på helsen til mor og barn."],
["Riktig. Svangerskapskontrollene blir gjort på helsestasjonen eller hos fastlegen.","Gravide går til kontroll hos jordmor på helsestasjonen eller hos fastlegen."],
["Riktig. Svangerskapskontrollene er frivillige, men det anbefales sterkt å gå.","Ingen lov sier at du må gå til kontroll. Men kontrollene er viktige for mor og barn."],
["Riktig. Kvinnen kan selv bestemme abort i de første 18 ukene av svangerskapet. En ny abortlov fra 2025 flyttet grensen fra 12 til 18 uker.","Den nye abortloven fra 2025 sier at kvinnen selv kan bestemme abort i de første 18 ukene."],
["Riktig. Det er den gravide kvinnen selv som bestemmer. Ingen kan tvinge henne.","Abortloven sier at kvinnen selv tar avgjørelsen. Ingen andre kan bestemme for henne."],
["Riktig. Helsestasjonen gir gratis helsekontroller til barn fra de er babyer og fram til skolestart.","Babyer og små barn går til kontroll på helsestasjonen. Der sjekker de at barnet vokser og utvikler seg."],
["Riktig. Når et barn er sykt, går man til fastlegen, ikke til helsestasjonen.","Helsestasjonen gir kontroller og vaksiner. Syke barn skal til fastlegen eller legevakten."],
["Riktig. Vaksinene i barnevaksinasjonsprogrammet er gratis og frivillige, men anbefales sterkt.","Ingen lov sier at barn må vaksineres. Men vaksinene er gratis, og myndighetene anbefaler dem sterkt."],
["Riktig. Skolehelsetjenesten gir helsekontroller og vaksiner til skolebarn. Helsesykepleieren er der.","Når barna begynner på skolen, overtar skolehelsetjenesten kontrollene fra helsestasjonen."],
["Riktig. Tannbehandling i den offentlige tannhelsetjenesten er gratis til og med året du fyller 18 år.","Det er barn og unge som får gratis tannbehandling, fram til og med året de fyller 18."],
["Riktig. Fra 19 til 28 år betaler du 25 prosent på offentlig tannklinikk. Det offentlige betaler 75 prosent.","Unge voksne får stor rabatt hos den offentlige tannhelsetjenesten. De betaler bare en fjerdedel."],
["Riktig. Det er vanlig å gå til kontroll hos tannlegen én gang i året.","Voksne bør sjekke tennene jevnlig. Det vanlige er én kontroll i året."],
["Riktig. Alle bør pusse tennene to ganger om dagen, morgen og kveld.","Puss tennene morgen og kveld. Det vil si to ganger om dagen."],
["Riktig. Sukker er skadelig for tennene. Det er mye sukker i brus, saft, kaker og godteri.","Sukker gir hull i tennene. Vann og grønnsaker er bra for tennene."],
["Riktig. Foreldrene har ansvaret for tannhelsen til barna.","Det er foreldrene som må hjelpe barna med tannpuss og gode vaner."],
["Riktig. Dårlige melketenner kan føre til at de nye tennene også blir dårlige.","Melketennene faller ut, men de er likevel viktige. Hull i melketennene kan skade de nye tennene."],
["Riktig. Tannregulering er ikke gratis. Foreldrene betaler en egenandel.","Kontroller og vanlig behandling er gratis for barn. Men for tannregulering må foreldrene betale en del."],
["Riktig. Den offentlige tannhelsetjenesten kaller inn barn og unge til jevnlige kontroller.","Foreldrene trenger ikke bestille selv. Den offentlige tannklinikken sender innkalling til barna."],
["Riktig. Vann er den beste tørstedrikken for tennene.","Brus og saft har mye sukker og syre. Det skader tennene. Drikk vann når du er tørst."],
["Riktig. Den psykiske migrasjonsprosessen har tre faser.","Mange som flytter, går gjennom tre faser: først glede, så en vanskelig tid, og så blir livet lettere."],
["Riktig. Den første tiden er det vanlig å føle seg glad og optimistisk. Alt det nye er spennende.","I fase 1 tenker man mest på nye muligheter. Man er ofte glad og har det travelt."],
["Riktig. I fase 2 føles livet vanskelig. Man savner livet slik det var før.","I fase 2 forstår man hva flyttingen betyr. Mange blir slitne og savner hjemlandet."],
["Riktig. I fase 3 føles livet lettere. Man forstår mer av språket og systemet.","I fase 3 har man akseptert flyttingen. Framtiden ser lysere ut."],
["Riktig. Hvor lenge fasene varer, er forskjellig fra menneske til menneske.","Fasene har ingen fast lengde. For noen går det fort, for andre tar det lang tid."],
["Riktig. Amaniel er i fase 2. Han er sliten og savner det han har mistet.","Når man er sliten og savner livet før, er man i fase 2."],
["Riktig. Man finner sin plass når man kombinerer det positive i det nye landet med verdier fra hjemlandet.","Du trenger ikke glemme hvem du er. Mange finner sin plass ved å kombinere det nye og det gamle."],
["Riktig. Ulike familiemedlemmer kan være i ulike faser til ulike tider.","Alle reagerer ikke likt. Barn og voksne i samme familie kan være i ulike faser."],
["Riktig. Identitet er hvordan vi oppfatter oss selv.","Identitet handler om hvem du er og hvordan du ser på deg selv."],
["Riktig. Identiteten formes av egenskaper og personlighet, og av hvor vi bor, hvem vi er sammen med og interessene våre.","Identiteten handler om personlighet og om livet vi lever, for eksempel venner og interesser."],
["Riktig. Hvem man blir forelsket i og tiltrukket av, sier noe om seksuell identitet.","Seksuell identitet handler om hvem man blir forelsket i."],
["Riktig. Hvordan man kler seg eller på andre måter viser kjønn, kaller vi kjønnsuttrykk.","Kjønnsuttrykk er hvordan du viser kjønn utad, for eksempel med klær, hår eller sminke."],
["Riktig. Kjønnsidentitet er hvilket kjønn en person opplever å være.","Kjønnsidentitet handler om hvordan du selv opplever kjønnet ditt."],
["Riktig. I dag er det større åpenhet for at ikke alle føler seg som gutt eller jente.","Før delte man kjønn i to. Nå er det mer åpenhet for at noen opplever kjønn på en annen måte."],
["Riktig. Heteroseksuell betyr at man blir forelsket i personer av motsatt kjønn.","Hetero betyr ulik. En heteroseksuell blir forelsket i en av motsatt kjønn."],
["Riktig. Likestillings- og diskrimineringsloven forbyr diskriminering på grunn av seksuell orientering, kjønnsidentitet og kjønnsuttrykk.","Loven sier at ingen skal behandles dårligere på grunn av hvem de blir forelsket i. Det gjelder også på jobb og i boligmarkedet."]];
