module.exports=[["Riktig. Under istiden lå det et lag med is over Nord-Europa. Isen var opptil 3000 meter tykk.","Tenk på ordet istid. Det var veldig kaldt, og landet var dekket av noe hvitt og hardt."],
["Riktig. De første menneskene kom til Norge for rundt tolv tusen år siden, da isen begynte å smelte.","Menneskene kom etter at isen begynte å smelte. Det er mange tusen år siden, men ikke så lenge som femti tusen år."],
["Riktig. De første menneskene fisket, fanget dyr og plukket bær og sopp.","I starten hadde folk ikke åkre eller husdyr. De fant maten sin i naturen."],
["Riktig. Folk laget redskaper og våpen av stein, bein og tre. Derfor heter perioden steinalderen.","Navnet handler om det folk brukte til å jakte og arbeide med. De hadde ikke metall ennå."],
["Riktig. Folk begynte å dyrke jorda i Norge for rundt fire tusen år siden.","Jordbruket kom lenge etter de første menneskene, men flere tusen år før vår tid."],
["Riktig. I bronsealderen begynte bøndene å bruke hest som trekkdyr. Kvinnene lærte også å spinne og veve ull.","Jern kom først senere, og kirker kom med kristendommen. I bronsealderen fikk bøndene hjelp av et dyr."],
["Riktig. Folk fant jernmalm i myrene. De smeltet malmen og laget jern.","Jernmalm er en type stein eller jord med jern i. Folk fant den i våt og bløt mark."],
["Riktig. Med redskaper av jern ble det lettere å dyrke jorda. Det ble mer mat, og folketallet steg.","Jern er hardt og sterkt. Tenk på hva bøndene kunne gjøre bedre med gode redskaper."],
["Riktig. Vikingtiden var fra rundt år 800 til rundt år 1050. Den var den siste delen av jernalderen.","Vikingtiden sluttet omtrent da kristendommen ble vanlig i Norge, på 1000-tallet."],
["Riktig. Høvdingene var de rikeste og mektigste bøndene. De hadde soldater som forsvarte landet deres.","Høvdingene bodde på de største gårdene og hadde mye makt i området sitt."],
["Riktig. Mange vikinger var dyktige handelsfolk, men de kriget og plyndret også.","Vikingene reiste for å bli rike. De gjorde det både på fredelige og voldelige måter."],
["Riktig. Ifølge gamle fortellinger ble Harald Hårfagre konge over hele Norge rundt år 872.","Denne kongen samlet landet på 800-tallet, lenge før slaget på Stiklestad i 1030."],
["Riktig. Vikingene trodde på de norrøne gudene. Gudene skulle hjelpe med god avling, barn og krig.","Vikingene hadde sin egen gamle religion med mange guder fra Norden."],
["Riktig. Olav Haraldsson var kristen og kjempet mot høvdinger som trodde på de gamle gudene. Han tapte og døde.","Stiklestad ligger i Trøndelag. Der kjempet en kristen konge mot mektige høvdinger."],
["Riktig. Sønnen til Olav fikk hjelp av kirken til å gjøre faren til helgen. Han blir ofte kalt Olav den hellige.","En helgen er en person som kirken mener var spesielt hellig. Mange kaller ham Olav den hellige."],
["Riktig. Da de som hadde makt skiftet tro, gjorde flere og flere vanlige folk det samme.","Vanlige folk fulgte ofte etter de mektige i samfunnet. Tenk på hvem som ble kristne først."],
["Riktig. Folk måtte betale skatt til kirken, og mange ga også land til kirken. Slik fikk kirken stor makt.","Kirken ble rik og mektig i middelalderen. Folk måtte betale til kirken på flere måter."],
["Riktig. Bøndene betalte skatt til kirken, kongen og adelen. De som ikke kunne betale, måtte gi fra seg jord.","I vikingtiden eide de fleste bøndene jorda si selv. Senere måtte de betale mye til kirken, kongen og adelen."],
["Riktig. Trondheim het Nidaros. Det var en av de første byene i Norge.","Bjørgvin var det gamle navnet på Bergen, og Kristiania var navnet på Oslo i en periode."],
["Riktig. Svartedauden var en pandemi på midten av 1300-tallet. En pandemi er en sykdom som sprer seg til mange land.","Svartedauden var ikke en krig. Mange mennesker ble smittet, og de fleste døde etter noen få dager."],
["Riktig. De som ble smittet, fikk store blåsvarte byller på kroppen.","Navnet handler om hvordan kroppen til de syke så ut."],
["Riktig. Gamle kilder forteller at pesten kom med et skip fra England til Bergen i 1349.","Sykdommen spredte seg ofte med handel. Den kom til en stor by ved havet på Vestlandet."],
["Riktig. Rundt halvparten av folket i Europa døde. I Norge døde kanskje en tredel eller enda flere.","Svartedauden var en av de verste katastrofene i Europa. Mange døde, men ikke nesten alle."],
["Riktig. En union betyr at land er knyttet sammen. Norge hadde felles konge med Danmark i flere hundre år.","En union er et samarbeid. Landene blir knyttet tett sammen, for eksempel under samme konge."],
["Riktig. Unionen fra 1397 kalles Kalmarunionen. Sverige gikk senere ut, men Norge og Danmark var i union helt til 1814.","Unionen fra 1397 samlet de tre skandinaviske landene under én konge."],
["Riktig. Politikken ble styrt fra København, og nordmenn leste og skrev på dansk.","Unionen ble styrt fra hovedstaden i Danmark. Det påvirket også språket."],
["Riktig. I 1517 protesterte Martin Luther mot makten til den katolske kirken. De som fulgte ham, ble kalt protestanter.","Ordet kommer fra «å protestere». Martin Luther var uenig med den katolske kirken."],
["Riktig. Protestantismen var statsreligion fra 1500-tallet og fram til Grunnloven ble endret i 2012.","Ordningen med statskirke varte veldig lenge, mye lenger enn unionen med Sverige."],
["Riktig. Danmark-Norge sto på Frankrikes side i Napoleonskrigene. Da Frankrike tapte, måtte Danmark gi fra seg Norge.","Tenk på Napoleonskrigene. Danmark-Norge og Frankrike var på samme side."],
["Riktig. I fredsavtalen i Kiel måtte den danske kongen gi Norge til Sverige. Sverige hadde stått på Englands side.","Landet hadde vunnet krigen sammen med England. Det er et naboland til Norge."],
["Riktig. 112 mektige menn møttes på Eidsvoll. De ville skrive en grunnlov for et selvstendig Norge.","Mange nordmenn håpet at Norge kunne bli et fritt land da unionen med Danmark tok slutt."],
["Riktig. Norge ble tvunget inn i unionen. Sommeren 1814 var det en kort krig mot Sverige.","Mange nordmenn ønsket ikke en ny union. Norge hadde ikke noe valg."],
["Riktig. Norge fikk beholde grunnloven og Stortinget og styrte mye selv i landet.","I unionen med Sverige fikk Norge beholde mye. Tenk på grunnloven og Stortinget."],
["Riktig. Utenrikspolitikken ble styrt fra Sverige. Norge hadde indre selvstyre.","Norge styrte sakene inne i landet selv. Sverige bestemte i saker om forholdet til andre land."],
["Riktig. Karl Johan var svensk konge over både Sverige og Norge. Hovedgata i Oslo har navn etter ham.","Gata har navn etter en mann som styrte begge landene i unionstiden."],
["Riktig. Nasjonalromantikken var en retning i litteratur, bilder og musikk rundt midten av 1800-tallet.","Nasjonalromantikken kunne du se i malerier, høre i musikk og lese i bøker."],
["Riktig. Kunstnerne viste den vakre naturen og bondesamfunnet som det typisk norske.","Tenk på maleriene fra denne tiden. De viste fjell, fjorder og folk på landet."],
["Riktig. Etter lang tid i union med Danmark var skriftspråket dansk. Bokmål er en fornorsking av dansk.","Husk at Norge var i union med Danmark i flere hundre år. Det påvirket skriftspråket."],
["Riktig. Mange ønsket et skriftspråk som ikke kom fra dansk. Aasen samlet eksempler fra dialektene og laget nynorsk.","Aasen reiste mye rundt i landet og hørte på hvordan folk snakket."],
["Riktig. Arbeidsdagene var lange, og flere familier kunne bo sammen i en liten leilighet. Mange barn måtte også jobbe.","Livet i byen var vanskelig for mange arbeidere. Boforholdene var dårlige."],
["Riktig. Folketallet økte, og det var ikke nok jord og arbeid til alle. Mange flyttet derfor til byene.","Det ble født mange barn, og befolkningen vokste. Tenk på hva det betyr for gårdene."],
["Riktig. Mer enn åtte hundre tusen nordmenn utvandret til Amerika i denne perioden.","Svært mange reiste. Tallet er mye høyere enn hele befolkningen i en stor norsk by den gangen."],
["Riktig. Å utvandre er å flytte fra landet sitt for å bo i et annet land. Mange nordmenn utvandret til Amerika.","Ordet «ut» viser retningen. Du forlater landet ditt for å bo et annet sted."],
["Riktig. Reaksjonene i Sverige var voldsomme, og det var nær ved å bli krig. Men landene løste det fredelig.","Sverige var ikke glad for at unionen ble brutt. Situasjonen var farlig en stund."],
["Riktig. I 1905 var det to folkeavstemninger. Den første handlet om unionen, den andre om at Norge skulle ha konge.","Et monarki er et land med konge eller dronning. Folket stemte om hvem som skulle være statsoverhode."],
["Riktig. Den danske prins Carl ble konge og tok navnet Haakon 7. Han var konge til han døde i 1957.","Den nye kongen kom ikke fra Sverige. Han tok det norske navnet Haakon."],
["Riktig. Norge har mange fosser. Vannkraften ga strøm, og det kom flere fabrikker.","Vann som faller med stor kraft, kan gi energi. Tenk på hva fabrikkene trengte."],
["Riktig. Først bestemte Stortinget at ingen skulle jobbe mer enn ti timer om dagen. I 1919 ble det endret til åtte.","Fagforeningene fikk gjennom kortere arbeidsdager. I 1919 ble grensen satt lavere enn ti timer."],
["Riktig. Syketrygd betyr at arbeiderne fikk penger fra staten når de var syke.","Ordet syketrygd har to deler: syk og trygd. Trygd er penger du får fra staten."],
["Riktig. Fra 1898 kunne alle menn over 25 år stemme ved stortingsvalg. Kvinnene måtte vente til 1913.","Kvinnene fikk ikke stemmerett ved stortingsvalg før i 1913. Tenk på hvem som fikk den først."],
["Riktig. Fagforeningene ønsket bedre forhold for arbeiderne og presset på. Da kom lover om kortere dager og syketrygd.","Arbeiderne organiserte seg for å få bedre forhold. Tenk på hvem som kjempet for dem."],
["Riktig. Norge var ikke aktivt med i første verdenskrig, men landet merket krigen gjennom mangel på varer.","Krigen var i Europa fra 1914 til 1918. Norge holdt seg utenfor kampene."],
["Riktig. Under første verdenskrig var det mangel på korn, kaffe og sukker. Derfor ble varene delt, og hver person fikk kjøpe bare en viss mengde.","Rasjonering brukes når det er for lite av en vare. Da må varene deles."],
["Riktig. Det var økonomisk krise i nesten hele mellomkrigstiden, og mange var arbeidsledige.","Mellomkrigstiden var en vanskelig tid for økonomien i mange land, også i Norge."],
["Riktig. 9. april 1940 kom tyske tropper til Norge. Etter rundt to måneder med kamper måtte Norge gi seg.","Den andre verdenskrigen begynte i 1939. Året etter kom krigen også til Norge."],
["Riktig. Under okkupasjonen hadde Tyskland makten i Norge. Det varte i fem år.","Okkupasjon er noe som skjer i krig. En fremmed makt kommer inn og bestemmer."],
["Riktig. Kongen og regjeringen flyktet til England. Derfra fortsatte de kampen for et fritt Norge.","Kongen og regjeringen måtte forlate Norge. De dro til et land som kjempet mot Tyskland."],
["Riktig. Quisling ledet en regjering som samarbeidet med tyskerne. Den var ikke valgt av folket.","Quisling samarbeidet med okkupasjonsmakten. I mange språk betyr ordet «quisling» en forræder."],
["Riktig. Motstandsgrupper ødela ting tyskerne trengte og ga ut ulovlige aviser. Mange gjorde også passiv motstand.","Motstandsbevegelsen kjempet mot okkupasjonen. De arbeidet i hemmelighet."],
["Riktig. Rundt femti tusen nordmenn flyktet til Sverige. Sverige var ikke med i krigen.","De flyktet til et naboland som ikke var med i krigen."],
["Riktig. På ordre fra Hitler ble det meste av hus, veier og bruer brent da tyskerne trakk seg ut.","Tyskerne trakk seg ut av området. De ville ikke at fienden skulle kunne bruke noe der."],
["Riktig. Over 770 jøder ble sendt fra Norge til leirer i Europa. Bare rundt 35 av dem overlevde.","Jødene ble forfulgt under krigen. Deportert betyr at de ble sendt ut av landet med tvang."],
["Riktig. Etter krigen måtte mye bygges opp igjen, for eksempel hus, veier og fabrikker. Dette kalles gjenreisingen.","Krigen hadde ødelagt mye, særlig i Nord-Norge. Det var mye som måtte gjøres."],
["Riktig. Arbeiderbevegelsen og kvinnebevegelsen har hatt stor betydning for lovene og rettighetene vi har i dag.","Tenk på bevegelser som kjempet for arbeiderne og for likestilling mellom kjønnene."],
["Riktig. Arbeiderbevegelsen ble mer organisert da det kom flere arbeidsplasser i industrien.","Arbeiderbevegelsen vokste fram der mange arbeidet sammen, for eksempel på fabrikker."],
["Riktig. Arbeiderbevegelsen har kjempet for blant annet støtte ved arbeidsledighet, kortere dager og tryggere arbeidsplasser.","Arbeiderbevegelsen har kjempet for bedre vilkår for arbeidstakerne, ikke dårligere."],
["Riktig. Kvinnebevegelsen har kjempet for kvinners rettigheter og for like muligheter for kvinner og menn.","Kvinnebevegelsen ville at kvinner skulle få de samme rettighetene som menn."],
["Riktig. I 1970-årene skjøt kvinnekampen fart igjen. Viktige saker var blant annet prevensjon og selvbestemt abort.","Kvinnebevegelsen var aktiv fra 1880-årene. Den ble sterk igjen omtrent hundre år senere."],
["Riktig. Gro Harlem Brundtland ble statsminister i 1981. Hun var den første kvinnen i Norge med denne jobben.","Camilla Collett og Aasta Hansteen kjempet for kvinners rettigheter på 1800-tallet. Statsministeren kom mye senere."],
["Riktig. Likestillingsloven kom i 1978. Den sa at kvinner og menn skal ha like muligheter.","Like rettigheter for kvinner og menn kalles likestilling. Loven har fått navn etter dette."],
["Riktig. Ekofisk ble funnet i 1969. Det var starten på at Norge ble en stor oljenasjon.","Dette funnet gjorde Norge til et rikt land. Det handler om energi."],
["Riktig. Akkurat som vannkraften er oljen i offentlig eie. Private selskaper kan få lov til å lete og bore i en viss tid.","Det er det samme som med vannkraften. Ressursene skal komme hele folket til gode."],
["Riktig. Det er ikke enighet om hvilke følger oljeindustrien har for natur og miljø.","Diskusjonen i dag handler om hvordan oljen påvirker klimaet og naturen."],
["Riktig. Gratis skole, kortere arbeidsdager og syketrygd kom før det ble funnet olje.","Mange velferdsordninger er eldre enn oljen. Tenk på skolen og retten til penger når du er syk."],
["Riktig. Ved to folkeavstemninger stemte et knapt flertall nei til medlemskap. EF var navnet på EU før.","Norge er ikke medlem av EU i dag. Det henger sammen med resultatet i disse to avstemningene."],
["Riktig. Norge er ikke med i EU, men gjennom EØS gjelder mange EU-regler også i Norge. Avtalen gjelder fra 1994.","EØS betyr Det europeiske økonomiske samarbeidsområdet. Det knytter Norge til EU."],
["Riktig. Norge deltar i FN, NATO og EØS. Norge er ikke medlem av EU.","Husk at Norge sa nei til EU to ganger."],
["Riktig. I dag bor rundt åtti prosent i byer og tettsteder. Før 1850 var det bare rundt femten prosent.","Mange har flyttet fra landsbygda til byene de siste hundre årene. I dag bor de fleste i byer."],
["Riktig. Industrien trengte flere arbeidere. Mange kom for eksempel fra Pakistan, Tyrkia og Jugoslavia.","Rundt 1970 gikk det godt for norsk økonomi. Tenk på hva bedriftene trengte."],
["Riktig. En terrorist drepte 77 mennesker i regjeringskvartalet i Oslo og på Utøya. Dagen blir minnet hvert år.","Dette var et angrep på demokratiet. Mange av dem som døde, var ungdom på en politisk leir."]];
