module.exports=[
["Kildekritikk betyr å vurdere om informasjonen stemmer, og hvem som står bak.","Kildekritikk er ikke å være uenig. Det er å vurdere om noe stemmer."],
["Vi må være kritiske fordi alle kan legge ut ting på nettet.","Nettet er åpent for alle. Det er ikke bare staten som skriver, og ikke alt er på engelsk."],
["Spør hvem som har skrevet teksten, og om det stemmer.","Se på avsenderen og fakta, ikke på hvor mange som har delt eller hvor pen siden er."],
["Etisk bevissthet betyr å tenke på ulike hensyn når du velger.","Etikk er å tenke på både deg selv og andre, ikke bare på dine egne ønsker."],
["Kritisk tenkning betyr å tenke over og vurdere informasjon.","Kritisk tenkning er ikke å være negativ. Det er å vurdere godt."],
["I Norge kan alle ha sin egen mening.","I Norge er det fint å ha egne meninger. Du trenger ikke å være enig med læreren."],
["Vi lærer nye ting når vi spør og diskuterer.","Kunnskap utvikles når vi stiller spørsmål, ikke når vi bare gjentar."],
["Du må som regel få lov fra den som har laget verket, og oppgi navnet.","Det er ikke nok å endre litt eller spørre vennene dine. Den som har laget verket, bestemmer."],
["Se på hvem som har skrevet, og hvorfor.","Antall følgere og magefølelse sier lite om hva som stemmer."],
["Et samfunn med mye informasjon kalles et informasjonssamfunn.","Tenk på ordet «informasjon» i navnet."],
["Etikk handler om hvordan man bør oppføre seg.","Etikk handler om rett og galt, ikke om penger eller skolefag."],
["Faktisk.no sjekker fakta i debatter.","Datatilsynet og Medietilsynet har andre oppgaver. Tenk på ordet «fakta»."],
["De må se på utslipp og hvor mye plass bilen har.","Se på det familien bryr seg om, ikke på farge eller merke."],
["Agenda betyr her at avsenderen vil oppnå noe med teksten.","Her betyr agenda en skjult hensikt, ikke en plan for et møte."],
["TikTok, Facebook og Instagram er sosiale medier.","Sosiale medier lar folk dele og snakke sammen. E-post og nettsider for jobb er noe annet."],
["Personvern er retten til å bestemme over dine opplysninger.","Personvern handler om dine egne opplysninger, ikke om ytringsfrihet."],
["Navn, adresse og telefonnummer er personopplysninger.","Personopplysninger sier noe om en person, ikke om været eller en butikk."],
["Spør personene om lov før du deler bildet.","Det viktigste er hva de som er på bildet, vil."],
["Trusler og hatefulle ytringer er forbudt, for eksempel mot noen på grunn av hudfarge eller religion.","Du kan kritisere og ha negative meninger. Men trusler og hatefulle ytringer er forbudt."],
["God digital dømmekraft er å skrive det du kan si ansikt til ansikt.","Tenk: Ville jeg sagt dette rett til personen?"],
["Når man er anonym, skriver mange stygge eller ulovlige ting.","Anonymitet gjør at noen skriver verre ting, ikke bedre."],
["Digitale spor er det du gjør på nettet, og som blir lagret.","Sporene blir værende. De forsvinner ikke etter noen timer."],
["Du kan vise hvem du er med BankID, passord eller fingeravtrykk.","Fødselsdato og e-post er ikke trygge nok til å vise hvem du er."],
["Personvernet og noen regler i loven begrenser ytringsfriheten.","Ytringsfriheten er lik i hele landet. Kommuner og flertall bestemmer ikke."],
["Privatliv er ting som bare gjelder deg og familien din.","Privat betyr at det gjelder deg og dine nærmeste, ikke jobben eller staten."],
["Noen kan bruke kontoen din og dele bilder hvis de får passordet ditt.","Tenk på hva en fremmed kan gjøre, ikke på hva som skjer av seg selv."],
["Det kan være ulovlig å dele private bilder av andre. Du kan melde det til politiet.","Ytringsfriheten gir ikke rett til å dele private bilder av andre uten lov."],
["Andre kan få vite ting om deg og bruke dem.","Det du deler, kan bli værende og kan sees av flere enn vennene dine."],
["Falske nyheter er usann informasjon som ser ut som nyheter.","Falske nyheter handler om at innholdet er usant, ikke om hvor de kommer fra."],
["Sjekk om pålitelige kilder skriver det samme.","Sjekk først. Ikke del før du vet at det stemmer."],
["En pålitelig kilde sier hvem som står bak, og viser hvor fakta kommer fra.","Mange følgere og store overskrifter sier ikke at noe er pålitelig."],
["Avsenderen er den som har laget informasjonen.","Avsender er den som sender eller lager, ikke den som leser."],
["Klikkbait er en overskrift som lokker deg til å klikke.","Klikkbait handler om overskrifter, ikke om virus eller betaling."],
["Bilder kan være endret eller tatt ut av sammenheng.","Tenk på at et bilde kan vise noe annet enn det som blir sagt."],
["En kilde er stedet informasjonen kommer fra.","Kilden er opprinnelsen, ikke stedet der noe slettes, og ikke den som leser."],
["Flere kilder gir et bedre bilde av saken.","Poenget er å få flere sider av saken, ikke å dele mer."],
["Et bildesøk på nett kan vise om et bilde er gammelt eller falskt.","Fremmede og likes viser ikke om et bilde er ekte."],
["«Oslo er hovedstaden i Norge» er et faktum.","Et faktum kan sjekkes. Det som er best eller vakrest, er en mening."],
["En mening er det en person mener om noe.","Meninger kan ikke bevises. Politikerne bestemmer dem ikke, og de står ikke i loven."],
["Reklame vil få deg til å kjøpe noe.","Reklame har et mål: salg. Den er ikke laget av en offentlig etat."],
["Journalister undersøker og skriver nyheter.","Journalister lager ikke lover og bestemmer ikke hva folk skal mene."],
["Seriøse medier retter feil når de får vite om dem.","Pålitelige medier skriver ikke bare det som gir flest klikk."],
["En algoritme er regler som bestemmer hva du ser i appen.","Algoritmen er et dataprogram, ikke en ansatt og ikke en slettefunksjon."],
["Ulike meninger gir deg et bedre grunnlag for å vurdere saken.","Å lese andre meninger er å tenke selv, ikke å bli enig med flertallet."],
["Ytringsfrihet er retten til å si og skrive det du mener.","Ytringsfrihet gjelder dine egne meninger, ikke å bestemme over andre."],
["Ytringsfriheten står i Grunnloven.","Tenk på landets viktigste lov."],
["Hatprat er krenkende utsagn om en bestemt gruppe.","Hatprat er ikke uenighet eller høy stemme. Det er å krenke en gruppe."],
["Diskriminering er å behandle noen dårligere på grunn av bakgrunn.","Diskriminering er urettferdig forskjellsbehandling, ikke like rettigheter."],
["Du kan melde fra til nettstedet eller politiet.","Ikke svar med mer hat. Meld fra i stedet."],
["Nettmobbing er å plage eller krenke noen igjen og igjen.","Nettmobbing er mer enn uenighet eller kritikk."],
["Ta skjermbilde og snakk med en du stoler på.","Ikke slett bevisene, og ikke svar med trusler."],
["Trusler er forbudt, også på nett.","Ytringsfriheten gir ikke rett til å true, heller ikke med falskt navn."],
["Sensur er når noen forbyr eller stopper en ytring.","Sensur handler om å stoppe det folk vil si."],
["Du kan kritisere regjeringen. Det er en viktig del av demokratiet.","Kritikk av dem som styrer er lov og viktig. Du trenger ikke tillatelse."],
["Fødselsnummeret har 11 siffer og er bare ditt. Mange kaller det personnummer.","Nummeret viser hvem du er. Det sier ikke noe om lønn eller bolig."],
["Bare de som trenger det, som banken og Nav, bør få personnummeret ditt.","Personnummeret er sensitivt. Ikke gi det til alle."],
["Datatilsynet passer på personvernet.","Skatt og pass hører til andre etater."],
["Et sterkt passord er langt og har tall og tegn.","Navn og enkle ord er lette å gjette."],
["Bruk ulike passord på ulike nettsteder.","Samme passord overalt og deling med andre gjør det lettere for svindlere."],
["En kode på mobilen gjør kontoen din tryggere.","Koden er for sikkerhet. Den gjør ikke nettet raskere og sletter ingenting."],
["En cookie er en liten fil som husker hva du gjør på nettsiden.","Cookies er små filer. De er ikke virus og ikke en avgift."],
["Firmaer vil bruke opplysningene dine til å vise deg reklame.","Firmaer vil tjene penger. De vil ikke hjelpe deg eller sende opplysningene til skolen."],
["Sjekk hvem som kan se innleggene dine.","Du bestemmer selv hvem som ser innleggene dine. Se i innstillingene."],
["Sjekk hvem som får opplysningene og hvorfor.","Les gjerne vilkårene før du gir fra deg noe."],
["Nettfiske er svindel der noen later som de er en annen.","Phishing er svindel. Det er ikke et søkeverktøy eller et program."],
["Ikke klikk, men sjekk med postselskapet.","Meldinger om pakker kan være svindel. Ikke trykk på lenken."],
["Avslutt samtalen og ikke si koden.","Banken ber aldri om BankID-koden din på telefon."],
["Mange skrivefeil og hast kan være tegn på svindel.","Svindlere vil at du skal skynde deg. Vær forsiktig, også når meldingen ser ut til å komme fra en du kjenner."],
["Noen kan lage et falskt wifi-nett og lure deg. Bruk heller mobildata til nettbank.","Åpent wifi er ikke ulovlig, men det kan være usikkert."],
["Oppdateringer retter sikkerhetsfeil.","Oppdateringer gjør telefonen tryggere. De gjør den ikke billigere, og de sletter ikke bilder."],
["Et virus er et skadelig program.","Et virus gjør skade. Det gjør ikke maskinen raskere."],
["Logg ut så ingen andre kommer inn på kontoen din.","Hensikten er sikkerhet, ikke fart eller penger til banken."],
["BankID er en elektronisk ID for trygg innlogging.","BankID er ikke et kort for butikken og ikke et nummer fra politiet."],
["Meld fra om svindel til politiet og banken din.","Svindel melder du til politiet og banken, ikke til Skatteetaten eller kommunen."],
["Et etisk dilemma er et valg mellom to ting som begge er viktige.","Et dilemma er vanskelig. Det finnes ikke alltid et klart svar."],
["Lever lommeboken til politiet eller eieren.","Pengene tilhører eieren. Tenk på å gjøre det som er riktig."],
["Kritisk tenkning betyr også å kunne endre mening når du får bedre fakta.","Kritisk tenkning er åpen, ikke stiv, men heller ikke tilfeldig."],
["God debattkultur er å diskutere saken, ikke personen.","Alle skal få snakke ferdig. Ikke avbryt og ikke rop."],
["Opphavsrett er retten til å bestemme over eget verk.","Opphavsrett beskytter den som har laget noe."],
["En deepfake er en falsk video eller et bilde laget med KI.","Deepfake handler om falske bilder og videoer, ikke om ulovlige kopier."],
];
