module.exports=[["Riktig. Det blir født omtrent 50 000 barn i Norge hvert år.","Norge har 5–6 millioner innbyggere. Da blir det født omtrent 50 000 barn hvert år."],
["Riktig. En kvinne i Norge får i gjennomsnitt omtrent 1,4 barn.","Det er færre barn i hver familie enn mange tror. Gjennomsnittet er omtrent 1,4 barn."],
["Riktig. Kvinner i Norge får første barn når de er omtrent 30 år.","Mange tar utdanning og jobber først. Da blir kvinnen omtrent 30 år når hun får første barn."],
["Riktig. Omskjæring av jenter er forbudt i Norge. Straffen kan være opptil 15 år i fengsel.","Omskjæring av jenter er forbudt i Norge, også når foreldrene ønsker det."],
["Riktig. I barnehagen er små barn mens foreldrene jobber eller studerer.","Barna lærer å lese og skrive på skolen. I barnehagen leker og lærer de gjennom dagen."],
["Riktig. En egenandel er den delen av prisen som du betaler selv.","En egenandel er ikke en støtte eller et lån. Det er prisen du betaler selv."],
["Riktig. Foreldre betaler en egenandel. Staten og kommunen betaler resten.","Foreldre betaler en del av prisen. Barnehagen er ikke gratis, og foreldrene betaler ikke hele prisen."],
["Riktig. Kontantstøtte er penger til foreldre som ikke bruker barnehage.","Kontantstøtte er til foreldre med små barn. Barna går ikke i barnehage."],
["Riktig. Foreldrepenger er penger fra Nav. Du får dem når du er hjemme med et nytt barn.","Det er Nav som betaler foreldrepenger, ikke barnehagen eller skolen."],
["Riktig. Staten betaler barnetrygd til foreldrene.","Barnetrygd kommer fra staten, ikke fra arbeidsgiveren eller barnehagen."],
["Riktig. Foreldre får barnetrygd til barnet fyller 18 år.","Barnetrygden varer lenger enn til skolestart. Den slutter når barnet er 18 år."],
["Riktig. Barnetrygden er lik for alle barn. Familiens penger spiller ingen rolle.","Barnetrygden er den samme for rike og fattige familier. Inntekten har ikke noe å si."],
["Riktig. Grunnskolen har ti år, fra 1. til 10. klasse.","Grunnskolen er barneskole og ungdomsskole sammen. Det blir til sammen ti år."],
["Riktig. Barneskolen er fra 1. til 7. klasse.","Barneskolen varer lenger enn fire år. Etter 7. klasse begynner barna på ungdomsskolen."],
["Riktig. Elever på ungdomsskolen er omtrent 13 til 16 år gamle.","Ungdomsskolen er 8. til 10. klasse. Elevene er da omtrent 13 til 16 år."],
["Riktig. Barn må gå på skole fra de er seks år. Skolen varer til de er 16 år.","Barn begynner på skolen når de er seks år, ikke før og ikke etter."],
["Riktig. Offentlig grunnskole er gratis i Norge.","Foreldre betaler ikke skolepenger i offentlig grunnskole. Skolen er gratis."],
["Riktig. SFO betyr skolefritidsordning. Barna er der før og etter skoletid.","SFO er ikke et fag eller en egen skole. Det er et tilbud ved siden av skoledagen."],
["Riktig. Omtrent åtte av ti barn i 1. til 4. klasse går på SFO.","SFO er et vanlig tilbud. De fleste barn på de laveste trinnene bruker det."],
["Riktig. Nesten åtte av ti elever fullfører videregående skole.","Det er flere enn seks av ti. Nesten åtte av ti elever fullfører."],
["Riktig. Omtrent halvparten velger yrkesfag, og halvparten velger studiespesialisering.","Yrkesfag er et vanlig valg. Omtrent halvparten av elevene velger det."],
["Riktig. Studiespesialisering gir studiekompetanse. Da kan du søke på universitet og høgskole.","Fagbrev får du på yrkesfag. Studiespesialisering gir rett til å søke studier."],
["Riktig. Etter yrkesfag og læretid kan du ta fagprøve og få fagbrev.","En bachelorgrad tar du på universitet. Etter læretid får du fagbrev."],
["Riktig. En lærling lærer et yrke på en arbeidsplass og har betalt arbeid.","En lærling er ikke student. Lærlingen arbeider og lærer et yrke på en arbeidsplass."],
["Riktig. En bachelorgrad tar omtrent tre år på universitet eller høgskole.","Bachelor tar du på universitet eller høgskole, ikke på videregående skole."],
["Riktig. Et stipend er penger som du ikke må betale tilbake.","Penger som du må betale tilbake kalles lån. Et stipend er en gave."],
["Riktig. Lånekassen gir lån og stipend til studenter.","Nav og Skatteetaten har andre oppgaver. Lånekassen gir studielån."],
["Riktig. Mange studenter har over 300 000 kroner i studiegjeld.","Studielån er mye penger. Mange har over 300 000 kroner i gjeld etter studiene."],
["Riktig. Når du er myndig, bestemmer du selv over livet og pengene dine.","Myndig betyr at du er voksen etter loven. Da bestemmer du selv."],
["Riktig. Myndighetsalderen i Norge er 18 år.","Du er myndig når du fyller 18 år, ikke før og ikke senere."],
["Riktig. Foreldrene har ansvar for barn under 18 år.","Barn under 18 år er ikke myndige. Foreldrene har ansvaret, ikke skolen."],
["Riktig. Mange gifter seg når de er mellom 30 og 40 år gamle.","I Norge gifter folk seg ofte sent. Mange er mellom 30 og 40 år."],
["Riktig. Samboere er et par som bor sammen uten å være gift.","Samboere er et par. De bor sammen, men er ikke gift."],
["Riktig. Ved skilsmisse avslutter et gift par ekteskapet sitt.","Skilsmisse handler om å avslutte et ekteskap. Det gjelder ikke samboere som flytter."],
["Riktig. Likestilling betyr at kvinner og menn har samme rettigheter og muligheter.","Likestilling betyr ikke samme arbeid. Det betyr samme rettigheter og muligheter."],
["Riktig. Et boliglån er penger du låner i banken for å kjøpe bolig.","Penger til utleier kalles husleie. Et boliglån får du fra en bank."],
["Riktig. Boliger er dyre. Mange har over to millioner kroner i boliglån.","Boliger i Norge koster mye. Lånet er ofte over to millioner kroner."],
["Riktig. Nav betaler ut pensjon fra folketrygden.","Lånekassen gir studielån og Skatteetaten tar imot skatt. Nav betaler ut pensjon."],
["Riktig. Mange slutter å jobbe når de er omtrent 67 år.","De fleste jobber lenger enn til 50 år, men slutter før 80 år. Vanlig alder er omtrent 67 år."],
["Riktig. Ved kremasjon blir den døde brent. Asken kan så gravlegges.","Å legge en kiste i jorden kalles kistegravlegging. Kremasjon er noe annet."],
["Riktig. Arv er penger og ting som du får når et familiemedlem dør.","Arv har med dødsfall å gjøre. Du får den ikke ved giftermål eller fødselsdag."],
["Riktig. I et testament står det hvem som skal arve etter personen.","Et testament handler om arv. Det handler ikke om eierskap eller ekteskap."],
["Riktig. En innvandrer har flyttet til Norge fra et annet land.","En innvandrer bor i Norge, men har flyttet fra et annet land."],
["Riktig. Med oppholdstillatelse har du lov til å bo i Norge.","Oppholdstillatelse handler om å bo i landet, ikke om bil eller jobb."],
["Riktig. UDI behandler søknader om oppholdstillatelse.","Nav hjelper med trygd og arbeid. UDI behandler søknader om opphold."],
["Riktig. På udi.no finner du regler for opphold i Norge.","Nav og Skatteetaten har egne nettsider. Informasjon om opphold finner du på udi.no."],
["Riktig. Borgere fra EU og EØS registrerer seg hos politiet.","EU- og EØS-borgere registrerer seg hos politiet, ikke hos Nav eller kommunen."],
["Riktig. En midlertidig tillatelse varer en periode. Etterpå må du søke på nytt.","Midlertidig betyr at det varer en periode. Det er ikke en tillatelse for livet."],
["Riktig. Med permanent tillatelse kan du bo i Norge uten å søke på nytt.","Permanent tillatelse er ikke det samme som statsborgerskap. Du slipper bare nye søknader."],
["Riktig. Med statsborgerskap hører du til et land. Du har rettigheter og plikter.","Statsborgerskap er mer enn besøk eller arbeid. Du hører til landet."],
["Riktig. En flyktning må forlate landet sitt fordi livet er i fare.","Noen flytter for jobb eller studier. En flyktning må forlate landet sitt."],
["Riktig. En arbeidsinnvandrer flytter til et nytt land for å jobbe.","Arbeid er grunnen til at en arbeidsinnvandrer flytter. Det er ikke FN eller familie."],
["Riktig. En asylsøker har søkt om beskyttelse og venter på svar.","En asylsøker venter på svar. Hun eller han har ikke fått svar ennå."],
["Riktig. Asyl er beskyttelse for personer som er forfulgt i hjemlandet.","Asyl er ikke en jobb- eller besøkstillatelse. Det er beskyttelse mot forfølgelse."],
["Riktig. Hver person får en egen vurdering av sin sak.","Hver sak er ulik. Personer fra samme land kan få ulike svar."],
["Riktig. Kvoteflyktninger er valgt ut før de kommer til Norge.","Kvoteflyktninger kommer ikke på egen hånd. De er valgt ut på forhånd."],
["Riktig. UNHCR er FNs flyktningorganisasjon. De hjelper Norge å velge flyktninger.","NATO og EU velger ikke kvoteflyktninger til Norge. Det gjør UNHCR i FN."],
["Riktig. Kvoteflyktninger får først en midlertidig tillatelse.","Permanent tillatelse og statsborgerskap kommer senere. Først får de en midlertidig tillatelse."],
["Riktig. Ved familiegjenforening får et familiemedlem flytte til familie i Norge.","Familiegjenforening handler om å samles igjen. Det handler ikke om skatt eller bolig."],
["Riktig. Introduksjonsprogrammet er et opplæringstilbud for nyankomne flyktninger.","Introduksjonsprogrammet er ikke TV eller et skolefag. Det er et tilbud til flyktninger."],
["Riktig. Deltakerne skal lære norsk og komme i jobb eller utdanning.","Programmet handler om språk, jobb og utdanning, ikke om pass eller bolig."],
["Riktig. Kommunen tilbyr introduksjonsprogram til flyktninger.","Det er kommunen som tilbyr programmet, ikke arbeidsgiveren eller politiet."],
["Riktig. Kommunen tilbyr programmet til flyktninger som har fått opphold.","Arbeidsinnvandrere og studenter har andre ordninger. Programmet er for flyktninger."],
["Riktig. Programmet kan vare fra tre måneder til tre år.","Programmet er lenger enn en måned, men kortere enn fem år. Det varer fra tre måneder til tre år."],
["Riktig. Deltakerne får økonomisk støtte mens de er med i programmet.","Deltakerne får penger som støtte. Bil og pass er ikke en del av programmet."],
["Riktig. Støtten hjelper deltakerne å leve mens de lærer norsk.","Støtten er ikke en belønning og ikke betaling for kurset. Den hjelper deltakerne å leve."],
["Riktig. Opplæring i norsk er en viktig del av programmet.","Programmet foregår i Norge. Deltakerne lærer norsk, men reiser ikke ut."],
["Riktig. Integrering betyr at nyankomne blir en del av samfunnet.","Integrering betyr å bli med i samfunnet. Det betyr ikke å reise hjem eller bo atskilt."],
["Riktig. Integreringsloven sier at kommunene skal tilby introduksjonsprogram.","Skoleloven og straffeloven handler om andre ting. Loven heter integreringsloven."],
["Riktig. Stortinget har vedtatt integreringsloven.","Lover blir vedtatt av Stortinget. Kommunen og UDI følger lovene."],
["Riktig. Kommunen gir informasjon om introduksjonsprogrammet.","Politiet og banken har ikke ansvar for programmet. Spør kommunen."],
["Riktig. Det bor over fem millioner mennesker i Norge.","Norge er et lite land. Likevel bor det over fem millioner mennesker her."],
["Riktig. Norge er et demokrati. Kongen har en symbolsk rolle.","Folket velger politikerne. Kongen styrer ikke landet."],
["Riktig. Det er stortingsvalg hvert fjerde år.","Valg hvert år eller hvert tiende år er ikke riktig. Det er hvert fjerde år."],
["Riktig. Du må være norsk statsborger og minst 18 år.","Du må være statsborger og minst 18 år. Botid alene er ikke nok."],
["Riktig. I en velferdsstat hjelper staten innbyggerne med blant annet skole og helse.","Velferdsstat betyr ikke at staten eier alt. Staten hjelper innbyggerne med skole og helse."],
["Riktig. Innbyggerne betaler skatt, og staten bruker pengene på velferd.","Velferden betales med skatt fra innbyggerne, ikke av kongen eller andre land."],
["Riktig. Nasjonaldagen er 17. mai.","1. mai er arbeidernes dag. 8. mai er frigjøringsdagen. Nasjonaldagen er 17. mai."],
["Riktig. Norge fikk grunnloven i 1814.","1905 og 1945 er viktige år, men grunnloven er fra 1814."],
["Riktig. I 1905 gikk Norge ut av unionen med Sverige.","Unionen med Danmark tok slutt i 1814. I 1905 gikk Norge ut av unionen med Sverige."]];
