module.exports=[["Riktig. Utgifter er alt vi bruker penger på, som husleie, mat, strøm og klær.","Penger som kommer inn, som lønn og trygd, er inntekter. Utgifter er penger som går ut."],
["Riktig. Nettolønn er det du får på kontoen etter at skatten er trukket.","Lønn før skatt heter bruttolønn. Nettolønn er det som er igjen etter skatt."],
["Riktig. Et budsjett viser inntekter og utgifter i en periode, for eksempel en måned.","Et budsjett er en plan. Det viser hvor mye penger som kommer inn og går ut."],
["Riktig. Sparing gjør at du kan betale uforutsette utgifter, for eksempel en reparasjon.","Sparing gir ikke lavere skatt eller mer støtte. Den gir trygghet hvis noe uventet skjer."],
["Riktig. Mer enn 35 prosent av forbruket går til bolig. Mat er omtrent 11 prosent.","Det er dyrt å bo i Norge. Bolig er den største utgiften for de fleste."],
["Riktig. Begge de voksne i familien er ansvarlige for familiens økonomi.","I Norge deler de voksne ansvaret for økonomien, uansett hvem som tjener mest."],
["Riktig. Brukte klær og møbler er ofte mye billigere. Barn kan også arve klær.","Det er billigere å kjøpe brukt, for eksempel på finn.no eller hos Fretex."],
["Riktig. Du sparer strøm når du slår av lyset og har litt lavere temperatur inne.","Åpne vinduer og lys som står på, bruker mer strøm. Slå av lyset og senk varmen."],
["Riktig. For å åpne bankkonto trenger du et norsk personnummer eller D-nummer.","Du trenger ikke være norsk borger eller ha jobb. Du trenger personnummer eller D-nummer."],
["Riktig. Du logger inn i nettbanken med BankID eller kodebrikke.","Pass og adresse er ikke nok på nett. Du må ha BankID eller kodebrikke."],
["Riktig. Renter er prisen for å låne penger. De blir regnet i prosent av gjelden.","Det du betaler ned på selve lånet, heter avdrag. Renter er prisen for å låne."],
["Riktig. Avdrag er det du betaler ned på selve lånet.","Prisen for lånet heter renter. Avdrag er det du betaler tilbake av selve lånet."],
["Riktig. Nedbetalingsplanen viser hva du skal betale hver måned eller hvert kvartal.","Når du låner, får du en plan fra banken. Den viser hva du skal betale og når."],
["Riktig. Effektiv rente viser hva lånet koster totalt, også gebyrene.","Effektiv rente gjelder prisen på et lån. Den tar med både renter og gebyrer."],
["Riktig. Et forbrukslån har ikke bolig eller bil som sikkerhet. Derfor er renten ofte høy.","Boliglån har boligen som sikkerhet. Forbrukslån har ingen sikkerhet og høyere rente."],
["Riktig. Forbrukslån er dyre. Renten er ofte mye høyere enn på boliglån.","Problemet med forbrukslån er prisen. Den høye renten gjør lånet dyrt."],
["Riktig. Det du ikke betaler, blir et lån med høy rente.","Banken sletter ikke gjelden. Du må betale høy rente på det du skylder."],
["Riktig. Gjeldsregisteret viser gjeld uten sikkerhet, som forbrukslån og kredittkort. Det er gratis å sjekke.","Boliglån og studielån er ikke med. Registeret viser forbrukslån og kredittkort."],
["Riktig. Nav gir gratis råd om økonomi og gjeld. Telefonen er 55 55 33 39.","Nav har økonomiske rådgivere. Ring 55 55 33 39 eller kontakt Nav-kontoret."],
["Riktig. Det er viktig å få hjelp tidlig. Nav gir gratis råd om gjeld.","Nye lån og uåpnede brev gjør problemet større. Be om hjelp så tidlig som mulig."],
["Riktig. Når du betaler for sent, kan du få purregebyr og forsinkelsesrente.","Regningen forsvinner ikke. Den blir dyrere med gebyr og renter."],
["Riktig. Et inkassobyrå krever inn penger for andre når regninger ikke blir betalt.","Et inkassobyrå gir ikke lån eller råd. Det krever inn regninger som ikke er betalt."],
["Riktig. Gjeldsordning er en plan der du betaler det du klarer, vanligvis i fem år.","Bostøtte og startlån gjelder bolig. Ved alvorlig gjeld kan du søke om gjeldsordning."],
["Riktig. En kausjonist må betale lånet hvis den som lånte, ikke klarer det.","Å kausjonere er et løfte. Du må betale hvis den som lånte, ikke betaler."],
["Riktig. KID-nummeret viser mottakeren hvilken regning du betaler. Skriv det riktig.","Beløp og dato står for seg selv. KID-nummeret viser hva betalingen gjelder."],
["Riktig. Forfallsdatoen er fristen. Du bør betale senest denne dagen.","Forfallsdato betyr frist. Betaler du etter denne dagen, kan du få gebyr."],
["Riktig. Med AvtaleGiro blir regningen betalt automatisk på forfallsdatoen.","AvtaleGiro er ikke et lån. Det er en avtale om at banken betaler regningen automatisk."],
["Riktig. Uten skattekort må arbeidsgiveren trekke 50 prosent skatt av lønnen.","Uten skattekort blir trekket høyt, 50 prosent. Bestill skattekort hos Skatteetaten."],
["Riktig. Du bestiller og endrer skattekortet på skatteetaten.no.","Det er Skatteetaten som lager skattekort. Arbeidsgiveren henter det derfra."],
["Riktig. Med frikort betaler du ikke skatt når inntekten er under en viss grense.","Frikort handler om skatt. Du slipper skatt hvis du tjener lite i løpet av året."],
["Riktig. Fristen er 30. april. Du kan også endre skattemeldingen etterpå.","Skattemeldingen kommer i mars. Du må sjekke og levere den innen 30. april."],
["Riktig. Skattemeldingen regnes som levert med opplysningene som står der. Derfor må du sjekke den.","Du blir ikke straffet med dobbel skatt. Men skattemeldingen blir levert som den er, også med feil."],
["Riktig. Skatteoppgjøret viser om du har penger til gode eller må betale restskatt.","Skatteoppgjøret gjelder skatten for i fjor. Det viser om du får igjen eller må betale."],
["Riktig. De fleste har halv skatt i desember. Til gjengjeld trekkes litt mer skatt resten av året.","Det er skattetrekket som er lavere. De fleste har bare halvt skattetrekk i desember."],
["Riktig. BSU betyr boligsparing for ungdom. Du kan spare til og med året du fyller 33 år.","BSU er ikke et lån eller en støtte. Det er en sparekonto for unge som vil kjøpe bolig."],
["Riktig. Da blir du et «pengemuldyr». Det er hvitvasking, og du kan få fengselsstraff.","Det er ulovlig å la andre bruke kontoen din, uansett avtale eller beløp. Si nei og kontakt banken."],
["Riktig. Løfter om mye penger på kort tid er et vanlig tegn på svindel.","Svindlere lager fine nettsider og bruker kjente navn. Si nei til løfter om rask gevinst."],
["Riktig. Ved kjøp på nett har du 14 dager angrerett fra dagen etter at du fikk varen.","Angreretten på nett er 14 dager. Den starter når du har fått varen."],
["Riktig. Angreretten gjelder blant annet på nett og ved dørsalg. I butikken gjelder byttereglene.","Loven gir ikke angrerett i vanlig butikk. Spør butikken om byttereglene."],
["Riktig. Klagefristen er minst to år. For ting som skal vare mye lenger, som mobiler, er den ofte fem år.","Klagefristen er minst to år. For ting som skal vare lenge, er den fem år."],
["Riktig. Forbrukerrådet gir råd og kan hjelpe deg når du er uenig med en butikk.","Forbrukerrådet hjelper forbrukere med klager på varer og tjenester."],
["Riktig. Finansportalen viser priser fra bankene, så du kan finne det billigste.","Bankene må melde prisene sine til Finansportalen. Der kan du sammenligne."],
["Riktig. Finanstilsynet kontrollerer banker, forsikringsselskaper og andre finansforetak.","Finanstilsynet gir ikke lån og krever ikke inn skatt. Det kontrollerer bankene."],
["Riktig. Sperr kortet med en gang i nettbanken eller appen, eller ring banken.","Andre kan bruke kortet ditt. Sperr det med en gang."],
["Riktig. Rundt 82 prosent eier boligen sin. Rundt 18 prosent leier.","De fleste i Norge eier boligen sin. Det gjelder omtrent åtte av ti husholdninger."],
["Riktig. Omtrent halvparten av boligene i Norge er eneboliger.","I store byer er det mange blokker. Men i hele landet er enebolig vanligst."],
["Riktig. I store byer bor mange i blokker og bygårder. I mindre kommuner er eneboliger vanligst.","I byene er det lite plass. Derfor bor mange i blokker og bygårder."],
["Riktig. I en selveierbolig betaler du selv forsikring, kommunale avgifter og vedlikehold.","En andel i et lag er borettslag. I en selveierbolig eier du boligen og betaler alt selv."],
["Riktig. Du eier en andel og har rett til å bruke din egen bolig.","I et borettslag eier du en andel. Borettslaget eier bygningen."],
["Riktig. Felleskostnadene (husleien) dekker din del av fellesgjelden, kommunale avgifter og forsikring.","Felleskostnadene gjelder det dere har felles, som fellesgjeld, avgifter og forsikring."],
["Riktig. Du må ha godkjenning fra styret for å leie ut boligen i et borettslag.","I et borettslag er det styret som må godkjenne utleie."],
["Riktig. I et sameie eier du din egen leilighet. Dere eier fellesarealene sammen.","Andel og fellesgjeld hører til borettslag. I et sameie eier du leiligheten din selv."],
["Riktig. Egenkapital er penger du har selv når du skal kjøpe bolig.","Lån er ikke egenkapital. Egenkapital er dine egne penger."],
["Riktig. Hovedregelen er 10 prosent egenkapital. Da kan du låne 90 prosent.","Du kan ikke låne alt. Hovedregelen er at du må ha 10 prosent selv."],
["Riktig. Banken må være sikker på at du kan betale renter og avdrag.","Banken ser mest på inntekten din. Du må kunne betale lånet tilbake."],
["Riktig. Banken skal vanligvis ikke gi lån hvis all gjelden blir mer enn fem ganger inntekten.","Regelen er fem ganger årsinntekten. Det gjelder all gjeld til sammen."],
["Riktig. Startlån er for dem som over tid har problemer med å få vanlig boliglån.","Startlån er ikke for hytter eller ekstra boliger. Det hjelper folk som ikke får vanlig lån."],
["Riktig. Du søker hos kommunen. Kommunen bestemmer om du får lån.","Startlån kommer fra kommunen. Husbanken låner ut pengene til kommunene."],
["Riktig. Bostøtte er for deg som har lav inntekt og høye boutgifter.","Bostøtte er ikke et lån. Det er støtte til boutgifter når inntekten er lav."],
["Riktig. Bostøtte er en statlig ordning i Husbanken. Kommunen hjelper og behandler søknaden.","Du søker om bostøtte hos Husbanken. Kommunen kan hjelpe deg med søknaden."],
["Riktig. Når selgeren har fått budet ditt, kan du ikke trekke det før fristen er ute.","Et bud er et løfte. Sier selgeren ja innen fristen, har dere en avtale."],
["Riktig. Finansieringsbeviset viser hvor mye banken vil låne deg.","Finansieringsbeviset kommer fra banken. Det viser hvor mye du kan låne."],
["Riktig. Der står det om boligen, om feil og mangler og om hva den koster.","Les dokumentene om boligen. Salgsoppgaven og tilstandsrapporten forteller om feil og mangler."],
["Riktig. Eierskiftet blir tinglyst i grunnboken. Det er Kartverket som har ansvaret for den.","Folkeregisteret viser hvor du bor, ikke hva du eier. Eiere står i grunnboken hos Kartverket."],
["Riktig. Kommunale avgifter er for vann, avløp og renovasjon (søppel).","Strøm og internett betaler du til firmaer. Kommunen tar betalt for vann, avløp og søppel."],
["Riktig. Utleierens forsikring dekker ikke tingene til leietakeren. Hun trenger innboforsikring.","Bygningen er utleierens ansvar. Fatima må forsikre sine egne ting med innboforsikring."],
["Riktig. Både leietaker og utleier kan kreve skriftlig kontrakt. Forbrukerrådet har en gratis mal.","Loven sier at begge kan kreve kontrakt på papir. Det er lurt å ha en skriftlig avtale."],
["Riktig. Depositum kan være høyst seks måneders husleie. Ofte er det tre måneder.","Loven setter en grense. Depositum kan ikke være mer enn seks måneders husleie."],
["Riktig. Depositumet skal stå på en depositumskonto i ditt navn. Ingen av dere kan ta ut penger alene.","Utleieren skal ikke ha depositumet selv. Det skal stå på en egen konto i leietakerens navn."],
["Riktig. Ikke betal depositum eller husleie før du har sett boligen og har en kontrakt.","Visning og kontrakt er normalt. Vær forsiktig hvis noen vil ha penger før du har sett boligen."],
["Riktig. Hvis dere ikke har avtalt noe annet, er oppsigelsestiden tre måneder.","Loven sier tre måneder hvis dere ikke har avtalt noe annet."],
["Riktig. Husleien kan øke med prisstigningen én gang i året. Du skal få skriftlig varsel en måned før.","Utleieren kan ikke øke husleien fritt. Det kan skje én gang i året."],
["Riktig. Leietakeren skal teste røykvarsleren og bytte batteri.","Det er den som bor i boligen, leietakeren, som skal teste og bytte batteri."],
["Riktig. Utleieren har hovedansvaret. Leietakeren tar seg av små ting, som røykvarsler og kraner.","Det er eieren, altså utleieren, som har hovedansvaret for vedlikehold."],
["Riktig. Det er forbudt å diskriminere ved utleie, for eksempel på grunn av religion eller etnisitet.","Loven forbyr diskriminering ved utleie. Det gjelder også når det står i en annonse."],
["Riktig. Husleietvistutvalget løser konflikter om leie av bolig i hele landet.","Konflikter om husleie går til Husleietvistutvalget, HTU."],
["Riktig. Du må melde flytting til Folkeregisteret hos Skatteetaten senest 8 dager etter at du flyttet.","Folkeregisteret må vite hvor du bor. Meld flytting på skatteetaten.no."],
["Riktig. Bilder viser hvordan boligen var. Da slipper du å betale for gamle skader.","Bildene er bevis. De viser skader som var der før du flyttet inn."],
["Riktig. Utleieren må gi beskjed i god tid, hvis det ikke er en skade som haster.","Selv om utleieren eier boligen, er det ditt hjem. Utleieren må varsle før besøk."],
["Riktig. En tidsbestemt kontrakt skal vanligvis vare minst tre år. I noen tilfeller kan det være ett år.","Loven gir leietakeren trygghet. En tidsbestemt kontrakt skal som regel vare minst tre år."]];
