module.exports=[
["Fra 1700-tallet skulle alle barn gå på skole, og staten skulle betale.","Tenk på at Norge ville at alle barn skulle få lære noe, også barn fra fattige familier."],
["Skolen skulle lære barna kristendommen.","Den gangen var religion det viktigste faget i skolen."],
["Norge har hatt skoleplikt i omtrent 300 år.","Skoleplikten er eldre enn 100 år. Den begynte allerede på 1700-tallet."],
["Elevene skal lære å finne god informasjon og bruke den.","Skolen vil at elevene bruker nettet til å lære, ikke bare til fritid."],
["Kommunen betaler den største delen, og foreldrene betaler resten.","Tenk på hvem som har ansvar for tjenester i nærmiljøet, som barnehage og skole."],
["Stortinget har bestemt hvor mye foreldrene maksimalt skal betale.","Det er politikerne som bestemmer regler som gjelder for hele landet."],
["Søskenmoderasjon betyr lavere pris når du har flere barn i barnehagen.","Ordet har med søsken å gjøre. Barn nummer to betaler mindre."],
["Familier med lite penger kan søke om lavere pris eller gratis kjernetid.","Barnehagen kan hjelpe med prisen, men gir ikke gratis plass til alle eller penger til klær."],
["Foreldre som ikke kan norsk, har rett til å ha med tolk på foreldremøte.","Retten gjelder hjelp til å forstå møtet, ikke at møtet holdes på et annet språk."],
["Barnehagen bygger på kristne og humanistiske verdier.","Verdiene står i barnehageloven og gjelder for alle barnehager i landet."],
["Barnehagen skal fremme demokrati og likestilling.","Tenk på verdier som gjør at alle får si sin mening og er like mye verdt."],
["De aller fleste barn mellom 1 og 5 år går i barnehage.","Barnehage er svært vanlig i Norge. Tenk på at nesten alle barn går der."],
["Barnehagen samarbeider med foreldrene gjennom foreldremøter og foreldresamtaler.","Barnehagen og foreldrene snakker sammen på møter og samtaler. Små barn får ikke karakterer."],
["Grunnskolen i Norge er 10 år.","Tenk på barnetrinnet og ungdomstrinnet til sammen."],
["Barn begynner på skolen i august det året de blir seks år.","Skolen starter etter sommerferien, og barna er seks år det året."],
["Barnetrinnet er 1. til 7. trinn.","Barnetrinnet er lengre enn fem eller seks år. Ungdomstrinnet er 8. til 10. trinn."],
["Barn på barnetrinnet får en muntlig eller skriftlig vurdering, ikke karakterer.","Karakterer kommer først på ungdomstrinnet. Før det får elevene en vurdering."],
["På ungdomstrinnet er karakterene fra 1 til 6, og 6 er best.","I Norge er 6 den beste karakteren i grunnskolen, og skalaen bruker tall."],
["Grunnskolen har blant annet matematikk, norsk, engelsk og naturfag.","Se etter fag som alle barn har på vanlig skole."],
["Elevene i grunnskolen flyttes automatisk opp til neste klasse.","I grunnskolen trenger ikke elevene å bestå en prøve for å gå videre."],
["Det er forbudt å slå barn i Norge, både hjemme og på skolen.","Loven er lik for alle barn: Det er forbudt å slå dem, også hjemme."],
["Grunnskolen bygger blant annet på nestekjærlighet, likeverd og solidaritet.","Skolen legger vekt på at alle er like mye verdt og skal hjelpe hverandre."],
["Alle elever i Norge følger den samme læreplanen.","Læreplanen er lik for hele landet. Det er ikke kommunen eller skolen som lager den."],
["Elever som trenger ekstra hjelp, får hjelp, vanligvis på sin egen skole.","Barn som trenger hjelp skal få den, ofte der de allerede går."],
["Alle barn har samme rett til opplæring, uansett kjønn og hvor de bor.","Retten til skole er lik for alle barn."],
["Elevene i Norge bruker ikke skoleuniform.","Tenk på hva elever vanligvis har på seg på norske skoler."],
["Eleven, foreldrene og læreren snakker sammen minst to ganger i året.","Samtalene skjer oftere enn én gang i året, og de er faste."],
["Samtalen heter utviklingssamtale.","Samtalen handler om hvordan eleven utvikler seg. Tenk på ordet «utvikling»."],
["Foreldrene har hovedansvaret for barna sine.","Skolen og kommunen hjelper til, men hovedansvaret ligger hos andre."],
["Foreldre bør lese informasjonen fra skolen nøye og følge med.","Informasjon fra skolen er viktig for alle foreldre. Les den, ikke bare når noe er galt."],
["Foreldre kan kontakte læreren eller skolen hvis de lurer på noe.","Du trenger ikke å vente. Skolen vil gjerne at foreldre tar kontakt."],
["Alle elever skal ha det bra og bli respektert på skolen.","Et godt sted for alle handler om trivsel og respekt, ikke om karakterer."],
["Elevene lærer demokrati ved å være med og bestemme, for eksempel i elevrådet.","Elevene får være med og bestemme, men lærerne har fortsatt ansvar."],
["Skolen forventer at foreldre kommer på møter og samtaler.","Foreldre samarbeider med skolen, men det er læreren som underviser."],
["Elevene jobber i grupper for å lære at alle må hjelpe til.","Gruppearbeid handler om samarbeid og felles ansvar, ikke om konkurranse."],
["Elever som har fullført grunnskolen, har rett til plass på videregående.","Retten gjelder alle som har fullført grunnskolen, ikke bare noen."],
["Yrkesfaglig utdanning gir et fagbrev i et praktisk yrke.","Vitnemål og mastergrad hører til andre utdanninger. Yrkesfag gir et bevis for et praktisk yrke."],
["Bilmekaniker er en yrkesfaglig utdanning.","Yrkesfag er praktiske yrker. Sykepleier og ingeniør tar du på høgskole eller universitet."],
["Du må søke om videregående skole før 1. mars.","Fristen kommer tidlig på våren, før mai og juni."],
["Studentene betaler ikke skolepenger, men må kjøpe bøkene selv.","Offentlige universiteter er gratis i Norge, men studentene har noen egne utgifter."],
["Du må søke om studieplass før 15. april.","Fristen er om våren, tidligere enn mai og juni."],
["Lånekassen gir lån og stipend til skole og studier.","Lånekassen gir penger til utdanning, ikke bolig eller lønn."],
["Lån må du betale tilbake, men stipend betaler du ikke tilbake.","Husk: Et stipend er en gave, men et lån må betales tilbake."],
["Du begynner vanligvis å betale tilbake lånet etter at du er ferdig å studere.","Man betaler ikke mens man studerer, og man trenger ikke vente på fast jobb."],
["Lånekassen ble startet i 1947.","Lånekassen er eldre enn 1957. Tenk på tiden rett etter krigen."],
["Lånekassen finnes slik at alle kan ta høyere utdanning.","Hensikten er å gi alle mulighet til å studere, ikke bare de beste."],
["Voksne kan få stipend og lån til grunnskole og videregående.","Lånekassen gir støtte også til voksne som tar grunnskole eller videregående."],
["Å lære hele livet kalles livslang læring.","Ordet sier at man lærer gjennom hele livet. Tenk på «lang» og «læring»."],
["Mange må lære noe nytt fordi ny teknologi endrer jobbene.","Tenk på hva som endrer seg i arbeidslivet, for eksempel datamaskiner og roboter."],
["Voksne som ikke har fullført grunnskole, har rett til forberedende opplæring (FOV).","FOV er for voksne som mangler grunnskole, ikke for dem som har jobb eller har bodd lenge i Norge."],
["Kommunen tilbyr grunnskole for voksne.","Staten og fylkeskommunen har andre oppgaver. Tenk på hvem som har ansvar for grunnskolen."],
["Voksne må ha fullført grunnskole, i Norge eller et annet land.","Kravet handler om grunnskole, ikke om norsktest eller antall år i Norge."],
["Videregående skole for voksne er gratis på offentlige skoler.","Offentlig utdanning er gratis i Norge, men private skoler kan koste penger."],
["Du søker HK-dir om godkjenning av utdanning fra utlandet.","UDI og Lånekassen har andre oppgaver. Tenk på direktoratet for høyere utdanning."],
["Helsepersonell søker Helsedirektoratet om autorisasjon.","Godkjenning for helsepersonell kommer fra et direktorat for helse."],
["Realkompetansevurdering er en vurdering av det du kan fra jobb og skole.","Det handler om det du kan fra før, ikke om norsk eller valg av jobb."],
["Norskopplæringen har nivåene A1, A2, B1 og B2.","Nivåene kommer fra et felles europeisk system med bokstav og tall."],
["Med videregående eller høyere utdanning har du opptil 18 måneder.","Tiden er litt lengre enn ett år, men kortere enn to år."],
["Uten videregående skole har du opptil tre år.","Du har lengre tid enn 18 måneder, men ikke fem år."],
["Norskmålet bestemmes etter utdanningen du har fra før.","Målet avhenger av utdanning, ikke av alder eller hvor du bor."],
["Et felles språk skaper fellesskap mellom folk.","Språk binder mennesker sammen. Alle trenger ikke å mene det samme."],
["Du lærer norsk best når du snakker det med naboer og kolleger.","Bruk norsk i hverdagen. Du trenger ikke å vente til du kan alt."],
["Barn har rett til opplæring i 13 år, altså grunnskole og videregående.","Tenk på grunnskolen (10 år) pluss videregående (tre år)."],
["Studieforberedende utdanning gir vitnemål, og da kan du studere videre.","Fagbrev hører til yrkesfag. Studieforberedende gir vitnemål."],
["Du har rett til plass til du har fullført en utdanning.","Retten gjelder til du er ferdig utdannet, ikke et bestemt antall år."],
["Etter hvert kom praktiske ting som skriving og regning inn i skolen.","Tenk på ferdigheter alle trenger i hverdagen, som å skrive og regne."],
["Skolen legger vekt på respekt, omtanke og felles ansvar.","Skolen handler om å ta vare på hverandre, ikke om konkurranse eller streng disiplin."],
["Leirskole er når klassen bor og lærer sammen noen dager.","Leirskole er en del av skolen. Det er ikke en ferie eller en leir for lærere."],
["Foreldre bør snakke med skolen på forhånd om fraværet.","Det beste er å si fra til skolen før dere reiser."],
["8. til 10. trinn kalles ungdomstrinnet.","Trinnet kommer etter barnetrinnet og før videregående."],
["Utdannede folk kan vurdere informasjon og ta gode valg i et demokrati.","Utdanning gir kunnskap, så folk kan tenke selv og velge godt."],
["Fylkeskommunen har ansvar for videregående opplæring for voksne.","Tenk på hvem som har ansvar for videregående skole."],
["Norskopplæringen slutter med en norskprøve som viser nivået ditt.","Opplæringen avsluttes med en prøve, ikke bare en samtale eller et kursbevis."],
["Realkompetansevurdering kan gi kortere utdanning eller studieplass.","Den kan hjelpe deg i utdanning og jobb, men gir ikke skattefritak eller bolig."],
["HK-dir er Direktoratet for høyere utdanning og kompetanse.","HK-dir er en statlig etat, ikke en forening eller et firma."],
["Barnehage er et sted der små barn leker og lærer.","Barnehagen er for små barn, ikke for foreldre eller syke barn."],
["I barnehagen lærer barna å ta hensyn til andre og klare seg selv.","Barnehagen handler om lek og samvær, ikke om skolefag som brøk."],
["I kroppsøving skal alle elever delta sammen, både jenter og gutter.","Kroppsøving er et vanlig fag for alle elever."],
["I samfunnsfag lærer elevene om hvordan samfunnet fungerer.","Tenk på faget som handler om mennesker, regler og samfunn."],
["Karakterene fra grunnskolen avgjør hvem som får plass.","Plass avhenger av karakterene dine, ikke av hvem som søker først eller av foreldrenes jobb."],
];
